//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotifClavesWeb.ADCambioContrasenia {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.cts.ast", ConfigurationName="ADCambioContrasenia.ADCambioContrasenia")]
    public interface ADCambioContrasenia {
        
        // CODEGEN: Parameter 'executeReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="execute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="executeReturn")]
        NotifClavesWeb.ADCambioContrasenia.executeResponse execute(NotifClavesWeb.ADCambioContrasenia.executeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://domain.webservices.common.cts.ast")]
    public partial class RequestConnection : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userField;
        
        private string passwordField;
        
        private string applicationIDField;
        
        private string sessionIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string applicationID {
            get {
                return this.applicationIDField;
            }
            set {
                this.applicationIDField = value;
                this.RaisePropertyChanged("applicationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string sessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
                this.RaisePropertyChanged("sessionID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://domain.webservices.common.cts.ast")]
    public partial class ServiceError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<long> codeField;
        
        private string messageField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<long> code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://transport.webservices.cts.ast")]
    public partial class ADCambioContraseniaRes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ServiceError serviceErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public ServiceError serviceError {
            get {
                return this.serviceErrorField;
            }
            set {
                this.serviceErrorField = value;
                this.RaisePropertyChanged("serviceError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://transport.webservices.cts.ast")]
    public partial class ADCambioContraseniaFil : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string i_u_login_adminsegField;
        
        private string i_c_clave_adminsegField;
        
        private string i_rol_adminsegField;
        
        private string i_oficina_adminsegField;
        
        private string i_servidor_adminsegField;
        
        private string i_c_claveField;
        
        private string i_u_loginField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string i_u_login_adminseg {
            get {
                return this.i_u_login_adminsegField;
            }
            set {
                this.i_u_login_adminsegField = value;
                this.RaisePropertyChanged("i_u_login_adminseg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string i_c_clave_adminseg {
            get {
                return this.i_c_clave_adminsegField;
            }
            set {
                this.i_c_clave_adminsegField = value;
                this.RaisePropertyChanged("i_c_clave_adminseg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string i_rol_adminseg {
            get {
                return this.i_rol_adminsegField;
            }
            set {
                this.i_rol_adminsegField = value;
                this.RaisePropertyChanged("i_rol_adminseg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string i_oficina_adminseg {
            get {
                return this.i_oficina_adminsegField;
            }
            set {
                this.i_oficina_adminsegField = value;
                this.RaisePropertyChanged("i_oficina_adminseg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string i_servidor_adminseg {
            get {
                return this.i_servidor_adminsegField;
            }
            set {
                this.i_servidor_adminsegField = value;
                this.RaisePropertyChanged("i_servidor_adminseg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string i_c_clave {
            get {
                return this.i_c_claveField;
            }
            set {
                this.i_c_claveField = value;
                this.RaisePropertyChanged("i_c_clave");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public string i_u_login {
            get {
                return this.i_u_loginField;
            }
            set {
                this.i_u_loginField = value;
                this.RaisePropertyChanged("i_u_login");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="execute", WrapperNamespace="http://webservices.cts.ast", IsWrapped=true)]
    public partial class executeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.cts.ast", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public NotifClavesWeb.ADCambioContrasenia.RequestConnection requestConnection;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.cts.ast", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public NotifClavesWeb.ADCambioContrasenia.ADCambioContraseniaFil CambioContraseniaFil;
        
        public executeRequest() {
        }
        
        public executeRequest(NotifClavesWeb.ADCambioContrasenia.RequestConnection requestConnection, NotifClavesWeb.ADCambioContrasenia.ADCambioContraseniaFil CambioContraseniaFil) {
            this.requestConnection = requestConnection;
            this.CambioContraseniaFil = CambioContraseniaFil;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="executeResponse", WrapperNamespace="http://webservices.cts.ast", IsWrapped=true)]
    public partial class executeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.cts.ast", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public NotifClavesWeb.ADCambioContrasenia.ADCambioContraseniaRes executeReturn;
        
        public executeResponse() {
        }
        
        public executeResponse(NotifClavesWeb.ADCambioContrasenia.ADCambioContraseniaRes executeReturn) {
            this.executeReturn = executeReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ADCambioContraseniaChannel : NotifClavesWeb.ADCambioContrasenia.ADCambioContrasenia, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ADCambioContraseniaClient : System.ServiceModel.ClientBase<NotifClavesWeb.ADCambioContrasenia.ADCambioContrasenia>, NotifClavesWeb.ADCambioContrasenia.ADCambioContrasenia {
        
        public ADCambioContraseniaClient() {
        }
        
        public ADCambioContraseniaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ADCambioContraseniaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ADCambioContraseniaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ADCambioContraseniaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NotifClavesWeb.ADCambioContrasenia.executeResponse NotifClavesWeb.ADCambioContrasenia.ADCambioContrasenia.execute(NotifClavesWeb.ADCambioContrasenia.executeRequest request) {
            return base.Channel.execute(request);
        }
        
        public NotifClavesWeb.ADCambioContrasenia.ADCambioContraseniaRes execute(NotifClavesWeb.ADCambioContrasenia.RequestConnection requestConnection, NotifClavesWeb.ADCambioContrasenia.ADCambioContraseniaFil CambioContraseniaFil) {
            NotifClavesWeb.ADCambioContrasenia.executeRequest inValue = new NotifClavesWeb.ADCambioContrasenia.executeRequest();
            inValue.requestConnection = requestConnection;
            inValue.CambioContraseniaFil = CambioContraseniaFil;
            NotifClavesWeb.ADCambioContrasenia.executeResponse retVal = ((NotifClavesWeb.ADCambioContrasenia.ADCambioContrasenia)(this)).execute(inValue);
            return retVal.executeReturn;
        }
    }
}
