/*
insert license info here
*/
using System;
using System.Collections;

namespace Common.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class AuditLoginEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

        private int m_aud_login_id;
		private DateTime m_fecha;
        private int? m_id_usuario;
        private string m_username; 
		private string m_fullname; 
		private string m_terminal;
        private EventoLoginEntity m_evento;
        #endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public AuditLoginEntity()
		{
            m_aud_login_id = 0;
            m_terminal = System.Environment.MachineName;
		}
		#endregion // End of Default ( Empty ) Class Constuctor


		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
            get { return m_aud_login_id; }
			set
			{
                m_isChanged |= (m_aud_login_id != value);
                m_aud_login_id = value;
			}

		}

		/// <summary>
		/// nombre de usuario. En un principio sería el usuario del dominio
		/// </summary>
		public string Username
		{
			get { return m_username; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for Username", value, "null");
				
				if(  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for Username", value, value.ToString());
				
				m_isChanged |= (m_username != value); m_username = value;
			}
		}
			
		/// <summary>
		/// nombre completo del usuario
		/// </summary>
		public string Fullname
		{
			get { return m_fullname; }

			set	
			{	
				
				m_fullname = value;
			}
		}
			
		public DateTime Fecha
		{
            get { return m_fecha; }
			set
			{
                m_isChanged |= (m_fecha != value);
                m_fecha = value;
			}

		}

        public string Terminal
		{
            get { return m_terminal; }

			set	
			{	
				if( value == null )
                    throw new ArgumentOutOfRangeException("Null value not allowed for Terminal", value, "null");
				
				if(  value.Length > 100)
                    throw new ArgumentOutOfRangeException("Invalid value for Terminal", value, value.ToString());

                m_isChanged |= (m_terminal != value); m_terminal = value;
			}
		}

        public int? IdUsuario
        {
            get
            {
                return m_id_usuario;
            }
            set
            {
                m_id_usuario = value;
            }

        }

        public EventoLoginEntity Evento
        {
            get { return m_evento; }
            set { m_evento = value; }
        }
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}

        #endregion
        public override string Key
        {
            get
            {
                return m_aud_login_id.ToString();
            }
            set
            {
                m_aud_login_id = Convert.ToInt32(value);
            }
        }
	}
}
