//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TestWSInterfaceClaves.ConectoresWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UsuarioServiceSoap", Namespace="http://tempuri.org/")]
    public partial class UsuarioService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AltaGrupoSeguimientoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AltaGrupoSolicitudesOperationCompleted;
        
        private System.Threading.SendOrPostCallback AltaPerfilOperationCompleted;
        
        private System.Threading.SendOrPostCallback AltaUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback BajaGrupoSeguimientoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BajaGrupoSolicitudesOperationCompleted;
        
        private System.Threading.SendOrPostCallback BajaPerfilOperationCompleted;
        
        private System.Threading.SendOrPostCallback BajaUsuarioOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UsuarioService() {
            this.Url = global::TestWSInterfaceClaves.Properties.Settings.Default.TestWSInterfaceClaves_ConectoresWS_UsuarioService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AltaGrupoSeguimientoCompletedEventHandler AltaGrupoSeguimientoCompleted;
        
        /// <remarks/>
        public event AltaGrupoSolicitudesCompletedEventHandler AltaGrupoSolicitudesCompleted;
        
        /// <remarks/>
        public event AltaPerfilCompletedEventHandler AltaPerfilCompleted;
        
        /// <remarks/>
        public event AltaUsuarioCompletedEventHandler AltaUsuarioCompleted;
        
        /// <remarks/>
        public event BajaGrupoSeguimientoCompletedEventHandler BajaGrupoSeguimientoCompleted;
        
        /// <remarks/>
        public event BajaGrupoSolicitudesCompletedEventHandler BajaGrupoSolicitudesCompleted;
        
        /// <remarks/>
        public event BajaPerfilCompletedEventHandler BajaPerfilCompleted;
        
        /// <remarks/>
        public event BajaUsuarioCompletedEventHandler BajaUsuarioCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AltaGrupoSeguimiento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Resultado AltaGrupoSeguimiento(GrupoSeguimientoRequest request) {
            object[] results = this.Invoke("AltaGrupoSeguimiento", new object[] {
                        request});
            return ((Resultado)(results[0]));
        }
        
        /// <remarks/>
        public void AltaGrupoSeguimientoAsync(GrupoSeguimientoRequest request) {
            this.AltaGrupoSeguimientoAsync(request, null);
        }
        
        /// <remarks/>
        public void AltaGrupoSeguimientoAsync(GrupoSeguimientoRequest request, object userState) {
            if ((this.AltaGrupoSeguimientoOperationCompleted == null)) {
                this.AltaGrupoSeguimientoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAltaGrupoSeguimientoOperationCompleted);
            }
            this.InvokeAsync("AltaGrupoSeguimiento", new object[] {
                        request}, this.AltaGrupoSeguimientoOperationCompleted, userState);
        }
        
        private void OnAltaGrupoSeguimientoOperationCompleted(object arg) {
            if ((this.AltaGrupoSeguimientoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AltaGrupoSeguimientoCompleted(this, new AltaGrupoSeguimientoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AltaGrupoSolicitudes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Resultado AltaGrupoSolicitudes(GrupoSolicitudesRequest request) {
            object[] results = this.Invoke("AltaGrupoSolicitudes", new object[] {
                        request});
            return ((Resultado)(results[0]));
        }
        
        /// <remarks/>
        public void AltaGrupoSolicitudesAsync(GrupoSolicitudesRequest request) {
            this.AltaGrupoSolicitudesAsync(request, null);
        }
        
        /// <remarks/>
        public void AltaGrupoSolicitudesAsync(GrupoSolicitudesRequest request, object userState) {
            if ((this.AltaGrupoSolicitudesOperationCompleted == null)) {
                this.AltaGrupoSolicitudesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAltaGrupoSolicitudesOperationCompleted);
            }
            this.InvokeAsync("AltaGrupoSolicitudes", new object[] {
                        request}, this.AltaGrupoSolicitudesOperationCompleted, userState);
        }
        
        private void OnAltaGrupoSolicitudesOperationCompleted(object arg) {
            if ((this.AltaGrupoSolicitudesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AltaGrupoSolicitudesCompleted(this, new AltaGrupoSolicitudesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AltaPerfil", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Resultado AltaPerfil(PerfilRequest request) {
            object[] results = this.Invoke("AltaPerfil", new object[] {
                        request});
            return ((Resultado)(results[0]));
        }
        
        /// <remarks/>
        public void AltaPerfilAsync(PerfilRequest request) {
            this.AltaPerfilAsync(request, null);
        }
        
        /// <remarks/>
        public void AltaPerfilAsync(PerfilRequest request, object userState) {
            if ((this.AltaPerfilOperationCompleted == null)) {
                this.AltaPerfilOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAltaPerfilOperationCompleted);
            }
            this.InvokeAsync("AltaPerfil", new object[] {
                        request}, this.AltaPerfilOperationCompleted, userState);
        }
        
        private void OnAltaPerfilOperationCompleted(object arg) {
            if ((this.AltaPerfilCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AltaPerfilCompleted(this, new AltaPerfilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AltaUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Resultado AltaUsuario(AltaUsuarioRequest request) {
            object[] results = this.Invoke("AltaUsuario", new object[] {
                        request});
            return ((Resultado)(results[0]));
        }
        
        /// <remarks/>
        public void AltaUsuarioAsync(AltaUsuarioRequest request) {
            this.AltaUsuarioAsync(request, null);
        }
        
        /// <remarks/>
        public void AltaUsuarioAsync(AltaUsuarioRequest request, object userState) {
            if ((this.AltaUsuarioOperationCompleted == null)) {
                this.AltaUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAltaUsuarioOperationCompleted);
            }
            this.InvokeAsync("AltaUsuario", new object[] {
                        request}, this.AltaUsuarioOperationCompleted, userState);
        }
        
        private void OnAltaUsuarioOperationCompleted(object arg) {
            if ((this.AltaUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AltaUsuarioCompleted(this, new AltaUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BajaGrupoSeguimiento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Resultado BajaGrupoSeguimiento(GrupoSeguimientoRequest request) {
            object[] results = this.Invoke("BajaGrupoSeguimiento", new object[] {
                        request});
            return ((Resultado)(results[0]));
        }
        
        /// <remarks/>
        public void BajaGrupoSeguimientoAsync(GrupoSeguimientoRequest request) {
            this.BajaGrupoSeguimientoAsync(request, null);
        }
        
        /// <remarks/>
        public void BajaGrupoSeguimientoAsync(GrupoSeguimientoRequest request, object userState) {
            if ((this.BajaGrupoSeguimientoOperationCompleted == null)) {
                this.BajaGrupoSeguimientoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBajaGrupoSeguimientoOperationCompleted);
            }
            this.InvokeAsync("BajaGrupoSeguimiento", new object[] {
                        request}, this.BajaGrupoSeguimientoOperationCompleted, userState);
        }
        
        private void OnBajaGrupoSeguimientoOperationCompleted(object arg) {
            if ((this.BajaGrupoSeguimientoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BajaGrupoSeguimientoCompleted(this, new BajaGrupoSeguimientoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BajaGrupoSolicitudes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Resultado BajaGrupoSolicitudes(GrupoSolicitudesRequest request) {
            object[] results = this.Invoke("BajaGrupoSolicitudes", new object[] {
                        request});
            return ((Resultado)(results[0]));
        }
        
        /// <remarks/>
        public void BajaGrupoSolicitudesAsync(GrupoSolicitudesRequest request) {
            this.BajaGrupoSolicitudesAsync(request, null);
        }
        
        /// <remarks/>
        public void BajaGrupoSolicitudesAsync(GrupoSolicitudesRequest request, object userState) {
            if ((this.BajaGrupoSolicitudesOperationCompleted == null)) {
                this.BajaGrupoSolicitudesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBajaGrupoSolicitudesOperationCompleted);
            }
            this.InvokeAsync("BajaGrupoSolicitudes", new object[] {
                        request}, this.BajaGrupoSolicitudesOperationCompleted, userState);
        }
        
        private void OnBajaGrupoSolicitudesOperationCompleted(object arg) {
            if ((this.BajaGrupoSolicitudesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BajaGrupoSolicitudesCompleted(this, new BajaGrupoSolicitudesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BajaPerfil", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Resultado BajaPerfil(PerfilRequest request) {
            object[] results = this.Invoke("BajaPerfil", new object[] {
                        request});
            return ((Resultado)(results[0]));
        }
        
        /// <remarks/>
        public void BajaPerfilAsync(PerfilRequest request) {
            this.BajaPerfilAsync(request, null);
        }
        
        /// <remarks/>
        public void BajaPerfilAsync(PerfilRequest request, object userState) {
            if ((this.BajaPerfilOperationCompleted == null)) {
                this.BajaPerfilOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBajaPerfilOperationCompleted);
            }
            this.InvokeAsync("BajaPerfil", new object[] {
                        request}, this.BajaPerfilOperationCompleted, userState);
        }
        
        private void OnBajaPerfilOperationCompleted(object arg) {
            if ((this.BajaPerfilCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BajaPerfilCompleted(this, new BajaPerfilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BajaUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Resultado BajaUsuario(BajaUsuarioRequest request) {
            object[] results = this.Invoke("BajaUsuario", new object[] {
                        request});
            return ((Resultado)(results[0]));
        }
        
        /// <remarks/>
        public void BajaUsuarioAsync(BajaUsuarioRequest request) {
            this.BajaUsuarioAsync(request, null);
        }
        
        /// <remarks/>
        public void BajaUsuarioAsync(BajaUsuarioRequest request, object userState) {
            if ((this.BajaUsuarioOperationCompleted == null)) {
                this.BajaUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBajaUsuarioOperationCompleted);
            }
            this.InvokeAsync("BajaUsuario", new object[] {
                        request}, this.BajaUsuarioOperationCompleted, userState);
        }
        
        private void OnBajaUsuarioOperationCompleted(object arg) {
            if ((this.BajaUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BajaUsuarioCompleted(this, new BajaUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GrupoSeguimientoRequest {
        
        private string stringAutenticacionField;
        
        private string dominioField;
        
        private string usuarioField;
        
        private string idGruposField;
        
        /// <remarks/>
        public string StringAutenticacion {
            get {
                return this.stringAutenticacionField;
            }
            set {
                this.stringAutenticacionField = value;
            }
        }
        
        /// <remarks/>
        public string Dominio {
            get {
                return this.dominioField;
            }
            set {
                this.dominioField = value;
            }
        }
        
        /// <remarks/>
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public string IdGrupos {
            get {
                return this.idGruposField;
            }
            set {
                this.idGruposField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BajaUsuarioRequest {
        
        private string stringAutenticacionField;
        
        private string dominioField;
        
        private string usuarioField;
        
        /// <remarks/>
        public string StringAutenticacion {
            get {
                return this.stringAutenticacionField;
            }
            set {
                this.stringAutenticacionField = value;
            }
        }
        
        /// <remarks/>
        public string Dominio {
            get {
                return this.dominioField;
            }
            set {
                this.dominioField = value;
            }
        }
        
        /// <remarks/>
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AltaUsuarioRequest {
        
        private string stringAutenticacionField;
        
        private string dominioField;
        
        private string usuarioField;
        
        private string nombreCompletoField;
        
        private string emailField;
        
        private string legajoField;
        
        /// <remarks/>
        public string StringAutenticacion {
            get {
                return this.stringAutenticacionField;
            }
            set {
                this.stringAutenticacionField = value;
            }
        }
        
        /// <remarks/>
        public string Dominio {
            get {
                return this.dominioField;
            }
            set {
                this.dominioField = value;
            }
        }
        
        /// <remarks/>
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public string NombreCompleto {
            get {
                return this.nombreCompletoField;
            }
            set {
                this.nombreCompletoField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Legajo {
            get {
                return this.legajoField;
            }
            set {
                this.legajoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PerfilRequest {
        
        private string stringAutenticacionField;
        
        private string dominioField;
        
        private string usuarioField;
        
        private string idPerfilesField;
        
        /// <remarks/>
        public string StringAutenticacion {
            get {
                return this.stringAutenticacionField;
            }
            set {
                this.stringAutenticacionField = value;
            }
        }
        
        /// <remarks/>
        public string Dominio {
            get {
                return this.dominioField;
            }
            set {
                this.dominioField = value;
            }
        }
        
        /// <remarks/>
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public string IdPerfiles {
            get {
                return this.idPerfilesField;
            }
            set {
                this.idPerfilesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GrupoSolicitudesRequest {
        
        private string stringAutenticacionField;
        
        private string dominioField;
        
        private string usuarioField;
        
        private string idGruposField;
        
        /// <remarks/>
        public string StringAutenticacion {
            get {
                return this.stringAutenticacionField;
            }
            set {
                this.stringAutenticacionField = value;
            }
        }
        
        /// <remarks/>
        public string Dominio {
            get {
                return this.dominioField;
            }
            set {
                this.dominioField = value;
            }
        }
        
        /// <remarks/>
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public string IdGrupos {
            get {
                return this.idGruposField;
            }
            set {
                this.idGruposField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Resultado {
        
        private bool exitoField;
        
        private string mensajeField;
        
        /// <remarks/>
        public bool Exito {
            get {
                return this.exitoField;
            }
            set {
                this.exitoField = value;
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AltaGrupoSeguimientoCompletedEventHandler(object sender, AltaGrupoSeguimientoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AltaGrupoSeguimientoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AltaGrupoSeguimientoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Resultado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Resultado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AltaGrupoSolicitudesCompletedEventHandler(object sender, AltaGrupoSolicitudesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AltaGrupoSolicitudesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AltaGrupoSolicitudesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Resultado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Resultado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AltaPerfilCompletedEventHandler(object sender, AltaPerfilCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AltaPerfilCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AltaPerfilCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Resultado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Resultado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AltaUsuarioCompletedEventHandler(object sender, AltaUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AltaUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AltaUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Resultado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Resultado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void BajaGrupoSeguimientoCompletedEventHandler(object sender, BajaGrupoSeguimientoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BajaGrupoSeguimientoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BajaGrupoSeguimientoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Resultado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Resultado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void BajaGrupoSolicitudesCompletedEventHandler(object sender, BajaGrupoSolicitudesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BajaGrupoSolicitudesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BajaGrupoSolicitudesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Resultado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Resultado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void BajaPerfilCompletedEventHandler(object sender, BajaPerfilCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BajaPerfilCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BajaPerfilCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Resultado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Resultado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void BajaUsuarioCompletedEventHandler(object sender, BajaUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BajaUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BajaUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Resultado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Resultado)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591