/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class ApplicationUserEntity : UserEntity
	{

		#region Private Members
		private bool m_isChanged;

		private ApplicationEntity m_app_id;
        private string m_field1_value;
        private string m_field2_value;
        private string m_field3_value;
        #endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public ApplicationUserEntity()
		{
			base.Id = 0; 
			m_app_id = new ApplicationEntity(); 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		/*public ApplicationUserEntity(
			Users user_id, 
			Applications app_id)
			: this()
		{
			m_user_id = user_id;
			m_app_id = app_id;
		}*/
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public ApplicationEntity Application
		{
			get { return m_app_id; }
			set
			{
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for AppId", value, "null");

				m_isChanged |= ( m_app_id != value ); 
				m_app_id = value;
			}

		}
        public string Field1Value
        {
            get { return m_field1_value; }

            set
            {
                if (value != null && value.Length > 50)
                    throw new ArgumentOutOfRangeException("Invalid value for Field1Value", value, value.ToString());

                m_isChanged |= (m_field1_value != value); m_field1_value = value;
            }
        }
        public string Field2Value
        {
            get { return m_field2_value; }

            set
            {
                if (value != null && value.Length > 50)
                    throw new ArgumentOutOfRangeException("Invalid value for Field2Value", value, value.ToString());

                m_isChanged |= (m_field2_value != value); m_field2_value = value;
            }
        }
        public string Field3Value
        {
            get { return m_field3_value; }

            set
            {
                if (value != null && value.Length > 50)
                    throw new ArgumentOutOfRangeException("Invalid value for Field3Value", value, value.ToString());

                m_isChanged |= (m_field3_value != value); m_field3_value = value;
            }
        }
        public string ApplicationName
        {
            get { return this.m_app_id.Name; }
        }
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
	}
}
