/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
    public sealed class ApplicationEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_app_id; 
		private IList m_ApplicationsUsersList; 
		private string m_app_name; 
		private string m_app_desc; 
		private string m_app_field1_desc; 
		private string m_app_field2_desc; 
		private string m_app_field3_desc;
        private bool m_active = true;
        private bool m_desactiva_pwd_cierre = false;
        #endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public ApplicationEntity()
		{
			m_app_id = 0; 
			m_ApplicationsUsersList = new ArrayList(); 
			m_app_name = String.Empty; 
			m_app_desc = String.Empty; 
			m_app_field1_desc = String.Empty; 
			m_app_field2_desc = String.Empty; 
			m_app_field3_desc = String.Empty; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public ApplicationEntity(
			string app_name)
			: this()
		{
			m_app_name = app_name;
			m_app_desc = String.Empty;
			m_app_field1_desc = String.Empty;
			m_app_field2_desc = String.Empty;
			m_app_field3_desc = String.Empty;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_app_id; }
			set
			{
				m_isChanged |= ( m_app_id != value ); 
				m_app_id = value;
			}

		}
			
		public IList ApplicationsUsersList
		{
			get
			{
				return m_ApplicationsUsersList;
			}
			set
			{
				m_ApplicationsUsersList = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Name
		{
			get { return m_app_name; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for Name", value, "null");
				
				if(  value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for Name", value, value.ToString());
				
				m_isChanged |= (m_app_name != value); m_app_name = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>
		public string Desc
		{
			get { return m_app_desc; }

			set	
			{	
				if(  value != null &&  value.Length > 200)
					throw new ArgumentOutOfRangeException("Invalid value for Desc", value, value.ToString());
				
				m_isChanged |= (m_app_desc != value); m_app_desc = value;
			}
		}
			
		/// <summary>
		/// Descripción de campo 1 de datos extra
		/// </summary>
		public string Field1Desc
		{
			get { return m_app_field1_desc; }

			set	
			{	
				if(  value != null &&  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for Field1Desc", value, value.ToString());
				
				m_isChanged |= (m_app_field1_desc != value); m_app_field1_desc = value;
			}
		}
			
			
		/// <summary>
		/// 
		/// </summary>
		public string Field2Desc
		{
			get { return m_app_field2_desc; }

			set	
			{	
				if(  value != null &&  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for Field2Desc", value, value.ToString());
				
				m_isChanged |= (m_app_field2_desc != value); m_app_field2_desc = value;
			}
		}
			
			
		/// <summary>
		/// 
		/// </summary>
		public string Field3Desc
		{
			get { return m_app_field3_desc; }

			set	
			{	
				if(  value != null &&  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for Field3Desc", value, value.ToString());
				
				m_isChanged |= (m_app_field3_desc != value); m_app_field3_desc = value;
			}
		}
			
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
        public bool Active
        {
            get { return m_active; }
            set
            {
                m_isChanged |= (m_active != value);
                m_active = value;
            }
        }
        public bool Desactiva_PWD_Cierre
        {
            get { return m_desactiva_pwd_cierre; }
            set
            {
                m_isChanged |= (m_desactiva_pwd_cierre != value);
                m_desactiva_pwd_cierre = value;
            }
        }
		#endregion 
        public override string Key
        {
            get
            {
                return m_app_id.ToString();
            }
            set
            {
                m_app_id = Convert.ToInt32(value);
            }
        }
        public override string ToString()
        {
            return this.m_app_name;
        }
    }
}
