/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
    /// <summary>
    ///	Generated by MyGeneration using the NHibernate Object Mapping template
    /// </summary>
    [Serializable]
    public sealed class AS400UserEntity : UserEntity
    {

        #region Private Members
        private bool m_isChanged;
        public string m_Server_Name;

        private AS400Entity m_as_id;
        #endregion

        #region Default ( Empty ) Class Constuctor
        /// <summary>
        /// default constructor
        /// </summary>
        public AS400UserEntity()
        {
            m_as_id = new AS400Entity();
        }
        #endregion // End of Default ( Empty ) Class Constuctor

        #region Required Fields Only Constructor
        /// <summary>
        /// required (not null) fields only constructor
        /// </summary>
        public AS400UserEntity(
            AS400Entity as_id)
            : this()
        {
            m_as_id = as_id;
        }
        #endregion // End Required Fields Only Constructor

        #region Public Properties

        /// <summary>
        /// 
        /// </summary>
        public AS400Entity AS400
        {
            get { return m_as_id; }
            set
            {
                if (value == null)
                    throw new ArgumentOutOfRangeException("Null value not allowed for AS400", value, "null");

                m_isChanged |= (m_as_id != value);
                m_as_id = value;
            }

        }

        public string Server_Name
        {
            get
            {
                if (m_as_id == null)
                {
                    return "";
                }
                else
                {
                    return m_as_id.ServerName;
                }
            }
            set { m_Server_Name = value; }
        }


        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public bool IsChanged
        {
            get { return m_isChanged; }
        }

        #endregion
    }
}
