/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
    public sealed class AS400Entity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_as_id; 
		private IList m_AS400UsersList; 
		private string m_as_server_name; 
		private string m_as_desc; 
		private string m_as_ip;
        private bool m_active = true;
        #endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public AS400Entity()
		{
			m_as_id = 0; 
			m_AS400UsersList = new ArrayList(); 
			m_as_server_name = String.Empty; 
			m_as_desc = String.Empty; 
			m_as_ip = String.Empty; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public AS400Entity(
			string as_server_name)
			: this()
		{
			m_as_server_name = as_server_name;
			m_as_desc = String.Empty;
			m_as_ip = String.Empty;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_as_id; }
			set
			{
				m_isChanged |= ( m_as_id != value ); 
				m_as_id = value;
			}

		}
			
		public IList AS400UsersList
		{
			get
			{
				return m_AS400UsersList;
			}
			set
			{
				m_AS400UsersList = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string ServerName
		{
			get { return m_as_server_name; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for ServerName", value, "null");
				
				if(  value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for ServerName", value, value.ToString());
				
				m_isChanged |= (m_as_server_name != value); m_as_server_name = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>
		public string Desc
		{
			get { return m_as_desc; }

			set	
			{	
				if(  value != null &&  value.Length > 200)
					throw new ArgumentOutOfRangeException("Invalid value for Desc", value, value.ToString());
				
				m_isChanged |= (m_as_desc != value); m_as_desc = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>
		public string Ip
		{
			get { return m_as_ip; }

			set	
			{	
				if(  value != null &&  value.Length > 15)
					throw new ArgumentOutOfRangeException("Invalid value for Ip", value, value.ToString());
				
				m_isChanged |= (m_as_ip != value); m_as_ip = value;
			}
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
        public bool Active
        {
            get { return m_active; }
            set
            {
                m_isChanged |= (m_active != value);
                m_active = value;
            }

        }
		
		#endregion 
	
        public override string Key
        {
            get
            {
                return this.m_as_id.ToString();
            }
            set
            {
                this.m_as_id = Convert.ToInt32(value);
            }
        }
        
        public override string ToString()
        {
            return m_as_server_name;
        }
    }
}
