/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class ATMUserEntity : UserEntity
	{

		#region Private Members
		private bool m_isChanged;

        private string m_ATM_Name;
        private string m_componente;
        #endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public ATMUserEntity()
		{
			base.Id = 0; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		/*public ATMUserEntity(
			Users user_id, 
			Applications app_id)
			: this()
		{
			m_user_id = user_id;
			m_app_id = app_id;
		}*/
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
        public string ATMName
        {
            get { return m_ATM_Name; }

            set
            {
                if (value != null && value.Length > 150)
                    throw new ArgumentOutOfRangeException("ATMName", value, "Invalid value for ATMName");

                m_isChanged |= (m_ATM_Name != value); m_ATM_Name = value;
            }
        }
        public string Componente
        {
            get { return m_componente; }

            set
            {
                if (value != null && value.Length > 50)
                    throw new ArgumentOutOfRangeException("Componente", value, "Invalid value for Componente");

                m_isChanged |= (m_componente != value); m_componente = value;
            }
        }
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
	}
}
