/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class AuditPermisosEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

        private int m_audit_permisos_id;
        private string m_recurso; 
		private DateTime m_fecha;
        private int m_id_usuario_abm;
		private string m_terminal_abm;
        private string m_username_abm; 
		private string m_fullname_abm;
        private int m_id_rol;
        private string m_rol;
        private int m_id_usuario;
        private string m_username; 
		private string m_fullname; 
        private string m_accion;
        private bool m_accion_satisfactoria;
        #endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public AuditPermisosEntity()
		{
            m_audit_permisos_id = 0; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
        public AuditPermisosEntity(PhxUserEntity Responsable, PhxUserEntity Usuario, bool Otorga, PhxRoleEntity Rol)
        {
            this.Recurso = "Phalanx";
            //this.Fecha = DateTime.Now;
            this.IdUsuario = Usuario.Id;
            this.Username = Usuario.Username;
            this.Fullname = Usuario.Fullname;
            this.IdUsuarioABM = Responsable.Id;
            this.UsernameABM = Responsable.Username;
            this.FullnameABM = Responsable.Fullname;
            this.TerminalABM = System.Environment.MachineName;
            this.AccionSatisfactoria = true;
            this.IdRol = Rol.Id;
            this.Rol = Rol.Name;
            if (Otorga)
            {
                this.Accion = "Otorgar";
            }
            else
            {
                this.Accion = "Revocar";
            }

        }


		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
            get { return m_audit_permisos_id; }
			set
			{
                m_isChanged |= (m_audit_permisos_id != value);
                m_audit_permisos_id = value;
			}

		}

        public string Recurso
		{
            get { return m_recurso; }

			set	
			{	
				if( value == null )
                    throw new ArgumentOutOfRangeException("Null value not allowed for Recurso", value, "null");
				
				if(  value.Length > 50)
                    throw new ArgumentOutOfRangeException("Invalid value for Recurso", value, value.ToString());

                m_isChanged |= (m_recurso != value); m_recurso = value;
			}
		}
			
		public DateTime Fecha
		{
            get { return m_fecha; }
			set
			{
                m_isChanged |= (m_fecha != value);
                m_fecha = value;
			}

		}

        public string Accion
		{
            get { return m_accion; }

			set	
			{	
				if( value == null )
                    throw new ArgumentOutOfRangeException("Null value not allowed for Accion", value, "null");
				
				if(  value.Length > 50)
                    throw new ArgumentOutOfRangeException("Invalid value for Accion", value, value.ToString());

                m_isChanged |= (m_accion != value); m_accion = value;
			}
		}
        public int IdUsuarioABM
		{
            get { return m_id_usuario_abm; }
			set
			{
                m_isChanged |= (m_id_usuario_abm != value);
                m_id_usuario_abm = value;
			}

		}
 		public string UsernameABM
		{
			get { return m_username_abm; }

			set	
			{	
				if( value == null )
                    throw new ArgumentOutOfRangeException("Null value not allowed for UsernameABM", value, "null");
				if(  value.Length > 50)
                    throw new ArgumentOutOfRangeException("Invalid value for UsernameABM", value, value.ToString());

                m_isChanged |= (m_username_abm != value); m_username_abm = value;
			}
		}
		public string FullnameABM
		{
			get { return m_fullname_abm; }

			set	
			{	
				if( value == null )
                    throw new ArgumentOutOfRangeException("Null value not allowed for FullnameABM", value, "null");
				
				if(  value.Length > 100)
                    throw new ArgumentOutOfRangeException("Invalid value for FullnameABM", value, value.ToString());

                m_isChanged |= (m_fullname_abm != value); m_fullname_abm = value;
			}
		}
        public string TerminalABM
		{
            get { return m_terminal_abm; }

			set	
			{	
				if( value == null )
                    throw new ArgumentOutOfRangeException("Null value not allowed for TerminalABM", value, "null");
				
				if(  value.Length > 100)
                    throw new ArgumentOutOfRangeException("Invalid value for TerminalABM", value, value.ToString());

                m_isChanged |= (m_terminal_abm != value); m_terminal_abm = value;
			}
		}
        public int IdUsuario
		{
            get { return m_id_usuario; }
			set
			{
                m_isChanged |= (m_id_usuario != value);
                m_id_usuario = value;
			}

		}
		/// <summary>
		/// nombre de usuario. En un principio sería el usuario del dominio
		/// </summary>
		public string Username
		{
			get { return m_username; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for Username", value, "null");
				
				if(  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for Username", value, value.ToString());
				
				m_isChanged |= (m_username != value); m_username = value;
			}
		}
			
		/// <summary>
		/// nombre completo del usuario
		/// </summary>
		public string Fullname
		{
			get { return m_fullname; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for Fullname", value, "null");
				
				if(  value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for Fullname", value, value.ToString());
				
				m_isChanged |= (m_fullname != value); m_fullname = value;
			}
		}
        public int IdRol
		{
            get { return m_id_rol; }
			set
			{
                m_isChanged |= (m_id_rol != value);
                m_id_rol = value;
			}

		}
        public string Rol
		{
            get { return m_rol; }

			set	
			{	
				if( value == null )
                    throw new ArgumentOutOfRangeException("Null value not allowed for Rol", value, "null");
				
				if(  value.Length > 200)
                    throw new ArgumentOutOfRangeException("Invalid value for Rol", value, value.ToString());

                m_isChanged |= (m_rol != value); m_rol = value;
			}
		}

        public bool AccionSatisfactoria
		{
            get { return m_accion_satisfactoria; }
			set
			{
                m_isChanged |= (m_accion_satisfactoria != value);
                m_accion_satisfactoria = value;
			}

		}
	
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}

        #endregion
        public override string Key
        {
            get
            {
                return m_audit_permisos_id.ToString();
            }
            set
            {
                m_audit_permisos_id = Convert.ToInt32(value);
            }
        }
	}
}
