/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class AuditPhxRoleEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

        private int m_audit_phx_role_id;
        private string m_recurso; 
		private DateTime m_fecha;
        private int m_id_usuario_abm;
		private string m_terminal_abm;
        private string m_username_abm; 
		private string m_fullname_abm;
        private int m_phx_role_id;
        private string m_rolename;
        private string m_operacion;
        private bool m_accion_satisfactoria;
        #endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public AuditPhxRoleEntity()
		{
            m_audit_phx_role_id = 0; 
            //this.Recurso = "Phalanx";
		}
		#endregion // End of Default ( Empty ) Class Constuctor
        public AuditPhxRoleEntity(PhxUserEntity Responsable, PhxRoleEntity Rol)
        {
            //this.Recurso = "Phalanx";
            this.IdUsuarioABM = Responsable.Id;
            this.UsernameABM = Responsable.Username;
            this.FullnameABM = Responsable.Fullname;
            this.TerminalABM = System.Environment.MachineName;
            this.AccionSatisfactoria = true;
            this.PhxRoleId = Rol.Id;
            this.Rolename = Rol.Name;

        }


		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
            get { return m_audit_phx_role_id; }
			set
			{
                m_isChanged |= (m_audit_phx_role_id != value);
                m_audit_phx_role_id = value;
			}

		}
        /*
        public string Recurso
		{
            get { return m_recurso; }

			set	
			{	
				if( value == null )
                    throw new ArgumentOutOfRangeException("Null value not allowed for Recurso", value, "null");
				
				if(  value.Length > 50)
                    throw new ArgumentOutOfRangeException("Invalid value for Recurso", value, value.ToString());

                m_isChanged |= (m_recurso != value); m_recurso = value;
			}
		}
		*/	
		public DateTime Fecha
		{
            get { return m_fecha; }
			set
			{
                m_isChanged |= (m_fecha != value);
                m_fecha = value;
			}

		}

        public string Operacion
        {
            get { return m_operacion; }

            set
            {
                if (value == null)
                    throw new ArgumentOutOfRangeException("Null value not allowed for Operacion", value, "null");

                if (value.Length > 50)
                    throw new ArgumentOutOfRangeException("Invalid value for Operacion", value, value.ToString());

                m_isChanged |= (m_operacion != value); m_operacion = value;
            }
        }
        public int IdUsuarioABM
		{
            get { return m_id_usuario_abm; }
			set
			{
                m_isChanged |= (m_id_usuario_abm != value);
                m_id_usuario_abm = value;
			}

		}
 		public string UsernameABM
		{
			get { return m_username_abm; }

			set	
			{	
				if( value == null )
                    throw new ArgumentOutOfRangeException("Null value not allowed for UsernameABM", value, "null");
				if(  value.Length > 50)
                    throw new ArgumentOutOfRangeException("Invalid value for UsernameABM", value, value.ToString());

                m_isChanged |= (m_username_abm != value); m_username_abm = value;
			}
		}
		public string FullnameABM
		{
			get { return m_fullname_abm; }

			set	
			{	
				if( value == null )
                    throw new ArgumentOutOfRangeException("Null value not allowed for FullnameABM", value, "null");
				
				if(  value.Length > 100)
                    throw new ArgumentOutOfRangeException("Invalid value for FullnameABM", value, value.ToString());

                m_isChanged |= (m_fullname_abm != value); m_fullname_abm = value;
			}
		}
        public string TerminalABM
		{
            get { return m_terminal_abm; }

			set	
			{	
				if( value == null )
                    throw new ArgumentOutOfRangeException("Null value not allowed for TerminalABM", value, "null");
				
				if(  value.Length > 100)
                    throw new ArgumentOutOfRangeException("Invalid value for TerminalABM", value, value.ToString());

                m_isChanged |= (m_terminal_abm != value); m_terminal_abm = value;
			}
		}
        public int PhxRoleId
		{
            get { return m_phx_role_id; }
			set
			{
                m_isChanged |= (m_phx_role_id != value);
                m_phx_role_id = value;
			}

		}
        public string Rolename
		{
            get { return m_rolename; }

			set	
			{	
				if( value == null )
                    throw new ArgumentOutOfRangeException("Null value not allowed for Rolename", value, "null");
				
				if(  value.Length > 200)
                    throw new ArgumentOutOfRangeException("Invalid value for Rolename", value, value.ToString());

                m_isChanged |= (m_rolename != value); m_rolename = value;
			}
		}

        public bool AccionSatisfactoria
		{
            get { return m_accion_satisfactoria; }
			set
			{
                m_isChanged |= (m_accion_satisfactoria != value);
                m_accion_satisfactoria = value;
			}

		}
	
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}

        #endregion
        public void SetAlta()
        {
            this.Operacion = "Alta";
        }
        public void SetBaja()
        {
            this.Operacion = "Baja";
        }
        public void SetModificacion()
        {
            this.Operacion = "Modificación";
        }
    
        public override string Key
        {
            get
            {
                return m_audit_phx_role_id.ToString();
            }
            set
            {
                m_audit_phx_role_id = Convert.ToInt32(value);
            }
        }
	}
}
