/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class AuditPhxUserEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

        private int m_audit_phx_user_id; 
		private int m_phx_user_id;
		private string m_username; 
		private string m_fullname; 
		private string m_user_domain; 
		private string m_user_email; 
		private Nullable<DateTime> m_creation_date; 
		private Nullable<DateTime> m_delete_date;
        private string m_file_number;
        private string m_relation_type;
        private string m_branch;
        private string m_function;
        private string m_building_adress;
        private string m_building_floor;
        private string m_extension_number;
        private bool m_active;
        private int m_sup_id;
        private string m_sup_name;
        private string m_sup_mail;
        #endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public AuditPhxUserEntity()
		{
            m_audit_phx_user_id = 0;
		}
		#endregion // End of Default ( Empty ) Class Constuctor
        #region Constructor
        public AuditPhxUserEntity(PhxUserEntity PhxUsr)
        {
            this.Active = PhxUsr.Active;
            this.Branch = PhxUsr.Branch;
            this.BuildingAdress = PhxUsr.BuildingAdress;
            this.BuildingFloor = PhxUsr.BuildingFloor;
            this.CreationDate = PhxUsr.CreationDate;
            this.DeleteDate = PhxUsr.DeleteDate;
            this.Domain = PhxUsr.Domain;
            this.Email = PhxUsr.Email;
            this.ExtensionNumber = PhxUsr.ExtensionNumber;
            this.FileNumber = PhxUsr.FileNumber;
            this.Fullname = PhxUsr.Fullname;
            this.Function = PhxUsr.Function;
            this.PhxUserId = PhxUsr.Id;
            this.RelationType = PhxUsr.RelationType;
            if (PhxUsr.PhxUserSuperior != null)
            {
                this.SupId = PhxUsr.PhxUserSuperior.Id;
                this.SupMail = PhxUsr.PhxUserSuperior.Mail;
                this.SupName = PhxUsr.PhxUserSuperior.Name;
            }
            this.Username = PhxUsr.Username;
        }

        #endregion

        #region Public Properties

        /// <summary>
		/// 
		/// </summary>
		public int Id
		{
            get { return m_audit_phx_user_id; }
			set
			{
                m_isChanged |= (m_audit_phx_user_id != value);
                m_audit_phx_user_id = value;
			}

		}

        public int PhxUserId
		{
			get { return m_phx_user_id; }
			set
			{
				m_isChanged |= ( m_phx_user_id != value ); 
				m_phx_user_id = value;
			}

		}
		/// <summary>
		/// nombre de usuario. En un principio sería el usuario del dominio
		/// </summary>
		public string Username
		{
			get { return m_username; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for Username", value, "null");
				
				if(  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for Username", value, value.ToString());
				
				m_isChanged |= (m_username != value); m_username = value;
			}
		}
			
		/// <summary>
		/// nombre completo del usuario
		/// </summary>
		public string Fullname
		{
			get { return m_fullname; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for Fullname", value, "null");
				
				if(  value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for Fullname", value, value.ToString());
				
				m_isChanged |= (m_fullname != value); m_fullname = value;
			}
		}
			
		/// <summary>
		/// Dominio al cual pertenece el usuario. El nombre del dominio será en formato NT Domain
		/// </summary>
        public string Domain
		{
			get { return m_user_domain; }

			set	
			{	
				if(  value != null &&  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for UserDomain", value, value.ToString());
				
				m_isChanged |= (m_user_domain != value); m_user_domain = value;
			}
		}
			
		/// <summary>
		/// Mail del usuario adonde le llegarán las notificaciones
		/// </summary>
		public string Email
		{
			get { return m_user_email; }

			set	
			{	
				if(  value != null &&  value.Length > 150)
					throw new ArgumentOutOfRangeException("Invalid value for UserEmail", value, value.ToString());
				
				m_isChanged |= (m_user_email != value); m_user_email = value;
			}
		}
        /// <summary>
        /// Indica si el usuario está activo para usar el sistema
        /// </summary>
		public bool Active
		{
            get { return m_active; }
			set
			{
                m_isChanged |= (m_active != value);
                m_active = value;
			}

		}

		/// <summary>
		/// 
		/// </summary>
		public Nullable<DateTime> CreationDate
		{
			get { return m_creation_date; }
			set
			{
				m_isChanged |= ( m_creation_date != value ); 
				m_creation_date = value;
			}

		}
			
		/// <summary>
		/// fecha de baja
		/// </summary>
		public Nullable<DateTime> DeleteDate
		{
			get { return m_delete_date; }
			set
			{
				m_isChanged |= ( m_delete_date != value ); 
				m_delete_date = value;
			}

		}

        public string FileNumber
        {
            get { return m_file_number; }

            set
            {
                if (value != null && value.Length > 10)
                    throw new ArgumentOutOfRangeException("Invalid value for FileNumber", value, value.ToString());

                m_isChanged |= (m_file_number != value); m_file_number = value;
            }
        }
        /// <summary>
        /// relacion laboral - I=interno - E=Externo - P=Proveedor
        /// </summary>
        public string RelationType
        {
            get { return m_relation_type; }

            set
            {
                if (value != null && value.Length > 1)
                    throw new ArgumentOutOfRangeException("Invalid value for RelationType", value, value.ToString());

                m_isChanged |= (m_relation_type != value); m_relation_type = value;
            }
        }
        public string Branch
        {
            get { return m_branch; }

            set
            {
                if (value != null && value.Length > 100)
                    throw new ArgumentOutOfRangeException("Invalid value for Branch", value, value.ToString());

                m_isChanged |= (m_branch != value); m_branch = value;
            }
        }
        public string Function
        {
            get { return m_function; }

            set
            {
                if (value != null && value.Length > 50)
                    throw new ArgumentOutOfRangeException("Invalid value for Function", value, value.ToString());

                m_isChanged |= (m_function != value); m_function = value;
            }
        }
        public string BuildingAdress
        {
            get { return m_building_adress; }

            set
            {
                if (value != null && value.Length > 50)
                    throw new ArgumentOutOfRangeException("Invalid value for BuildingAdress", value, value.ToString());

                m_isChanged |= (m_building_adress != value); m_building_adress = value;
            }
        }
        public string BuildingFloor
        {
            get { return m_building_floor; }

            set
            {
                if (value != null && value.Length > 5)
                    throw new ArgumentOutOfRangeException("Invalid value for BuildingFloor", value, value.ToString());

                m_isChanged |= (m_building_floor != value); m_building_floor = value;
            }
        }
        public string ExtensionNumber
        {
            get { return m_extension_number; }

            set
            {
                if (value != null && value.Length > 5)
                    throw new ArgumentOutOfRangeException("Invalid value for ExtensionNumber", value, value.ToString());

                m_isChanged |= (m_extension_number != value); m_extension_number = value;
            }
        }
        public int SupId
        {
            get { return m_sup_id; }
            set
            {
                m_isChanged |= (m_sup_id != value);
                m_sup_id = value;
            }

        }
        public string SupName
        {
            get { return m_sup_name; }

            set
            {

                if (value != null && value.Length > 100)
                    throw new ArgumentOutOfRangeException("Invalid value for Name", value, value.ToString());

                m_isChanged |= (m_sup_name != value); m_sup_name = value;
            }
        }

        public string SupMail
        {
            get { return m_sup_mail; }

            set
            {

                if (value != null && value.Length > 100)
                    throw new ArgumentOutOfRangeException("Invalid value for Mail", value, value.ToString());

                m_isChanged |= (m_sup_mail != value); m_sup_mail = value;
            }
        }

		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}

        #endregion
        public override string Key
        {
            get
            {
                return m_audit_phx_user_id.ToString();
            }
            set
            {
                m_audit_phx_user_id = Convert.ToInt32(value);
            }
        }


    }
}
