/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class AuditUsuariosEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

        private int m_aud_usr_id;
        private string m_recurso; 
        private int m_id_usuario;
        private string m_username; 
		private string m_fullname; 
		private DateTime m_fecha;
        private string m_operacion;
        private int m_id_usuario_abm;
        private string m_username_abm; 
		private string m_fullname_abm; 
		private string m_terminal_abm;
        private bool m_accion_satisfactoria;
        private AuditPhxUserEntity m_audit_phx_user_id_new;
        private AuditPhxUserEntity m_audit_phx_user_id_old;
        #endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public AuditUsuariosEntity()
		{
            m_aud_usr_id = 0; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
        public AuditUsuariosEntity(PhxUserEntity Responsable, PhxUserEntity NewReg, PhxUserEntity OldReg)
        {
            if (NewReg != null)
            {
                this.AuditPhxUserNew = new AuditPhxUserEntity(NewReg);
            }
            if (OldReg != null)
            {
                this.AuditPhxUserOld = new AuditPhxUserEntity(OldReg);
            }
            this.Recurso = "Phalanx";
            //this.Fecha = DateTime.Now;
            if (OldReg == null && NewReg != null)
            {
                this.Operacion = "Alta";
                this.IdUsuario = NewReg.Id;
                this.Username = NewReg.Username;
                this.Fullname = NewReg.Fullname;
            }
            else if (OldReg != null && NewReg == null)
            {
                this.Operacion = "Baja";
                this.IdUsuario = OldReg.Id;
                this.Username = OldReg.Username;
                this.Fullname = OldReg.Fullname;
            }
            else if (OldReg != null && NewReg != null)
            {
                this.Operacion = "Modificación";
                this.IdUsuario = NewReg.Id;
                this.Username = NewReg.Username;
                this.Fullname = NewReg.Fullname;
            }
            this.IdUsuarioABM = Responsable.Id;
            this.UsernameABM = Responsable.Username;
            this.FullnameABM = Responsable.Fullname;
            this.TerminalABM = System.Environment.MachineName;
            this.AccionSatisfactoria = true;

        }


		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
            get { return m_aud_usr_id; }
			set
			{
                m_isChanged |= (m_aud_usr_id != value);
                m_aud_usr_id = value;
			}

		}

        public string Recurso
		{
            get { return m_recurso; }

			set	
			{	
				if( value == null )
                    throw new ArgumentOutOfRangeException("Null value not allowed for Recurso", value, "null");
				
				if(  value.Length > 50)
                    throw new ArgumentOutOfRangeException("Invalid value for Recurso", value, value.ToString());

                m_isChanged |= (m_recurso != value); m_recurso = value;
			}
		}
        public int IdUsuario
		{
            get { return m_id_usuario; }
			set
			{
                m_isChanged |= (m_id_usuario != value);
                m_id_usuario = value;
			}

		}
        public AuditPhxUserEntity AuditPhxUserNew
        {
            get
            {
                return m_audit_phx_user_id_new;
            }
            set
            {
                //m_isChanged |= (m_phx_superior != value);
                m_audit_phx_user_id_new = value;
            }
        }
        public AuditPhxUserEntity AuditPhxUserOld
        {
            get
            {
                return m_audit_phx_user_id_old;
            }
            set
            {
                //m_isChanged |= (m_phx_superior != value);
                m_audit_phx_user_id_old = value;
            }
        }
		/// <summary>
		/// nombre de usuario. En un principio sería el usuario del dominio
		/// </summary>
		public string Username
		{
			get { return m_username; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for Username", value, "null");
				
				if(  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for Username", value, value.ToString());
				
				m_isChanged |= (m_username != value); m_username = value;
			}
		}
			
		/// <summary>
		/// nombre completo del usuario
		/// </summary>
		public string Fullname
		{
			get { return m_fullname; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for Fullname", value, "null");
				
				if(  value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for Fullname", value, value.ToString());
				
				m_isChanged |= (m_fullname != value); m_fullname = value;
			}
		}
			
		public DateTime Fecha
		{
            get { return m_fecha; }
			set
			{
                m_isChanged |= (m_fecha != value);
                m_fecha = value;
			}

		}

        public string Operacion
		{
            get { return m_operacion; }

			set	
			{	
				if( value == null )
                    throw new ArgumentOutOfRangeException("Null value not allowed for Operacion", value, "null");
				
				if(  value.Length > 50)
                    throw new ArgumentOutOfRangeException("Invalid value for Operacion", value, value.ToString());

                m_isChanged |= (m_operacion != value); m_operacion = value;
			}
		}
        public int IdUsuarioABM
		{
            get { return m_id_usuario_abm; }
			set
			{
                m_isChanged |= (m_id_usuario_abm != value);
                m_id_usuario_abm = value;
			}

		}
 		public string UsernameABM
		{
			get { return m_username_abm; }

			set	
			{	
				if( value == null )
                    throw new ArgumentOutOfRangeException("Null value not allowed for UsernameABM", value, "null");
				if(  value.Length > 50)
                    throw new ArgumentOutOfRangeException("Invalid value for UsernameABM", value, value.ToString());

                m_isChanged |= (m_username_abm != value); m_username_abm = value;
			}
		}
		public string FullnameABM
		{
			get { return m_fullname_abm; }

			set	
			{	
				if( value == null )
                    throw new ArgumentOutOfRangeException("Null value not allowed for FullnameABM", value, "null");
				
				if(  value.Length > 100)
                    throw new ArgumentOutOfRangeException("Invalid value for FullnameABM", value, value.ToString());

                m_isChanged |= (m_fullname_abm != value); m_fullname_abm = value;
			}
		}
        public string TerminalABM
		{
            get { return m_terminal_abm; }

			set	
			{	
				if( value == null )
                    throw new ArgumentOutOfRangeException("Null value not allowed for TerminalABM", value, "null");
				
				if(  value.Length > 100)
                    throw new ArgumentOutOfRangeException("Invalid value for TerminalABM", value, value.ToString());

                m_isChanged |= (m_terminal_abm != value); m_terminal_abm = value;
			}
		}

        public bool AccionSatisfactoria
		{
            get { return m_accion_satisfactoria; }
			set
			{
                m_isChanged |= (m_accion_satisfactoria != value);
                m_accion_satisfactoria = value;
			}

		}
	
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}

        #endregion
        public override string Key
        {
            get
            {
                return m_aud_usr_id.ToString();
            }
            set
            {
                m_aud_usr_id = Convert.ToInt32(value);
            }
        }
	}
}
