/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
    public sealed class BuildingEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_bld_id;
        private string m_bld_address; 
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public BuildingEntity()
		{
			m_bld_id = 0; 
			m_bld_address = String.Empty; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public BuildingEntity(
			string as_server_name)
			: this()
		{
			m_bld_address = as_server_name;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_bld_id; }
			set
			{
				m_isChanged |= ( m_bld_id != value ); 
				m_bld_id = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
        public string Address
		{
			get { return m_bld_address; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for Address", value, "null");
				
				if(  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for Address", value, value.ToString());
				
				m_isChanged |= (m_bld_address != value); m_bld_address = value;
			}
		}
			
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
	
        public override string Key
        {
            get
            {
                return this.m_bld_id.ToString();
            }
            set
            {
                this.m_bld_id = Convert.ToInt32(value);
            }
        }
        
        public override string ToString()
        {
            return m_bld_address;
        }
    }
}
