/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class DatabaseUserEntity : UserEntity
	{

		#region Private Members
		private bool m_isChanged;

		private DataBaseEntity m_db_id; 		
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public DatabaseUserEntity():base()
		{
			m_db_id = new DataBaseEntity(); 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public DatabaseUserEntity(
			DataBaseEntity db_id)
			: this()
		{
			m_db_id = db_id;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public DataBaseEntity Db
		{
			get { return m_db_id; }
			set
			{
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for DbId", value, "null");

				m_isChanged |= ( m_db_id != value ); 
				m_db_id = value;
			}

		}

        public string DBName
        {
            get { return this.m_db_id.Name; }
        }
        public string DBType
        {
            get { return this.m_db_id.Type.Name; }
        }
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
	}
}
