/*
insert license info here
*/
using System;
using System.Collections;
using System.Collections.Generic;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
    public sealed class DatabaseTypeEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_db_type_id; 
		private IList<DataBaseEntity> m_DataBasesList; 
		private string m_db_type_code; 
		private string m_db_type_name; 		
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public DatabaseTypeEntity()
		{
			m_db_type_id = 0; 
			m_DataBasesList = new List<DataBaseEntity>(); 
			m_db_type_code = String.Empty; 
			m_db_type_name = String.Empty; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public DatabaseTypeEntity(
			string db_type_code, 
			string db_type_name)
			: this()
		{
			m_db_type_code = db_type_code;
			m_db_type_name = db_type_name;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_db_type_id; }
			set
			{
				m_isChanged |= ( m_db_type_id != value ); 
				m_db_type_id = value;
			}

		}
			
		public IList<DataBaseEntity> DataBasesList
		{
			get
			{
				return m_DataBasesList;
			}
			set
			{
				m_DataBasesList = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Code
		{
			get { return m_db_type_code; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for Code", value, "null");
				
				if(  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for Code", value, value.ToString());
				
				m_isChanged |= (m_db_type_code != value); m_db_type_code = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>
		public string Name
		{
			get { return m_db_type_name; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for Name", value, "null");
				
				if(  value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for Name", value, value.ToString());
				
				m_isChanged |= (m_db_type_name != value); m_db_type_name = value;
			}
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
        public override string Key
        {
            get
            {
                return m_db_type_id.ToString();
            }
            set
            {
                m_db_type_id = Convert.ToInt32(value);
            }
        }
        public override string ToString()
        {
            return m_db_type_name;
        }
    }
}
