/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class DelegationRequestEntity : RequestEntity
	{

		#region Private Members
		private bool m_isChanged;

		//private int m_request_id; 
		//private IList m_DelegationRequestsList; 
		private WinGroupEntity m_win_group_id; 		
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public DelegationRequestEntity() : base()
		{
			//m_request_id = 0; 
			base.Id = 0;
			//m_DelegationRequestsList = new ArrayList(); 
			m_win_group_id = new WinGroupEntity(); 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public DelegationRequestEntity(
			int request_id, 
			WinGroupEntity win_group_id)
			: this()
		{
			//m_request_id = request_id;
			base.Id = request_id;
			m_win_group_id = win_group_id;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties

        /*			
		/// <summary>
		/// 
		/// </summary>
		public int RequestId
		{
			get { return m_request_id; }
			set
			{
				m_isChanged |= ( m_request_id != value ); 
				m_request_id = value;
			}

		}
		*/
		
		/*
		public IList DelegationRequestsList
		{
			get
			{
				return m_DelegationRequestsList;
			}
			set
			{
				m_DelegationRequestsList = value;
			}
		}*/

		/// <summary>
		/// 
		/// </summary>
		public WinGroupEntity WinGroup
		{
			get { return m_win_group_id; }
			set
			{
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for WinGroupId", value, "null");

				m_isChanged |= ( m_win_group_id != value ); 
				m_win_group_id = value;
			}

		}
		
		/*
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
		*/
				
		#endregion 
	}
}
