/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class DemoConf
	{

		#region Private Members
		private bool m_isChanged;

		private int m_demo_conf_id; 
		private string m_conf_code; 
		private string m_conf_value; 		
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public DemoConf()
		{
			m_demo_conf_id = 0; 
			m_conf_code = String.Empty; 
			m_conf_value = String.Empty; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public DemoConf(
			int demo_conf_id, 
			string conf_code)
			: this()
		{
			m_demo_conf_id = demo_conf_id;
			m_conf_code = conf_code;
			m_conf_value = String.Empty;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_demo_conf_id; }
			set
			{
				m_isChanged |= ( m_demo_conf_id != value ); 
				m_demo_conf_id = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public string Code
		{
			get { return m_conf_code; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for ConfCode", value, "null");
				
				if(  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for ConfCode", value, value.ToString());
				
				m_isChanged |= (m_conf_code != value); m_conf_code = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>
		public string Value
		{
			get { return m_conf_value; }

			set	
			{	
				if(  value != null &&  value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for ConfValue", value, value.ToString());
				
				m_isChanged |= (m_conf_value != value); m_conf_value = value;
			}
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
	}
}
