/*
insert license info here
*/
using System;
using System.Collections;
using System.Collections.Generic;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
    public sealed class EventoLoginEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_evento_login_id; 
		private IList<UserPasswordEntity> m_AuditLoginList; 
		private string m_evento; 		
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public EventoLoginEntity()
		{
			m_evento_login_id = 0; 
			m_AuditLoginList = new List<UserPasswordEntity>(); 
			m_evento = String.Empty; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public EventoLoginEntity(
			int evento_login_id, 
			string evento_login_code)
			: this()
		{
			m_evento_login_id = evento_login_id;
			m_evento = String.Empty;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_evento_login_id; }
			set
			{
				m_isChanged |= ( m_evento_login_id != value ); 
				m_evento_login_id = value;
			}

		}
			
		public IList<UserPasswordEntity> UsersPasswordsList
		{
			get
			{
				return m_AuditLoginList;
			}
			set
			{
				m_AuditLoginList = value;
			}
		}

			
		/// <summary>
		/// 
		/// </summary>
		public string Evento
		{
			get { return m_evento; }

			set	
			{	
				if(  value != null &&  value.Length > 150)
                    throw new ArgumentOutOfRangeException("Invalid value for Evento", value, value.ToString());
				
				m_isChanged |= (m_evento != value); m_evento = value;
			}
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
	
        public override string Key
        {
            get
            {
                return m_evento_login_id.ToString();
            }
            set
            {
                m_evento_login_id = Convert.ToInt32(value);
            }
        }
    }
}
