/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class FollowupRequestGroupDefaultEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_frgd_id;
        private UserTypeEntity m_user_type_id;
        private FollowupRequestGroupEntity m_frg_id; 		
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public FollowupRequestGroupDefaultEntity()
		{
			m_frgd_id = 0;
            m_user_type_id = new UserTypeEntity(); 
			m_frg_id = new FollowupRequestGroupEntity(); 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public FollowupRequestGroupDefaultEntity(
			int frgu_id,
            UserTypeEntity UserType, 
			FollowupRequestGroupEntity frg_id)
			: this()
		{
			m_frgd_id = frgu_id;
            UserType = UserType;
			m_frg_id = frg_id;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_frgd_id; }
			set
			{
				m_isChanged |= ( m_frgd_id != value ); 
				m_frgd_id = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public UserTypeEntity UserType
		{
			get { return m_user_type_id; }
			set
			{
				if( value == null )
                    throw new ArgumentOutOfRangeException("Null value not allowed for UserType", value, "null");

				m_isChanged |= ( m_user_type_id != value ); 
				m_user_type_id = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public FollowupRequestGroupEntity FollowupRqstGrp
		{
			get { return m_frg_id; }
			set
			{
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for FollowupRqstGrpId", value, "null");

				m_isChanged |= ( m_frg_id != value ); 
				m_frg_id = value;
			}

		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
        public override string Key
        {
            get
            {
                return m_frgd_id.ToString();
            }
            set
            {
                m_frgd_id = Convert.ToInt32(value);
            }
        }
    }
}
