/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class FollowupRequestGroupUserEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_frgu_id; 
		private PhxUserEntity m_phx_user_id;
        private FollowupRequestGroupEntity m_frg_id; 		
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public FollowupRequestGroupUserEntity()
		{
			m_frgu_id = 0; 
			m_phx_user_id = new PhxUserEntity(); 
			m_frg_id = new FollowupRequestGroupEntity(); 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public FollowupRequestGroupUserEntity(
			int frgu_id, 
			PhxUserEntity phx_user_id, 
			FollowupRequestGroupEntity frg_id)
			: this()
		{
			m_frgu_id = frgu_id;
			m_phx_user_id = phx_user_id;
			m_frg_id = frg_id;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_frgu_id; }
			set
			{
				m_isChanged |= ( m_frgu_id != value ); 
				m_frgu_id = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public PhxUserEntity PhxUser
		{
			get { return m_phx_user_id; }
			set
			{
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for PhxUserId", value, "null");

				m_isChanged |= ( m_phx_user_id != value ); 
				m_phx_user_id = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public FollowupRequestGroupEntity FollowupRqstGrp
		{
			get { return m_frg_id; }
			set
			{
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for FollowupRqstGrpId", value, "null");

				m_isChanged |= ( m_frg_id != value ); 
				m_frg_id = value;
			}

		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
        public override string Key
        {
            get
            {
                return m_frgu_id.ToString();
            }
            set
            {
                m_frgu_id = Convert.ToInt32(value);
            }
        }
    }
}
