/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class FollowupRequestGroupEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_frg_id; 
		private IList m_FollowupGroupUsersList; 
		private IList m_FollowupGroupPwdsList;
		private string m_frg_name;
        private bool m_frg_active; 
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public FollowupRequestGroupEntity()
		{
			m_frg_id = 0; 
			m_FollowupGroupUsersList = new ArrayList(); 
			m_FollowupGroupPwdsList = new ArrayList(); 
			m_frg_name = String.Empty; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public FollowupRequestGroupEntity(
			int frg_id, 
			string frg_name)
			: this()
		{
			m_frg_id = frg_id;
			m_frg_name = frg_name;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_frg_id; }
			set
			{
				m_isChanged |= ( m_frg_id != value ); 
				m_frg_id = value;
			}

		}
			
		public IList FollowupGroupUsersList
		{
			get
			{
				return m_FollowupGroupUsersList;
			}
			set
			{
				m_FollowupGroupUsersList = value;
			}
		}


		public IList FollowupRequestGroupPasswordList
		{
			get
			{
				return m_FollowupGroupPwdsList;
			}
			set
			{
				m_FollowupGroupPwdsList = value;
			}
		}

		/// <summary>
		/// Nombre del grupo
		/// </summary>
		public string Name
		{
			get { return m_frg_name; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for Name", value, "null");
				
				if(  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for Name", value, value.ToString());
				
				m_isChanged |= (m_frg_name != value); m_frg_name = value;
			}
		}
        public bool Active
        {
            get { return m_frg_active; }
            set
            {
                m_isChanged |= (m_frg_active != value);
                m_frg_active = value;
            }

        }

		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
        public override string Key
        {
            get
            {
                return m_frg_id.ToString();
            }
            set
            {
                m_frg_id = Convert.ToInt32(value);
            }
        }
        public override string ToString()
        {
            return this.Name;
        }

    }
}
