/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class FollowupRequestGroupPasswordEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_frgp_id; 
		private FollowupRequestGroupEntity m_frg_id; 
		private UserPasswordEntity m_user_password_id; 
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public FollowupRequestGroupPasswordEntity()
		{
			m_frgp_id = 0; 
			m_frg_id = new FollowupRequestGroupEntity(); 
			m_user_password_id = new UserPasswordEntity(); 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public FollowupRequestGroupPasswordEntity(
			int frgp_id, 
			FollowupRequestGroupEntity frg_id, 
			UserPasswordEntity user_password_id)
			: this()
		{
			m_frgp_id = frgp_id;
			m_frg_id = frg_id;
			m_user_password_id = user_password_id;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_frgp_id; }
			set
			{
				m_isChanged |= ( m_frgp_id != value ); 
				m_frgp_id = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public FollowupRequestGroupEntity FollowupRqstGrp
		{
			get { return m_frg_id; }
			set
			{
				if( value == null )
                    throw new ArgumentOutOfRangeException("Null value not allowed for FollowupRqstGrp", value, "null");

				m_isChanged |= ( m_frg_id != value ); 
				m_frg_id = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public UserPasswordEntity UserPassword
		{
			get { return m_user_password_id; }
			set
			{
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for UserPasswordId", value, "null");

				m_isChanged |= ( m_user_password_id != value ); 
				m_user_password_id = value;
			}

		}
			
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
	
        public override string Key
        {
            get
            {
                return m_frgp_id.ToString();
            }
            set
            {
                m_frgp_id = Convert.ToInt32(value);
            }
        }
    }
}
