/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class GlobalWinGroupEntity : WinGroupEntity
	{

		#region Private Members
		private bool m_isChanged;

		//private int m_win_group_id; 
		private IList m_GlobalWinGroupsList; 
		private WinDomainEntity m_win_domain_id; 		
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public GlobalWinGroupEntity()
		{
			//m_win_group_id = 0; 
			Id = 0;
			m_GlobalWinGroupsList = new ArrayList(); 
			m_win_domain_id = new WinDomainEntity(); 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public GlobalWinGroupEntity(
			int win_group_id, 
			WinDomainEntity win_domain_id)
			: this()
		{
			Id = win_group_id;
			m_win_domain_id = win_domain_id;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/*
		/// <summary>
		/// 
		/// </summary>
		public int WinGroupId
		{
			get { return m_win_group_id; }
			set
			{
				m_isChanged |= ( m_win_group_id != value ); 
				m_win_group_id = value;
			}

		}*/
		
		/*
		public IList GlobalWinGroupsList
		{
			get
			{
				return m_GlobalWinGroupsList;
			}
			set
			{
				m_GlobalWinGroupsList = value;
			}
		}*/

		/// <summary>
		/// dominio al que pertenece el grupo
		/// </summary>
		public WinDomainEntity WinDomain
		{
			get { return m_win_domain_id; }
			set
			{
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for WinDomainId", value, "null");

				m_isChanged |= ( m_win_domain_id != value ); 
				m_win_domain_id = value;
			}

		}
			
		/*
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
		*/
				
		#endregion 
	}
}
