/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
    public sealed class ItemLoteChkWinLocalUsersEntity : UserEntity
	{

		#region Private Members
		private bool m_isChanged;

		//private int m_user_id; 
		private int _id;
        private LoteChkWinLocalUsersEntity _lote;
        private WinLocalUserEntity _win_local_user;
        private bool? _chk_ping_nombre_equipo;
        private bool? _chk_ping_ip_equipo;
        private bool? _chk_pwd;
        private bool? _chk_username;
        private string _nombre_equipo_ping_ip;
        private DateTime? _fecha_chk;
        private AccionItemChkWinLocalUserEntity _accion;

        #endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public ItemLoteChkWinLocalUsersEntity()
		{
			//m_user_id = 0; 
			this.Id = 0;
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		#endregion // End Required Fields Only Constructor

		#region Public Properties
		
		
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return _id; }
			set
			{
                m_isChanged |= (_id != value);
                _id = value;
			}

		}

        public LoteChkWinLocalUsersEntity Lote
        {
            get { return _lote; }
            set { _lote = value; }            
        }
        public WinLocalUserEntity WinLocalUser
        {
            get { return _win_local_user; }
            set { _win_local_user = value; }            
        }
        public DateTime? FechaChk
        {
            get { return _fecha_chk; }
            set { _fecha_chk = value; }            
        }
        public bool? ChkPingNombreEquipo
        {
            get { return _chk_ping_nombre_equipo; }
            set { _chk_ping_nombre_equipo = value; }            
        }
        public bool? ChkPingIPEquipo
        {
            get { return _chk_ping_ip_equipo; }
            set { _chk_ping_ip_equipo = value; }            
        }
        public bool? ChkPwd
        {
            get { return _chk_pwd; }
            set { _chk_pwd = value; }            
        }
        public bool? ChkUsername
        {
            get { return _chk_username; }
            set { _chk_username = value; }            
        }
        public AccionItemChkWinLocalUserEntity Accion
        {
            get { return _accion; }
            set { _accion = value; }
        }
        public string NombreEquipoPingIP
        {
            get { return _nombre_equipo_ping_ip; }

            set
            {
                if (value != null && value.Length > 150)
                    throw new ArgumentOutOfRangeException("NombreEquipoPingIP", value, "Invalid value for NombreEquipoPingIP");

                m_isChanged |= (_nombre_equipo_ping_ip != value);
                _nombre_equipo_ping_ip = value;
            }
        }

        public override string Key
        {
            get
            {
                return _id.ToString();
            }
            set
            {
                _id = Convert.ToInt32(value);
            }
        }
		#endregion 
	}
}
