/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class LocalWinGroupEntity : WinGroupEntity
	{

		#region Private Members
		private bool m_isChanged;

		//private int m_win_group_id; 
		private IList m_LocalWinGroupsList; 
		private WinPCEntity m_win_pc_id; 		
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public LocalWinGroupEntity()
		{
			//m_win_group_id = 0; 
			Id = 0;
			m_LocalWinGroupsList = new ArrayList(); 
			m_win_pc_id = new WinPCEntity(); 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public LocalWinGroupEntity(
			int win_group_id, 
			WinPCEntity win_pc_id)
			: this()
		{
			//m_win_group_id = win_group_id;
			Id = win_group_id;
			m_win_pc_id = win_pc_id;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties

        /*			
		/// <summary>
		/// 
		/// </summary>
		public int WinGroupId
		{
			get { return m_win_group_id; }
			set
			{
				m_isChanged |= ( m_win_group_id != value ); 
				m_win_group_id = value;
			}

		}
		*/
			
		/*
		public IList LocalWinGroupsList
		{
			get
			{
				return m_LocalWinGroupsList;
			}
			set
			{
				m_LocalWinGroupsList = value;
			}
		}*/

		/// <summary>
		/// 
		/// </summary>
		public WinPCEntity WinPc
		{
			get { return m_win_pc_id; }
			set
			{
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for WinPcId", value, "null");

				m_isChanged |= ( m_win_pc_id != value ); 
				m_win_pc_id = value;
			}

		}
		
		/*
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
		*/
				
		#endregion 
	}
}
