/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
    public sealed class LoteChkWinLocalUsersEntity : UserEntity
	{

		#region Private Members
		private bool m_isChanged;

		//private int m_user_id; 
		private int _id;
        private DateTime _fecha_creacion;
        private DateTime _fecha_programada;
        private DateTime? _fecha_inicio_proceso;
        private DateTime? _fecha_fin_proceso;
        #endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public LoteChkWinLocalUsersEntity()
		{
			//m_user_id = 0; 
			this.Id = 0;
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		#endregion // End Required Fields Only Constructor

		#region Public Properties
		
		
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return _id; }
			set
			{
                m_isChanged |= (_id != value);
                _id = value;
			}

		}

        public DateTime FechaCreacion
        {
            get { return _fecha_creacion; }
            set { _fecha_creacion = value; }
        }
        public DateTime FechaProgramada
        {
            get { return _fecha_programada; }
            set { _fecha_programada = value; }            
        }
        public DateTime? FechaInicioProceso
        {
            get { return _fecha_inicio_proceso; }
            set { _fecha_inicio_proceso = value; }            
        }
        public DateTime? FechaFinProceso
        {
            get { return _fecha_fin_proceso; }
            set { _fecha_fin_proceso = value; }            
        }
        public override string Key
        {
            get
            {
                return _id.ToString();
            }
            set
            {
                _id = Convert.ToInt32(value);
            }
        }

		#endregion 
	}
}
