/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
    public sealed class MailTypeEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

        private int m_mail_type_id; 
		private IList m_MailsList; 
		private string m_mail_type_name; 		
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public MailTypeEntity()
		{
			m_mail_type_id = 0; 
			m_MailsList = new ArrayList(); 
			m_mail_type_name = String.Empty; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public MailTypeEntity(
			string mail_type_name)
			: this()
		{
            m_mail_type_name = mail_type_name;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_mail_type_id; }
			set
			{
				m_isChanged |= ( m_mail_type_id != value ); 
				m_mail_type_id = value;
			}

		}

        public IList MailsList
		{
			get
			{
				return m_MailsList;
			}
			set
			{
				m_MailsList = value;
			}
		}

		/// <summary>
		/// 
			
		/// <summary>
		/// 
		/// </summary>
		public string Name
		{
			get { return m_mail_type_name; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for Name", value, "null");
				
				if(  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for Name", value, value.ToString());
				
				m_isChanged |= (m_mail_type_name != value); m_mail_type_name = value;
			}
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
        public override string Key
        {
            get
            {
                return m_mail_type_id.ToString();
            }
            set
            {
                m_mail_type_id = Convert.ToInt32(value);
            }
        }
        public override string ToString()
        {
            return m_mail_type_name;
        }
    }
}
