/*
insert license info here
*/
using System;
using System.Collections;
using PhalanxCommon.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
    public sealed class MailAlertEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_mail_id; 
		private MailTypeEntity m_mail_type_id;
        private Nullable<DateTime> m_creation_date;
        private Nullable<DateTime> m_send_date;
        private string m_subject;
        private string m_to_name;
        private string m_to_address;
        private string m_cc1_name;
        private string m_cc1_address;
        private string m_cc2_name;
        private string m_cc2_address;
        private string m_cc3_name;
        private string m_cc3_address;
        private string m_cc4_name;
        private string m_cc4_address;
        private string m_cc5_name;
        private string m_cc5_address;
        private string m_cc6_name;
        private string m_cc6_address;
        private string m_cc7_name;
        private string m_cc7_address;
        private string m_cc8_name;
        private string m_cc8_address;
        private string m_cc9_name;
        private string m_cc9_address;
        private string m_cc10_name;
        private string m_cc10_address;
        private string m_cc11_name;
        private string m_cc11_address;
        private string m_cc12_name;
        private string m_cc12_address;
        private string m_body;
        private int m_send_attemp;
        private IList m_MailAlertCCList; 

		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public MailAlertEntity()
		{
			m_mail_id = 0;
            m_send_attemp = 0; 
			m_mail_type_id = new MailTypeEntity();
            m_subject = String.Empty;
            m_to_name = String.Empty;
            m_to_address = String.Empty;
            m_cc1_name = String.Empty;
            m_cc1_address = String.Empty;
            m_cc2_name = String.Empty;
            m_cc2_address = String.Empty;
            m_cc3_name = String.Empty;
            m_cc3_address = String.Empty;

            m_cc4_name = String.Empty;
            m_cc4_address = String.Empty;

            m_cc5_name = String.Empty;
            m_cc5_address = String.Empty;

            m_cc6_name = String.Empty;
            m_cc6_address = String.Empty;

            m_cc7_name = String.Empty;
            m_cc7_address = String.Empty;

            m_cc8_name = String.Empty;
            m_cc8_address = String.Empty;

            m_cc9_name = String.Empty;
            m_cc9_address = String.Empty;

            m_cc10_name = String.Empty;
            m_cc10_address = String.Empty;

            m_cc11_name = String.Empty;
            m_cc11_address = String.Empty;

            m_cc12_name = String.Empty;
            m_cc12_address = String.Empty;

            m_body = String.Empty;
            //m_send_date = new Nullable<DateTime>();

            m_MailAlertCCList = new MailAlertCCEntityCollection(); 

		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_mail_id; }
			set
			{
				m_isChanged |= ( m_mail_id != value ); 
				m_mail_id = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
        public MailTypeEntity MailType
		{
			get { return m_mail_type_id; }
			set
			{
				if( value == null )
                    throw new ArgumentOutOfRangeException("Null value not allowed for MailType", value, "null");

				m_isChanged |= ( m_mail_type_id != value ); 
				m_mail_type_id = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
        public string Subject
		{
            get { return m_subject; }

			set	
			{	
				if( value == null )
                    throw new ArgumentOutOfRangeException("Null value not allowed for Subject", value, "null");
				
				if(  value.Length > 100)
                    throw new ArgumentOutOfRangeException("Invalid value for Subject", value, value.ToString());

                m_isChanged |= (m_subject != value); m_subject = value;
			}
		}

        public string ToName
		{
            get { return m_to_name; }

			set	
			{	
				
				if(  value.Length > 100)
                    throw new ArgumentOutOfRangeException("Invalid value for ToName", value, value.ToString());

                m_isChanged |= (m_to_name != value); m_to_name = value;
			}
		}
			
        public string ToAddress
		{
            get { return m_to_address; }

			set	
			{	
				if( value == null )
                    throw new ArgumentOutOfRangeException("Null value not allowed for ToAddress", value, "null");
				
				if(  value.Length > 150)
                    throw new ArgumentOutOfRangeException("Invalid value for ToAddress", value, value.ToString());

                m_isChanged |= (m_to_address != value); m_to_address = value;
			}
		}

        public string Cc1Name
		{
            get { return m_cc1_name; }

			set	
			{	
				
				if(  value.Length > 100)
                    throw new ArgumentOutOfRangeException("Invalid value for Cc1Name", value, value.ToString());

                m_isChanged |= (m_cc1_name != value); m_cc1_name = value;
			}
		}

        public string Cc1Address
		{
            get { return m_cc1_address; }

			set	
			{	
				
				if(  value.Length > 150)
                    throw new ArgumentOutOfRangeException("Invalid value for Cc1Address", value, value.ToString());

                m_isChanged |= (m_cc1_address != value); m_cc1_address = value;
			}
		}

        public string Cc2Name
		{
            get { return m_cc2_name; }

			set	
			{	
				
				if(  value.Length > 100)
                    throw new ArgumentOutOfRangeException("Invalid value for Cc2Name", value, value.ToString());

                m_isChanged |= (m_cc2_name != value); m_cc2_name = value;
			}
		}

        public string Cc2Address
		{
            get { return m_cc2_address; }

			set	
			{	
				
				if(  value.Length > 150)
                    throw new ArgumentOutOfRangeException("Invalid value for Cc2Address", value, value.ToString());

                m_isChanged |= (m_cc2_address != value); m_cc2_address = value;
			}
		}
        public string Cc3Name
        {
            get { return m_cc3_name; }

            set
            {

                if (value != null && value.Length > 150)
                    throw new ArgumentOutOfRangeException("Invalid value for Cc3Name", value, value.ToString());

                m_isChanged |= (m_cc3_name != value); m_cc3_name = value;
            }
        }
        public string Cc4Name
        {
            get { return m_cc4_name; }

            set
            {

                if (value != null && value.Length > 150)
                    throw new ArgumentOutOfRangeException("Invalid value for Cc4Name", value, value.ToString());

                m_isChanged |= (m_cc4_name != value); m_cc4_name = value;
            }
        }
        public string Cc5Name
        {
            get { return m_cc5_name; }

            set
            {

                if (value != null && value.Length > 150)
                    throw new ArgumentOutOfRangeException("Invalid value for Cc5Name", value, value.ToString());

                m_isChanged |= (m_cc5_name != value); m_cc5_name = value;
            }
        }
        public string Cc6Name
        {
            get { return m_cc6_name; }

            set
            {

                if (value != null && value.Length > 150)
                    throw new ArgumentOutOfRangeException("Invalid value for Cc6Name", value, value.ToString());

                m_isChanged |= (m_cc6_name != value); m_cc6_name = value;
            }
        }
        public string Cc7Name
        {
            get { return m_cc7_name; }

            set
            {

                if (value != null && value.Length > 150)
                    throw new ArgumentOutOfRangeException("Invalid value for Cc7Name", value, value.ToString());

                m_isChanged |= (m_cc7_name != value); m_cc7_name = value;
            }
        }
        public string Cc8Name
        {
            get { return m_cc8_name; }

            set
            {

                if (value != null && value.Length > 150)
                    throw new ArgumentOutOfRangeException("Invalid value for Cc8Name", value, value.ToString());

                m_isChanged |= (m_cc8_name != value); m_cc8_name = value;
            }
        }
        public string Cc9Name
        {
            get { return m_cc9_name; }

            set
            {

                if (value != null && value.Length > 150)
                    throw new ArgumentOutOfRangeException("Invalid value for Cc9Name", value, value.ToString());

                m_isChanged |= (m_cc9_name != value); m_cc9_name = value;
            }
        }
        public string Cc10Name
        {
            get { return m_cc10_name; }

            set
            {

                if (value != null && value.Length > 150)
                    throw new ArgumentOutOfRangeException("Invalid value for Cc10Name", value, value.ToString());

                m_isChanged |= (m_cc10_name != value); m_cc10_name = value;
            }
        }
        public string Cc11Name
        {
            get { return m_cc11_name; }

            set
            {

                if (value != null && value.Length > 150)
                    throw new ArgumentOutOfRangeException("Invalid value for Cc11Name", value, value.ToString());

                m_isChanged |= (m_cc11_name != value); m_cc11_name = value;
            }
        }
        public string Cc12Name
        {
            get { return m_cc12_name; }

            set
            {

                if (value != null && value.Length > 150)
                    throw new ArgumentOutOfRangeException("Invalid value for Cc12Name", value, value.ToString());

                m_isChanged |= (m_cc12_name != value); m_cc12_name = value;
            }
        }
        public string Cc3Address
        {
            get { return m_cc3_address; }

            set
            {

                if (value != null && value.Length > 150)
                    throw new ArgumentOutOfRangeException("Invalid value for Cc3Address", value, value.ToString());

                m_isChanged |= (m_cc3_address != value); m_cc3_address = value;
            }
        }

        public string Cc4Address
        {
            get { return m_cc4_address; }

            set
            {

                if (value != null && value.Length > 150)
                    throw new ArgumentOutOfRangeException("Invalid value for Cc4Address", value, value.ToString());

                m_isChanged |= (m_cc4_address != value); m_cc4_address = value;
            }
        }

        public string Cc5Address
        {
            get { return m_cc5_address; }

            set
            {

                if (value != null && value.Length > 150)
                    throw new ArgumentOutOfRangeException("Invalid value for Cc5Address", value, value.ToString());

                m_isChanged |= (m_cc5_address != value); m_cc5_address = value;
            }
        }

        public string Cc6Address
        {
            get { return m_cc6_address; }

            set
            {

                if (value != null && value.Length > 150)
                    throw new ArgumentOutOfRangeException("Invalid value for Cc6Address", value, value.ToString());

                m_isChanged |= (m_cc6_address != value); m_cc6_address = value;
            }
        }

        public string Cc7Address
        {
            get { return m_cc7_address; }

            set
            {

                if (value != null && value.Length > 150)
                    throw new ArgumentOutOfRangeException("Invalid value for Cc7Address", value, value.ToString());

                m_isChanged |= (m_cc7_address != value); m_cc7_address = value;
            }
        }

        public string Cc8Address
        {
            get { return m_cc8_address; }

            set
            {

                if (value != null && value.Length > 150)
                    throw new ArgumentOutOfRangeException("Invalid value for Cc8Address", value, value.ToString());

                m_isChanged |= (m_cc8_address != value); m_cc8_address = value;
            }
        }

        public string Cc9Address
        {
            get { return m_cc9_address; }

            set
            {

                if (value != null && value.Length > 150)
                    throw new ArgumentOutOfRangeException("Invalid value for Cc9Address", value, value.ToString());

                m_isChanged |= (m_cc9_address != value); m_cc9_address = value;
            }
        }

        public string Cc10Address
        {
            get { return m_cc10_address; }

            set
            {

                if (value != null && value.Length > 150)
                    throw new ArgumentOutOfRangeException("Invalid value for Cc10Address", value, value.ToString());

                m_isChanged |= (m_cc10_address != value); m_cc10_address = value;
            }
        }

        public string Cc11Address
        {
            get { return m_cc11_address; }

            set
            {

                if (value != null && value.Length > 150)
                    throw new ArgumentOutOfRangeException("Invalid value for Cc11Address", value, value.ToString());

                m_isChanged |= (m_cc11_address != value); m_cc11_address = value;
            }
        }

        public string Cc12Address
        {
            get { return m_cc12_address; }

            set
            {

                if (value != null && value.Length > 150)
                    throw new ArgumentOutOfRangeException("Invalid value for Cc12Address", value, value.ToString());

                m_isChanged |= (m_cc12_address != value); m_cc12_address = value;
            }
        }


        public string Body
		{
            get { return m_body; }

			set	
			{	
				if( value == null )
                    throw new ArgumentOutOfRangeException("Null value not allowed for Body", value, "null");
				
				if(  value.Length > 1000)
                    throw new ArgumentOutOfRangeException("Invalid value for Body", value, value.ToString());

                m_isChanged |= (m_body != value); m_body = value;
			}
		}

        public int SendAttemp
        {
            get
            {
                return m_send_attemp;
            }
            set
            {
                m_send_attemp = value;
            }
        }
			
        public Nullable<DateTime> SendDate
		{
			get { return m_send_date; }
			set
			{
                m_isChanged |= (m_send_date != value);
                m_send_date = value;
			}

		}

        public Nullable<DateTime> CreationDate
		{
			get { return m_creation_date; }
			set
			{
                m_isChanged |= (m_creation_date != value);
                m_creation_date = value;
			}

		}

        public IList MailAlertCCList
        {
            get
            {
                return m_MailAlertCCList;
            }
            set
            {
                m_MailAlertCCList = value;
            }
        }
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}

		#endregion 
        public override string Key
        {
            get
            {
                return m_mail_id.ToString();
            }
            set
            {
                m_mail_id = Convert.ToInt32(value);
            }
        }
    }
}
