/*
insert license info here
*/
using System;
using System.Collections;
using System.Collections.Generic;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class MailGroupEntity : BaseEntity
	{
		#region Private Members

		#endregion

		#region Default ( Empty ) Class Constuctor

		/// <summary>
		/// default constructor
		/// </summary>
		public MailGroupEntity()
		{			
		}

		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		

		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id { get; set; }

        public string Name { get; set; }

        public IList<MailTypeEntity> MailsType { get; set; }
        
        #endregion

        public override string Key
        {
            get
            {
                return this.Id.ToString();
            }
            set
            {
                this.Id = Convert.ToInt32(value);
            }
        }
    }
}
