/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
    public sealed class MailAlertCCEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_mail_id; 
		private MailAlertEntity m_mail_alert_id;
        private string m_cc_name;
        private string m_cc_address;

        #endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public MailAlertCCEntity()
		{
			m_mail_id = 0;
			m_mail_alert_id = new MailAlertEntity();
            m_cc_name = String.Empty;
            m_cc_address = String.Empty;
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_mail_id; }
			set
			{
				m_isChanged |= ( m_mail_id != value ); 
				m_mail_id = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
        public MailAlertEntity MailAlert
		{
			get { return m_mail_alert_id; }
			set
			{
				if( value == null )
                    throw new ArgumentOutOfRangeException("Null value not allowed for MailAlert", value, "null");

                m_isChanged |= (m_mail_alert_id != value);
                m_mail_alert_id = value;
			}

		}
			
        public string CcName
		{
            get { return m_cc_name; }

			set	
			{	
				
				if(  value.Length > 100)
                    throw new ArgumentOutOfRangeException("Invalid value for CcName", value, value.ToString());

                m_isChanged |= (m_cc_name != value); m_cc_name = value;
			}
		}

        public string CcAddress
		{
            get { return m_cc_address; }

			set	
			{	
				
				if(  value.Length > 150)
                    throw new ArgumentOutOfRangeException("Invalid value for CcAddress", value, value.ToString());

                m_isChanged |= (m_cc_address != value); m_cc_address = value;
			}
		}

		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}

		#endregion 
        public override string Key
        {
            get
            {
                return m_mail_id.ToString();
            }
            set
            {
                m_mail_id = Convert.ToInt32(value);
            }
        }
    }
}
