/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public class PasswordRequestEntity : RequestEntity
	{

		#region Private Members
		private bool m_isChanged;
        private string m_ReportContrasenia;
        private string m_ReportContraseniaType;
        private string m_ReportFolio;
        /// <summary>
        /// indica si se busco datos del cambio post devolución (si lo hay) y pre cierre (si lo hay).
        /// Si es true y m_Change = null es porque no hay cambio que cumpla con esas condiciones
        /// </summary>
        private bool m_CambioLoaded = false;
        private HistPasswordChangeEntity m_ChangePostReturn;


		//private int m_request_id; 
		private IList m_PasswordsRequestsList; 
		private UserPasswordEntity m_user_password_id; 		
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public PasswordRequestEntity() : base()
		{
			//m_request_id = 0; 
			base.Id = 0; 
			m_PasswordsRequestsList = new ArrayList(); 
			m_user_password_id = new UserPasswordEntity(); 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public PasswordRequestEntity(
			int request_id, 
			UserPasswordEntity user_password_id)
			: this()
		{
			//m_request_id = request_id;
			base.Id = request_id;
			m_user_password_id = user_password_id;
		}
		#endregion // End Required Fields Only Constructor
        #region Public Properties
        public string ReportContrasenia
        {
            set { m_ReportContrasenia = value; }
            get {return m_ReportContrasenia;}
        }
        public string ReportContraseniaType
        {
            set { m_ReportContraseniaType = value; }
            get { return m_ReportContraseniaType; }
        }
        public string ReportFolio
        {
            set { m_ReportFolio = value; }
            get { return m_ReportFolio; }
        }
        public bool CambioLoaded
        {
            set { m_CambioLoaded = value; }
            get { return m_CambioLoaded; }
        }

        public HistPasswordChangeEntity ChangePostReturn
        {
            set { m_ChangePostReturn = value; }
            get { return m_ChangePostReturn; }
        }


		/*
		/// <summary>
		/// 
		/// </summary>
		public int RequestId
		{
			get { return m_request_id; }
			set
			{
				m_isChanged |= ( m_request_id != value ); 
				m_request_id = value;
			}

		}
		*/
	
		/*
		public IList PasswordsRequestsList
		{
			get
			{
				return m_PasswordsRequestsList;
			}
			set
			{
				m_PasswordsRequestsList = value;
			}
		}
		*/

		/// <summary>
		/// Password consultado
		/// </summary>
		public UserPasswordEntity UserPassword
		{
			get { return m_user_password_id; }
			set
			{
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for UserPasswordId", value, "null");

				m_isChanged |= ( m_user_password_id != value ); 
				m_user_password_id = value;
			}

		}

        /*
        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public bool IsChanged
        {
            get { return m_isChanged; }
        }
        */
        public string State
        {
            get { return base.RqstState.RqstStateDesc; }
        }
        public string RqstDateddmmyyyy
        {
            get { return RequestDate.ToString("dd/MM/yyyy"); }
        }

        public string RqstDatedatetime
        {
            get { return RequestDate.ToString("dd/MM/yyyy HH:mm:ss"); }
        }
        public string ExpDatedatetime
        {
            get
            {
                if (ExpirationDate != null)
                {
                    return ExpirationDate.Value.ToString("dd/MM/yyyy HH:mm:ss");
                }
                else
                {
                    return "";
                }
            }
        }
        public string UserName
        {
            get
            {
                return User.Username;
            }
        }
        public string UserDesc
        {
            get
            {
                return User.Desc;
            }
        }

        public UserEntity User
        {
            get
            {
                return (UserEntity)UserPassword.UsersList[0];
            }
        }

        #region Propiedades para Request de Win Pass

        private WinLocalUserEntity WinUser
        {
            get
            {
                return (WinLocalUserEntity)UserPassword.UsersList[0];
            }
        }
        
        /*
        public string PCName
        {
            get
            {
                return User.PCName;
            }
        }
        public string Domain
        {
            get
            {
                return this.User.Domain;
            }
        }
         * */

        public bool ModificadaDespuesDevolucion
        {
            get
            {
                return UserPassword.DLastChange != null &&
                        (
                            (ReturnDate != null && UserPassword.DLastChange.Value > ReturnDate.Value)
                            ||
                            (ExpirationDate != null && UserPassword.DLastChange.Value > ExpirationDate)
                        );
            }
        }

        #endregion
        
        #endregion
    }
}
