/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
    public sealed class PhxContingenciaEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_phx_cont_id;
        private string m_esquema_activo;
        private DateTime m_fecha;
        #endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public PhxContingenciaEntity()
		{
			m_phx_cont_id = 0; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_phx_cont_id; }
			set
			{
				m_isChanged |= ( m_phx_cont_id != value ); 
				m_phx_cont_id = value;
			}

		}
			

		/// <summary>
		/// 
		/// </summary>
        public string EsquemaActivo
		{
            get { return m_esquema_activo; }

			set	
			{	
				if( value == null )
                    throw new ArgumentOutOfRangeException("Null value not allowed for EsquemaActivo", value, "null");
				
				if(  value.Length > 50)
                    throw new ArgumentOutOfRangeException("Invalid value for EsquemaActivo", value, value.ToString());

                m_isChanged |= (m_esquema_activo != value); 
                m_esquema_activo = value;
			}
		}

        public DateTime Fecha
		{
			get { return m_fecha; }
			set
			{
                m_isChanged |= (m_fecha != value);
                m_fecha = value;
			}

		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
		
		#endregion 
	
        public override string Key
        {
            get
            {
                return this.m_phx_cont_id.ToString();
            }
            set
            {
                this.m_phx_cont_id = Convert.ToInt32(value);
            }
        }
        
        public override string ToString()
        {
            return m_esquema_activo;
        }

        public bool EsProduccion
        {
            get
            {
                if (m_esquema_activo == "@PROD@")
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
        }
        public bool EsContingencia
        {
            get
            {
                if (m_esquema_activo == "@CONT@")
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
        }
        public void SetProduccion()
        {
            m_esquema_activo = "@PROD@";
        }
        public void SetContingencia()
        {
            m_esquema_activo = "@CONT@";
        }
    }
}
