/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class PhxLogUsuarioInactivado : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_phx_log_id;
		private string m_username;
		private string m_fullname;
		private string m_user_domain;
		private DateTime m_fecha_inactivacion;
		private PhxUserEntity m_user_id;
        #endregion

		#region Public Properties

		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_phx_log_id; }
			set
			{
				m_isChanged |= (m_phx_log_id != value);
				m_phx_log_id = value;
			}

		}

		/// <summary>
		/// nombre de usuario. En un principio sería el usuario del dominio
		/// </summary>
		public string Username
		{
			get { return m_username; }

			set
			{
				if (value == null)
					throw new ArgumentOutOfRangeException("Null value not allowed for Username", value, "null");

				if (value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for Username", value, value.ToString());

				m_isChanged |= (m_username != value); m_username = value;
			}
		}

		/// <summary>
		/// nombre completo del usuario
		/// </summary>
		public string Fullname
		{
			get { return m_fullname; }

			set
			{
				if (value == null)
					throw new ArgumentOutOfRangeException("Null value not allowed for Fullname", value, "null");

				if (value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for Fullname", value, value.ToString());

				m_isChanged |= (m_fullname != value); m_fullname = value;
			}
		}

		/// <summary>
		/// Dominio al cual pertenece el usuario. El nombre del dominio será en formato NT Domain
		/// </summary>
		public string Domain
		{
			get { return m_user_domain; }

			set
			{
				if (value != null && value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for UserDomain", value, value.ToString());

				m_isChanged |= (m_user_domain != value); m_user_domain = value;
			}
		}

		public PhxUserEntity PhxUser
		{
			get { return m_user_id; }
			set
			{
				if (value == null)
					throw new ArgumentOutOfRangeException("Null value not allowed for AppId", value, "null");

				m_isChanged |= (m_user_id != value);
				m_user_id = value;
			}

		}

		public DateTime FechaInactivacion
		{
			get { return m_fecha_inactivacion; }
			set
			{
				m_isChanged |= (m_fecha_inactivacion != value);
				m_fecha_inactivacion = value;
			}

		}

		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 

		public override string Key
		{
			get
			{
				return m_phx_log_id.ToString();
			}
			set
			{
				m_phx_log_id = Convert.ToInt32(value);
			}
		}
	}
}
