/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class PhxPrivilegeRoleEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int _id;
        private PhxRoleEntity _role;
        private PhxPrivilegeEntity _privilege;
        #endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public PhxPrivilegeRoleEntity()
		{
            _id = 0;
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return _id; }
			set
			{
                m_isChanged |= (_id != value);
                _id = value;
			}

		}
        public PhxRoleEntity Role
        {
            get { return _role; }
            set { _role = value; }
        }
        public PhxPrivilegeEntity Privilege
        {
            get { return _privilege; }
            set { _privilege = value; }
        }

		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
        public override string Key
        {
            get
            {
                return _id.ToString();
            }
            set
            {
                _id = Convert.ToInt32(value);
            }
        }
    }
}
