/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class PhxPrivilegeEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int _id;
        private string _name;
        private string _code;
        private PhxPrivilegeGroupEntity _privilege_grp;
        private IList _privilege_role_list;
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public PhxPrivilegeEntity()
		{
            _id = 0;
            _privilege_role_list = new ArrayList();
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return _id; }
			set
			{
                m_isChanged |= (_id != value);
                _id = value;
			}

		}
        public PhxPrivilegeGroupEntity Group
        {
            get { return _privilege_grp; }
            set { _privilege_grp = value; }
        }
        public string Name
        {
            get { return _name; }

            set
            {
                if (value == null)
                    throw new ArgumentOutOfRangeException("Null value not allowed for Name", value, "null");

                if (value.Length > 150)
                    throw new ArgumentOutOfRangeException("Invalid value for Name", value, value.ToString());

                m_isChanged |= (_name != value); _name = value;
            }
        }
        public string Code
        {
            get { return _code; }

            set
            {
                if (value == null)
                    throw new ArgumentOutOfRangeException("Null value not allowed for Code", value, "null");

                if (value.Length > 150)
                    throw new ArgumentOutOfRangeException("Invalid value for Code", value, value.ToString());

                m_isChanged |= (_code != value); _code = value;
            }
        }

        public IList PhxPrivilegeRoleList
        {
            get { return _privilege_role_list; }
            set { _privilege_role_list = value; }
        }
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
        public override string Key
        {
            get
            {
                return _id.ToString();
            }
            set
            {
                _id = Convert.ToInt32(value);
            }
        }
    }
}
