/*
insert license info here
*/
using System;
using System.Collections;
using System.Collections.Generic;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class PhxRoleEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_phx_role_id; 
		private IList<PhxRoleUserEntity> m_PhxRolesUsersList; 
		private string m_role_name; 
		private string m_role_code;
        private IList<PhxPrivilegeRoleEntity> m_privilege_role_list;
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public PhxRoleEntity()
		{
			m_phx_role_id = 0;
            m_PhxRolesUsersList = new List<PhxRoleUserEntity>();
            m_privilege_role_list = new List<PhxPrivilegeRoleEntity>();
            m_role_name = String.Empty; 
			m_role_code = String.Empty; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public PhxRoleEntity(
			int phx_role_id, 
			string role_name)
			: this()
		{
			m_phx_role_id = phx_role_id;
			m_role_name = role_name;
			
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_phx_role_id; }
			set
			{
				m_isChanged |= ( m_phx_role_id != value ); 
				m_phx_role_id = value;
			}

		}
			
		public IList<PhxRoleUserEntity> PhxRolesUsersList
		{
			get
			{
				return m_PhxRolesUsersList;
			}
			set
			{
				m_PhxRolesUsersList = value;
			}
		}

        public IList<PhxPrivilegeRoleEntity> PhxPrivilegeRoleList
		{
			get
			{
                return m_privilege_role_list;
			}
			set
			{
                m_privilege_role_list = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Name
		{
			get { return m_role_name; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for RoleName", value, "null");
				
				if(  value.Length > 200)
					throw new ArgumentOutOfRangeException("Invalid value for RoleName", value, value.ToString());
				
				m_isChanged |= (m_role_name != value); m_role_name = value;
			}
		}
			
		/// <summary>
		/// Código del Rol. Para no estar pendiente del ID ya que es identity
		/// </summary>
		public string Code
		{
			get { return m_role_code; }

			set	
			{	
				/*if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for RoleCode", value, "null");*/

                if (value != null && value.Length > 20)
					throw new ArgumentOutOfRangeException("Invalid value for RoleCode", value, value.ToString());
				
				m_isChanged |= (m_role_code != value); m_role_code = value;
			}
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
	
        public override string Key
        {
            get
            {
                return m_phx_role_id.ToString();
            }
            set
            {
                m_phx_role_id = Convert.ToInt32(value);
            }
        }
    }
}
