/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class PhxRoleUserEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_phx_role_usr_id; 
		private PhxRoleEntity m_phx_role_id; 
		private PhxUserEntity m_phx_user_id; 		
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public PhxRoleUserEntity()
		{
			m_phx_role_usr_id = 0; 
			m_phx_role_id = new PhxRoleEntity(); 
			m_phx_user_id = new PhxUserEntity(); 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public PhxRoleUserEntity(
			int phx_role_usr_id, 
			PhxRoleEntity phx_role_id, 
			PhxUserEntity phx_user_id)
			: this()
		{
			m_phx_role_usr_id = phx_role_usr_id;
			m_phx_role_id = phx_role_id;
			m_phx_user_id = phx_user_id;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_phx_role_usr_id; }
			set
			{
				m_isChanged |= ( m_phx_role_usr_id != value ); 
				m_phx_role_usr_id = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public PhxRoleEntity PhxRole
		{
			get { return m_phx_role_id; }
			set
			{
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for PhxRoleId", value, "null");

				m_isChanged |= ( m_phx_role_id != value ); 
				m_phx_role_id = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public PhxUserEntity PhxUser
		{
			get { return m_phx_user_id; }
			set
			{
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for PhxUserId", value, "null");

				m_isChanged |= ( m_phx_user_id != value ); 
				m_phx_user_id = value;
			}

		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
        public override string Key
        {
            get
            {
                return m_phx_role_usr_id.ToString();
            }
            set
            {
                m_phx_role_usr_id = Convert.ToInt32(value);
            }
        }
    }
}
