/*
insert license info here
*/
using System;
using System.Collections;
using System.Collections.Generic;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class PhxUserEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_phx_user_id; 
		private IList<PhxUserGroupEntity> m_PhxUsersGroupsList;
        private IList<FollowupRequestGroupUserEntity> m_PhxUsersFollowupGroupsList; 
		private IList<RequestEntity> m_RequestsList;
		private IList<RequestEntity> m_RequestsListAuth1; 
		private IList<RequestEntity> m_RequestsListAuth2; 
		private IList<RqstGrpDelegEntity> m_RqstGrpsDelegListAuth1; 
		private IList<RqstGrpDelegEntity> m_RqstGrpsDelegListAuth2; 
		private IList<RqstGrpPwdEntity> m_RqstGrpsPwdsListAuth1; 
		private IList<RqstGrpPwdEntity> m_RqstGrpsPwdsListAuth2; 
		private IList<PhxRoleUserEntity> m_PhxRolesUsersList; 
		private string m_username; 
		private string m_fullname; 
		private string m_user_domain; 
		private string m_user_email; 
		private Nullable<DateTime> m_creation_date; 
		private Nullable<DateTime> m_delete_date;
        private string m_file_number;
        private string m_relation_type;
        private string m_branch;
        private string m_function;
        private string m_building_adress;
        private string m_building_floor;
        private string m_extension_number;
        private bool m_active;
        private PhxUserSuperiorEntity m_phx_superior;
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public PhxUserEntity()
		{
			m_phx_user_id = 0; 
			m_PhxUsersGroupsList = new List<PhxUserGroupEntity>();
            m_PhxUsersFollowupGroupsList = new List<FollowupRequestGroupUserEntity>(); 
			m_RequestsList = new List<RequestEntity>(); 
			m_RequestsListAuth1 = new List<RequestEntity>(); 
			m_RequestsListAuth2 = new List<RequestEntity>(); 
			m_RqstGrpsPwdsListAuth1 = new List<RqstGrpPwdEntity>(); 
			m_RqstGrpsPwdsListAuth2 = new List<RqstGrpPwdEntity>(); 
			m_RqstGrpsDelegListAuth1 = new List<RqstGrpDelegEntity>(); 
			m_RqstGrpsDelegListAuth2 = new List<RqstGrpDelegEntity>(); 
			m_PhxRolesUsersList = new List<PhxRoleUserEntity>(); 
			m_username = String.Empty; 
			m_fullname = String.Empty; 
			m_user_domain = String.Empty; 
			m_user_email = String.Empty;
            m_phx_superior = null;
			//m_creation_date = Nullable<DateTime>.Default; 
			//m_delete_date = DateTime.MinValue; 
			//m_delete_date = Nullable<DateTime>.Default; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public PhxUserEntity(
			int phx_user_id, 
			string username, 
			string fullname, 
			DateTime creation_date)
			: this()
		{
			m_phx_user_id = phx_user_id;
			m_username = username;
			m_fullname = fullname;
			m_user_domain = String.Empty;
			m_user_email = String.Empty;
			m_creation_date = creation_date;
            m_active = true;
			//m_delete_date = DateTime.MinValue;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_phx_user_id; }
			set
			{
				m_isChanged |= ( m_phx_user_id != value ); 
				m_phx_user_id = value;
			}

		}
			
		public IList<PhxRoleUserEntity> PhxRolesUsersList
		{
			get
			{
				return m_PhxRolesUsersList;
			}
			set
			{
				m_PhxRolesUsersList = value;
			}
		}

		public IList<PhxUserGroupEntity> PhxUsersGroupsList
		{
			get
			{
				return m_PhxUsersGroupsList;
			}
			set
			{
				m_PhxUsersGroupsList = value;
			}
		}

        public IList<FollowupRequestGroupUserEntity> PhxUsersFollowupGroupsList
		{
			get
			{
                return m_PhxUsersFollowupGroupsList;
			}
			set
			{
                m_PhxUsersFollowupGroupsList = value;
			}
		}
		public IList<RequestEntity> RequestsList
		{
			get
			{
				return m_RequestsList;
			}
			set
			{
				m_RequestsList = value;
			}
		}

		public IList<RequestEntity> RequestsListAuth1
		{
			get
			{
				return m_RequestsListAuth1;
			}
			set
			{
				m_RequestsListAuth1 = value;
			}
		}

		public IList<RequestEntity> RequestsListAuth2
		{
			get
			{
				return m_RequestsListAuth2;
			}
			set
			{
				m_RequestsListAuth2 = value;
			}
		}

		public IList<RqstGrpDelegEntity> RqstGrpsDelegListAuth1
		{
			get
			{
				return m_RqstGrpsDelegListAuth1;
			}
			set
			{
				m_RqstGrpsDelegListAuth1 = value;
			}
		}

		public IList<RqstGrpDelegEntity> RqstGrpsDelegListAuth2
		{
			get
			{
				return m_RqstGrpsDelegListAuth2;
			}
			set
			{
				m_RqstGrpsDelegListAuth2 = value;
			}
		}
		
		public IList<RqstGrpPwdEntity> RqstGrpsPwdsListAuth1
		{
			get
			{
				return m_RqstGrpsPwdsListAuth1;
			}
			set
			{
				m_RqstGrpsPwdsListAuth1 = value;
			}
		}
		
		public IList<RqstGrpPwdEntity> RqstGrpsPwdsListAuth2
		{
			get
			{
				return m_RqstGrpsPwdsListAuth2;
			}
			set
			{
				m_RqstGrpsPwdsListAuth2 = value;
			}
		}
        public PhxUserSuperiorEntity PhxUserSuperior
        {
            get
            {
                return m_phx_superior;
            }
            set
            {
                //m_isChanged |= (m_phx_superior != value);
                m_phx_superior = value;
            }
        }
		/// <summary>
		/// nombre de usuario. En un principio sería el usuario del dominio
		/// </summary>
		public string Username
		{
			get { return m_username; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for Username", value, "null");
				
				if(  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for Username", value, value.ToString());
				
				m_isChanged |= (m_username != value); m_username = value;
			}
		}
			
		/// <summary>
		/// nombre completo del usuario
		/// </summary>
		public string Fullname
		{
			get { return m_fullname; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for Fullname", value, "null");
				
				if(  value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for Fullname", value, value.ToString());
				
				m_isChanged |= (m_fullname != value); m_fullname = value;
			}
		}
			
		/// <summary>
		/// Dominio al cual pertenece el usuario. El nombre del dominio será en formato NT Domain
		/// </summary>
        public string Domain
		{
			get { return m_user_domain; }

			set	
			{	
				if(  value != null &&  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for UserDomain", value, value.ToString());
				
				m_isChanged |= (m_user_domain != value); m_user_domain = value;
			}
		}
			
		/// <summary>
		/// Mail del usuario adonde le llegarán las notificaciones
		/// </summary>
		public string Email
		{
			get { return m_user_email; }

			set	
			{	
				if(  value != null &&  value.Length > 150)
					throw new ArgumentOutOfRangeException("Invalid value for UserEmail", value, value.ToString());
				
				m_isChanged |= (m_user_email != value); m_user_email = value;
			}
		}
        /// <summary>
        /// Indica si el usuario está activo para usar el sistema
        /// </summary>
		public bool Active
		{
            get { return m_active; }
			set
			{
                m_isChanged |= (m_active != value);
                m_active = value;
			}

		}

		/// <summary>
		/// 
		/// </summary>
		public Nullable<DateTime> CreationDate
		{
			get { return m_creation_date; }
			set
			{
				m_isChanged |= ( m_creation_date != value ); 
				m_creation_date = value;
			}

		}
			
		/// <summary>
		/// fecha de baja
		/// </summary>
		public Nullable<DateTime> DeleteDate
		{
			get { return m_delete_date; }
			set
			{
				m_isChanged |= ( m_delete_date != value ); 
				m_delete_date = value;
			}

		}

        public string FileNumber
        {
            get { return m_file_number; }

            set
            {
                if (value != null && value.Length > 10)
                    throw new ArgumentOutOfRangeException("Invalid value for FileNumber", value, value.ToString());

                m_isChanged |= (m_file_number != value); m_file_number = value;
            }
        }
        /// <summary>
        /// relacion laboral - I=interno - E=Externo - P=Proveedor
        /// </summary>
        public string RelationType
        {
            get { return m_relation_type; }

            set
            {
                if (value != null && value.Length > 1)
                    throw new ArgumentOutOfRangeException("Invalid value for RelationType", value, value.ToString());

                m_isChanged |= (m_relation_type != value); m_relation_type = value;
            }
        }
        public string Branch
        {
            get { return m_branch; }

            set
            {
                if (value != null && value.Length > 100)
                    throw new ArgumentOutOfRangeException("Invalid value for Branch", value, value.ToString());

                m_isChanged |= (m_branch != value); m_branch = value;
            }
        }
        public string Function
        {
            get { return m_function; }

            set
            {
                if (value != null && value.Length > 50)
                    throw new ArgumentOutOfRangeException("Invalid value for Function", value, value.ToString());

                m_isChanged |= (m_function != value); m_function = value;
            }
        }
        public string BuildingAdress
        {
            get { return m_building_adress; }

            set
            {
                if (value != null && value.Length > 50)
                    throw new ArgumentOutOfRangeException("Invalid value for BuildingAdress", value, value.ToString());

                m_isChanged |= (m_building_adress != value); m_building_adress = value;
            }
        }
        public string BuildingFloor
        {
            get { return m_building_floor; }

            set
            {
                if (value != null && value.Length > 5)
                    throw new ArgumentOutOfRangeException("Invalid value for BuildingFloor", value, value.ToString());

                m_isChanged |= (m_building_floor != value); m_building_floor = value;
            }
        }
        public string ExtensionNumber
        {
            get { return m_extension_number; }

            set
            {
                if (value != null && value.Length > 5)
                    throw new ArgumentOutOfRangeException("Invalid value for ExtensionNumber", value, value.ToString());

                m_isChanged |= (m_extension_number != value); m_extension_number = value;
            }
        }
	
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}

        #endregion
        public override string Key
        {
            get
            {
                return m_phx_user_id.ToString();
            }
            set
            {
                m_phx_user_id = Convert.ToInt32(value);
            }
        }
        public override string ToString()
        {
            return Fullname;
        }
	}
}
