/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
    public sealed class PhxVersionEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_phx_version_id;
        private string m_version;
        private DateTime m_implementation_date;
        #endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public PhxVersionEntity()
		{
			m_phx_version_id = 0; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_phx_version_id; }
			set
			{
				m_isChanged |= ( m_phx_version_id != value ); 
				m_phx_version_id = value;
			}

		}
			

		/// <summary>
		/// 
		/// </summary>
		public string Version
		{
            get { return m_version; }

			set	
			{	
				if( value == null )
                    throw new ArgumentOutOfRangeException("Null value not allowed for Version", value, "null");
				
				if(  value.Length > 20)
                    throw new ArgumentOutOfRangeException("Invalid value for Version", value, value.ToString());

                m_isChanged |= (m_version != value); 
                m_version = value;
			}
		}

        public DateTime FechaImplementacion
		{
			get { return m_implementation_date; }
			set
			{
                m_isChanged |= (m_implementation_date != value);
                m_implementation_date = value;
			}

		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
		
		#endregion 
	
        public override string Key
        {
            get
            {
                return this.m_phx_version_id.ToString();
            }
            set
            {
                this.m_phx_version_id = Convert.ToInt32(value);
            }
        }
        
        public override string ToString()
        {
            return m_version;
        }
    }
}
