/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
    public sealed class PwdLockTypeEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_pwd_lock_type_id; 
		private IList m_UsersPasswordsList; 
		private string m_pwd_lock_type_code; 
		private string m_pwd_lock_type_desc; 		
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public PwdLockTypeEntity()
		{
			m_pwd_lock_type_id = 0; 
			m_UsersPasswordsList = new ArrayList(); 
			m_pwd_lock_type_code = String.Empty; 
			m_pwd_lock_type_desc = String.Empty; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public PwdLockTypeEntity(
			int pwd_lock_type_id, 
			string pwd_lock_type_code)
			: this()
		{
			m_pwd_lock_type_id = pwd_lock_type_id;
			m_pwd_lock_type_code = pwd_lock_type_code;
			m_pwd_lock_type_desc = String.Empty;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_pwd_lock_type_id; }
			set
			{
				m_isChanged |= ( m_pwd_lock_type_id != value ); 
				m_pwd_lock_type_id = value;
			}

		}
			
		public IList UsersPasswordsList
		{
			get
			{
				return m_UsersPasswordsList;
			}
			set
			{
				m_UsersPasswordsList = value;
			}
		}

		/// <summary>
		/// Código interno del tipo de lockeo
		/// </summary>
		public string Code
		{
			get { return m_pwd_lock_type_code; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for PwdLockTypeCode", value, "null");
				
				if(  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for PwdLockTypeCode", value, value.ToString());
				
				m_isChanged |= (m_pwd_lock_type_code != value); m_pwd_lock_type_code = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>
		public string Desc
		{
			get { return m_pwd_lock_type_desc; }

			set	
			{	
				if(  value != null &&  value.Length > 150)
					throw new ArgumentOutOfRangeException("Invalid value for PwdLockTypeDesc", value, value.ToString());
				
				m_isChanged |= (m_pwd_lock_type_desc != value); m_pwd_lock_type_desc = value;
			}
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
	
        public override string Key
        {
            get
            {
                return m_pwd_lock_type_id.ToString();
            }
            set
            {
                m_pwd_lock_type_id = Convert.ToInt32(value);
            }
        }
    }
}
