/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class RequestStateEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_rqst_state_id; 
		private IList m_RequestsList; 
		private string m_rqst_state_desc; 		
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public RequestStateEntity()
		{
			m_rqst_state_id = 0; 
			m_RequestsList = new ArrayList(); 
			m_rqst_state_desc = String.Empty; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public RequestStateEntity(
			int rqst_state_id, 
			string rqst_state_desc)
			: this()
		{
			m_rqst_state_id = rqst_state_id;
			m_rqst_state_desc = rqst_state_desc;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_rqst_state_id; }
			set
			{
				m_isChanged |= ( m_rqst_state_id != value ); 
				m_rqst_state_id = value;
			}

		}
			
		public IList RequestsList
		{
			get
			{
				return m_RequestsList;
			}
			set
			{
				m_RequestsList = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string RqstStateDesc
		{
			get { return m_rqst_state_desc; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for RqstStateDesc", value, "null");
				
				if(  value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for RqstStateDesc", value, value.ToString());
				
				m_isChanged |= (m_rqst_state_desc != value); m_rqst_state_desc = value;
			}
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
        public override string Key
        {
            get
            {
                return m_rqst_state_id.ToString();
            }
            set
            {
                m_rqst_state_id = Convert.ToInt32(value);
            }
        }

        public override string ToString()
        {
            return m_rqst_state_desc;
        }
    }
}
