/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
    public sealed class RequestNoteEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_request_note_id;
        private RequestEntity m_request_id; 
		private PhxUserEntity m_phx_user_id; 
		private DateTime m_request_note_date; 
		private string m_request_note_descrip; 		
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public RequestNoteEntity()
		{
			m_request_note_id = 0;
            m_request_id = new RequestEntity();
            m_phx_user_id = new PhxUserEntity(); 
			m_request_note_date = DateTime.MinValue; 
			m_request_note_descrip = String.Empty; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public RequestNoteEntity(
            RequestEntity request_id,
            PhxUserEntity phx_user_id, 
			DateTime request_note_date, 
			string request_note_descrip)
			: this()
		{
			m_request_id = request_id;
			m_phx_user_id = phx_user_id;
			m_request_note_date = request_note_date;
			m_request_note_descrip = request_note_descrip;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_request_note_id; }
			set
			{
				m_isChanged |= ( m_request_note_id != value ); 
				m_request_note_id = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public RequestEntity Request
		{
			get { return m_request_id; }
			set
			{
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for Request", value, "null");

				m_isChanged |= ( m_request_id != value ); 
				m_request_id = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public PhxUserEntity PhxUser
		{
			get { return m_phx_user_id; }
			set
			{
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for PhxUser", value, "null");

				m_isChanged |= ( m_phx_user_id != value ); 
				m_phx_user_id = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public DateTime RequestNoteDate
		{
			get { return m_request_note_date; }
			set
			{
				m_isChanged |= ( m_request_note_date != value ); 
				m_request_note_date = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public string Descrip
		{
			get { return m_request_note_descrip; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for Descrip", value, "null");
				
				if(  value.Length > 200)
					throw new ArgumentOutOfRangeException("Invalid value for Descrip", value, value.ToString());
				
				m_isChanged |= (m_request_note_descrip != value); m_request_note_descrip = value;
			}
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
	
        public override string Key
        {
            get
            {
                return m_request_note_id.ToString();
            }
            set
            {
                m_request_note_id = Convert.ToInt32(value);
            }
        }
    }
}
