/*
insert license info here
*/
using System;
using System.Collections;
//using Nullables;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public class RequestEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_request_id; 
		private IList m_DelegationRequestsList; 
		private IList m_PasswordsRequestsList; 
		private PhxUserEntity m_rqst_user_id; 
		private DateTime m_request_date; 
		private PhxUserEntity m_auth1_usr_id; 
		private Nullable<DateTime> m_auth1_date; 
		private PhxUserEntity m_auth2_usr_id; 
		private Nullable<DateTime> m_auth2_date; 
		private RequestStateEntity m_rqst_state_id; 
		private int m_hours_requested; 
		private int m_hours_given; 
		private string m_request_desc; 
		private string m_auth_desc;
        private Nullable<DateTime> m_expiration_date;
        private bool m_expirada_sin_visualizar;
        private string m_unit_requested;
        private string m_unit_given;
        private Nullable<DateTime> m_return_date;
        private string m_return_note;
        private PhxUserEntity m_return_user;
        private Nullable<DateTime> m_close_date;
        private string m_close_note;
        private PhxUserEntity m_close_user; 

        #endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public RequestEntity()
		{
			m_request_id = 0; 
			m_DelegationRequestsList = new ArrayList(); 
			m_PasswordsRequestsList = new ArrayList(); 
			m_rqst_user_id = new PhxUserEntity(); 
			m_request_date = DateTime.MinValue; 
			m_auth1_usr_id = null; //new PhxUsers(); 
			//m_auth1_date = Nullable<DateTime>.Default; 
			m_auth2_usr_id = null; //new PhxUsers(); 
			//m_auth2_date = Nullable<DateTime>.Default; 
			m_rqst_state_id = new RequestStateEntity(); 
			m_hours_requested = 0; 
			m_hours_given = 0; 
			m_request_desc = String.Empty; 
			m_auth_desc = String.Empty; 
			m_expiration_date = null;
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public RequestEntity(
			int request_id, 
			PhxUserEntity rqst_user_id, 
			DateTime request_date, 
			RequestStateEntity rqst_state_id)
			: this()
		{
			m_request_id = request_id;
			m_rqst_user_id = rqst_user_id;
			m_request_date = request_date;
			m_auth1_usr_id = null;
			//m_auth1_date = DateTime.MinValue;
			m_auth2_usr_id = null;
			//m_auth2_date = DateTime.MinValue;
			m_rqst_state_id = rqst_state_id;
			m_hours_requested = 0;
			m_hours_given = 0;
			m_request_desc = String.Empty;
			m_auth_desc = String.Empty;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
        public int Id
		{
			get { return m_request_id; }
			set
			{
				m_isChanged |= ( m_request_id != value ); 
				m_request_id = value;
			}
		}
			
		public IList DelegationRequestsList
		{
			get
			{
				return m_DelegationRequestsList;
			}
			set
			{
				m_DelegationRequestsList = value;
			}
		}

		public IList PasswordsRequestsList
		{
			get
			{
				return m_PasswordsRequestsList;
			}
			set
			{
				m_PasswordsRequestsList = value;
			}
		}

		/// <summary>
		/// Usuario que realizó la consulta
		/// </summary>
		public PhxUserEntity RqstUser
		{
			get { return m_rqst_user_id; }
			set
			{
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for RqstUserId", value, "null");

				m_isChanged |= ( m_rqst_user_id != value ); 
				m_rqst_user_id = value;
			}

		}
			
		/// <summary>
		/// Fecha en que se hizo la solicitud
		/// </summary>
		public DateTime RequestDate
		{
			get { return m_request_date; }
			set
			{
				m_isChanged |= ( m_request_date != value ); 
				m_request_date = value;
			}

		}
			
		/// <summary>
		/// Usuario Autorizador 1
		/// </summary>
		public PhxUserEntity Auth1Usr
		{
			get { return m_auth1_usr_id; }
			set
			{
				m_isChanged |= ( m_auth1_usr_id != value ); 
				m_auth1_usr_id = value;
			}

		}
			
		/// <summary>
		/// fecha en que el autorizador 1 autorizó
		/// </summary>
		public Nullable<DateTime> Auth1Date
		{
			get { return m_auth1_date; }
			set
			{
				m_isChanged |= ( m_auth1_date != value ); 
				m_auth1_date = value;
			}

		}
			
		/// <summary>
		/// Usuario Autorizador 2
		/// </summary>
		public PhxUserEntity Auth2Usr
		{
			get { return m_auth2_usr_id; }
			set
			{
				m_isChanged |= ( m_auth2_usr_id != value ); 
				m_auth2_usr_id = value;
			}

		}
			
		/// <summary>
		/// fecha en que el autorizador 2 autorizó
		/// </summary>
		public Nullable<DateTime> Auth2Date
		{
			get { return m_auth2_date; }
			set
			{
				m_isChanged |= ( m_auth2_date != value ); 
				m_auth2_date = value;
			}

		}
			
		/// <summary>
		/// Estado en que se encuentra la solicitud
		/// </summary>
		public RequestStateEntity RqstState
		{
			get { return m_rqst_state_id; }
			set
			{
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for RqstStateId", value, "null");

				m_isChanged |= ( m_rqst_state_id != value ); 
				m_rqst_state_id = value;
			}

		}
			
		/// <summary>
		/// cantidad de horas solicitadas
		/// </summary>
		public int HoursRequested
		{
			get { return m_hours_requested; }
			set
			{
				m_isChanged |= ( m_hours_requested != value ); 
				m_hours_requested = value;
			}

		}
			
		/// <summary>
		/// Cantidad de horas concedidas
		/// </summary>
		public int HoursGiven
		{
			get { return m_hours_given; }
			set
			{
				m_isChanged |= ( m_hours_given != value ); 
				m_hours_given = value;
			}

		}
			
		/// <summary>
		/// Descripción de la solicitud
		/// </summary>
		public string RequestDesc
		{
			get { return m_request_desc; }

			set	
			{	
				if(  value != null &&  value.Length > 500)
					throw new ArgumentOutOfRangeException("Invalid value for RequestDesc", value, value.ToString());
				
				m_isChanged |= (m_request_desc != value); m_request_desc = value;
			}
		}
			
		/// <summary>
		/// Motivo del rechazo
		/// </summary>
		public string AuthDesc
		{
			get { return m_auth_desc; }

			set	
			{	
				if(  value != null &&  value.Length > 500)
					throw new ArgumentOutOfRangeException("Invalid value for AuthDesc", value, value.ToString());
				
				m_isChanged |= (m_auth_desc != value); m_auth_desc = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>
		public Nullable<DateTime> ExpirationDate
		{
			get { return m_expiration_date; }
			set
			{
				m_isChanged |= ( m_expiration_date != value ); 
				m_expiration_date = value;
			}

		}

        public bool ExpiradaSinVisualizar
		{
            get { return m_expirada_sin_visualizar; }
			set
			{
				m_isChanged |= ( m_expirada_sin_visualizar != value );
                m_expirada_sin_visualizar = value;
			}

		}

		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}

        public string UnitRequested
        {
            get { return m_unit_requested; }
            set
            {
                if (value != null && value.Length > 1)
                    throw new ArgumentOutOfRangeException("Invalid value for UnitRequested", value, value.ToString());

                m_isChanged |= (m_unit_requested != value); m_unit_requested = value;
            }
        }
        public string UnitGiven
        {
            get { return m_unit_given; }
            set
            {
                if (value != null && value.Length > 1)
                    throw new ArgumentOutOfRangeException("Invalid value for UnitGiven", value, value.ToString());

                m_isChanged |= (m_unit_given != value); m_unit_given = value;
            }
        }

        public Nullable<DateTime> ReturnDate 
        {
            get { return m_return_date;}
            set 
            {
                m_isChanged |= (m_return_date != value);
                m_return_date = value;
            }

        }
        public string ReturnNote
        {
            get { return m_return_note; }
            set
            {
                if (value != null && value.Length > 200)
                    throw new ArgumentOutOfRangeException("Invalid value for UnitGiven", value, value.ToString());

                m_isChanged |= (m_return_note != value); m_return_note = value;
            }
        }
        public PhxUserEntity ReturnUser
        {
            get { return m_return_user; }
            set
            {
                m_isChanged |= (m_return_user != value);
                m_return_user = value;
            }
        }

        /// <summary>
        /// Fecha en la que se cierra una contraseña
        /// </summary>
        public Nullable<DateTime> CloseDate
        {
            get { return m_close_date; }
            set
            {
                m_isChanged |= (m_close_date != value);
                m_close_date = value;
            }

        }
        /// <summary>
        /// Nota asociada al cierre de una contraseña
        /// </summary>
        public string CloseNote
        {
            get { return m_close_note; }
            set
            {
                if (value != null && value.Length > 200)
                    throw new ArgumentOutOfRangeException("Invalid value for UnitGiven", value, value.ToString());

                m_isChanged |= (m_close_note != value); m_close_note = value;
            }
        }
        /// <summary>
        /// Usuario administrador que efectuó el cierre de una contraseña
        /// </summary>
        public PhxUserEntity CloseUser
        {
            get { return m_close_user; }
            set
            {
                m_isChanged |= (m_close_user != value);
                m_close_user = value;
            }
        }
           
        #endregion 

        public override string Key
        {
            get
            {
                return m_request_id.ToString();
            }
            set
            {
                m_request_id = Convert.ToInt32(value);
            }
        }

        public string RqstUsrFullName
        {
            get { return RqstUser.Fullname; }
        }
    }
}
