/*
insert license info here
*/
using System;
using System.Collections;
using System.Collections.Generic;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class RequestGroupEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_rqst_grp_id; 
		private IList<PhxUserGroupEntity> m_PhxUsersGroupsList; 
		private IList<RqstGrpDelegEntity> m_RqstGrpsDelegList; 
		private IList<RqstGrpPwdEntity> m_RqstGrpsPwdsList;
		private string m_rqst_grp_name;
        private bool m_rqst_grp_user; 
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public RequestGroupEntity()
		{
			m_rqst_grp_id = 0; 
			m_PhxUsersGroupsList = new List<PhxUserGroupEntity>(); 
			m_RqstGrpsDelegList = new List<RqstGrpDelegEntity>(); 
			m_RqstGrpsPwdsList = new List<RqstGrpPwdEntity>(); 
			m_rqst_grp_name = String.Empty; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public RequestGroupEntity(
			int rqst_grp_id, 
			string rqst_grp_name)
			: this()
		{
			m_rqst_grp_id = rqst_grp_id;
			m_rqst_grp_name = rqst_grp_name;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_rqst_grp_id; }
			set
			{
				m_isChanged |= ( m_rqst_grp_id != value ); 
				m_rqst_grp_id = value;
			}

		}
			
		public IList<PhxUserGroupEntity> PhxUsersGroupsList
		{
			get
			{
				return m_PhxUsersGroupsList;
			}
			set
			{
				m_PhxUsersGroupsList = value;
			}
		}

		public IList<RqstGrpDelegEntity> RqstGrpsDelegList
		{
			get
			{
				return m_RqstGrpsDelegList;
			}
			set
			{
				m_RqstGrpsDelegList = value;
			}
		}

		public IList<RqstGrpPwdEntity> RqstGrpsPwdsList
		{
			get
			{
				return m_RqstGrpsPwdsList;
			}
			set
			{
				m_RqstGrpsPwdsList = value;
			}
		}

		/// <summary>
		/// Nombre del grupo
		/// </summary>
		public string RqstGrpName
		{
			get { return m_rqst_grp_name; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for RqstGrpName", value, "null");
				
				if(  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for RqstGrpName", value, value.ToString());
				
				m_isChanged |= (m_rqst_grp_name != value); m_rqst_grp_name = value;
			}
		}
        public string RqstGrpNameInactTxt
        {
            get
            {
                string GrpName = m_rqst_grp_name;
                if (!this.Active)
                {
                    GrpName += " (inactivo)";
                }
                return GrpName;
            }
        }
        public bool Active
        {
            get { return m_rqst_grp_user; }
            set
            {
                m_isChanged |= (m_rqst_grp_user != value);
                m_rqst_grp_user = value;
            }

        }
	
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
        public override string Key
        {
            get
            {
                return m_rqst_grp_id.ToString();
            }
            set
            {
                m_rqst_grp_id = Convert.ToInt32(value);
            }
        }
    }
}
