/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class RqstGrpPwdEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_pwdrqst_grp_pwd_id; 
		private RequestGroupEntity m_rqst_grp_id; 
		private UserPasswordEntity m_user_password_id; 
		private PhxUserEntity m_auth1_usr_id; 
		private PhxUserEntity m_auth2_usr_id; 		
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public RqstGrpPwdEntity()
		{
			m_pwdrqst_grp_pwd_id = 0; 
			m_rqst_grp_id = new RequestGroupEntity(); 
			m_user_password_id = new UserPasswordEntity(); 
			m_auth1_usr_id = new PhxUserEntity(); 
			m_auth2_usr_id = new PhxUserEntity(); 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public RqstGrpPwdEntity(
			int pwdrqst_grp_pwd_id, 
			RequestGroupEntity rqst_grp_id, 
			UserPasswordEntity user_password_id)
			: this()
		{
			m_pwdrqst_grp_pwd_id = pwdrqst_grp_pwd_id;
			m_rqst_grp_id = rqst_grp_id;
			m_user_password_id = user_password_id;
			m_auth1_usr_id = null;
			m_auth2_usr_id = null;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_pwdrqst_grp_pwd_id; }
			set
			{
				m_isChanged |= ( m_pwdrqst_grp_pwd_id != value ); 
				m_pwdrqst_grp_pwd_id = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public RequestGroupEntity RqstGrp
		{
			get { return m_rqst_grp_id; }
			set
			{
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for RqstGrpId", value, "null");

				m_isChanged |= ( m_rqst_grp_id != value ); 
				m_rqst_grp_id = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public UserPasswordEntity UserPassword
		{
			get { return m_user_password_id; }
			set
			{
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for UserPasswordId", value, "null");

				m_isChanged |= ( m_user_password_id != value ); 
				m_user_password_id = value;
			}

		}
			
		/// <summary>
		/// Usuario autorizador 1
		/// </summary>
		public PhxUserEntity Auth1Usr
		{
			get { return m_auth1_usr_id; }
			set
			{
				m_isChanged |= ( m_auth1_usr_id != value ); 
				m_auth1_usr_id = value;
			}

		}
			
		/// <summary>
		/// Usuario autorizador 2
		/// </summary>
		public PhxUserEntity Auth2Usr
		{
			get { return m_auth2_usr_id; }
			set
			{
				m_isChanged |= ( m_auth2_usr_id != value ); 
				m_auth2_usr_id = value;
			}

		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
	
        public override string Key
        {
            get
            {
                return m_pwdrqst_grp_pwd_id.ToString();
            }
            set
            {
                m_pwdrqst_grp_pwd_id = Convert.ToInt32(value);
            }
        }
    }
}
