/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
    /// <summary>
    ///	Generated by MyGeneration using the NHibernate Object Mapping template
    /// </summary>
    [Serializable]
    public sealed class UnixUserEntity : UserEntity
    {

        #region Private Members
        private bool m_isChanged;
        public string m_Server_Name;

        private UnixEntity m_unx_id;
        #endregion

        #region Default ( Empty ) Class Constuctor
        /// <summary>
        /// default constructor
        /// </summary>
        public UnixUserEntity()
        {
            m_unx_id = new UnixEntity();
        }
        #endregion // End of Default ( Empty ) Class Constuctor

        #region Required Fields Only Constructor
        /// <summary>
        /// required (not null) fields only constructor
        /// </summary>
        public UnixUserEntity(
            UnixEntity unx_id)
            : this()
        {
            m_unx_id = unx_id;
        }
        #endregion // End Required Fields Only Constructor

        #region Public Properties

        /// <summary>
        /// 
        /// </summary>
        public UnixEntity Unix
        {
            get { return m_unx_id; }
            set
            {
                if (value == null)
                    throw new ArgumentOutOfRangeException("Null value not allowed for Unix", value, "null");

                m_isChanged |= (m_unx_id != value);
                m_unx_id = value;
            }

        }

        public string Server_Name
        {
            get { return m_Server_Name; }
            set { m_Server_Name = value; }
        }


        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public bool IsChanged
        {
            get { return m_isChanged; }
        }

        #endregion
    }
}
