/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
    public sealed class UnixEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_unx_id; 
		private IList m_UnixUsersList; 
		private string m_unx_server_name; 
		private Nullable<byte> m_unx_server_ip1;
        private Nullable<byte> m_unx_server_ip2;
        private Nullable<byte> m_unx_server_ip3;
        private Nullable<byte> m_unx_server_ip4; 
		private string m_unx_desc; 
		private string m_unx_ip;
        private bool m_active = true;
        #endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public UnixEntity()
		{
			m_unx_id = 0; 
			m_UnixUsersList = new ArrayList(); 
			m_unx_server_name = String.Empty; 
			m_unx_server_ip1 = new byte(); 
			m_unx_server_ip2 = new byte(); 
			m_unx_server_ip3 = new byte(); 
			m_unx_server_ip4 = new byte(); 
			m_unx_desc = String.Empty; 
			m_unx_ip = String.Empty; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public UnixEntity(
			string unx_server_name)
			: this()
		{
			m_unx_server_name = unx_server_name;
			m_unx_server_ip1 = null;
			m_unx_server_ip2 = null;
			m_unx_server_ip3 = null;
			m_unx_server_ip4 = null;
			m_unx_desc = String.Empty;
			m_unx_ip = String.Empty;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_unx_id; }
			set
			{
				m_isChanged |= ( m_unx_id != value ); 
				m_unx_id = value;
			}

		}
			
		public IList UnixUsersList
		{
			get
			{
				return m_UnixUsersList;
			}
			set
			{
				m_UnixUsersList = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string ServerName
		{
			get { return m_unx_server_name; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for ServerName", value, "null");
				
				if(  value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for ServerName", value, value.ToString());
				
				m_isChanged |= (m_unx_server_name != value); m_unx_server_name = value;
			}
		}
			
		/// <summary>
		/// Primer valor de la dir IP
		/// </summary>
        public Nullable<byte> Ip1
		{
			get { return m_unx_server_ip1; }

			set	
			{	
				if(  value != null &&  value > 255)
					throw new ArgumentOutOfRangeException("Invalid value for Ip1", value, value.ToString());
				
				m_isChanged |= (m_unx_server_ip1 != value); m_unx_server_ip1 = value;
			}

		}
			
		/// <summary>
		/// Segundo valor de la dir IP
		/// </summary>
        public Nullable<byte> Ip2
		{
			get { return m_unx_server_ip2; }

			set	
			{
                if (value != null && value > 255)
					throw new ArgumentOutOfRangeException("Invalid value for Ip2", value, value.ToString());
				
				m_isChanged |= (m_unx_server_ip2 != value); m_unx_server_ip2 = value;
			}

		}
			
		/// <summary>
		/// Tercer valor de la dir IP
		/// </summary>
        public Nullable<byte> Ip3
		{
			get { return m_unx_server_ip3; }

			set	
			{
                if (value != null && value > 255)
					throw new ArgumentOutOfRangeException("Invalid value for Ip3", value, value.ToString());
				
				m_isChanged |= (m_unx_server_ip3 != value); m_unx_server_ip3 = value;
			}

		}
			
		/// <summary>
		/// Cuarto  valor de la dir IP
		/// </summary>
        public Nullable<byte> Ip4
		{
			get { return m_unx_server_ip4; }

			set	
			{
                if (value != null && value > 255)
					throw new ArgumentOutOfRangeException("Invalid value for Ip4", value, value.ToString());
				
				m_isChanged |= (m_unx_server_ip4 != value); m_unx_server_ip4 = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public string Desc
		{
			get { return m_unx_desc; }

			set	
			{	
				if(  value != null &&  value.Length > 200)
					throw new ArgumentOutOfRangeException("Invalid value for Desc", value, value.ToString());
				
				m_isChanged |= (m_unx_desc != value); m_unx_desc = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>
		public string Ip
		{
			get { return m_unx_ip; }

			set	
			{	
				if(  value != null &&  value.Length > 15)
					throw new ArgumentOutOfRangeException("Invalid value for Ip", value, value.ToString());
				
				m_isChanged |= (m_unx_ip != value); m_unx_ip = value;
			}
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}

        public bool Active
        {
            get { return m_active; }
            set
            {
                m_isChanged |= (m_active != value);
                m_active = value;
            }

        }
        #endregion 
	
        public override string Key
        {
            get
            {
                return this.m_unx_id.ToString();
            }
            set
            {
                this.m_unx_id = Convert.ToInt32(value);
            }
        }
        
        public override string ToString()
        {
            return m_unx_server_name;
        }
    }
}
