/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
    public sealed class UserPasswordEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_user_password_id; 
		private IList m_PasswordsRequestsList; 
		private IList m_RqstGrpsPwdsList;
        private IList m_FollowupRqstGrpsPwdsList; 
		private IList m_UsersList; 
		private string m_password; 
		private bool m_static_pwd; 
		private Nullable<DateTime> m_d_next_change; 
		private Nullable<DateTime> m_d_last_change; 
		private decimal m_change_freq; 
		private string m_change_freq_unit; 
		private Nullable<DateTime> m_d_next_chk; 
		private Nullable<DateTime> m_d_last_chk; 
		private decimal m_chk_freq; 
		private string m_chk_freq_unit; 		
		private PwdLockTypeEntity m_pwd_lock_type_id; 		
		private bool m_chk_pwd; 		
		private Nullable<DateTime> m_d_in_use_until;
		private bool m_concurrent; 
        private bool m_ApplyRealUser = false;
        private string m_RealPassword = string.Empty;
        private bool m_checkeable; 

		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public UserPasswordEntity()
		{
			m_user_password_id = 0; 
			m_UsersList = new ArrayList(); 
			m_PasswordsRequestsList = new ArrayList(); 
			m_RqstGrpsPwdsList = new ArrayList();
            m_FollowupRqstGrpsPwdsList = new ArrayList(); 
			m_password = String.Empty; 
			m_static_pwd = false; 
			//m_d_next_change = DateTime.MinValue; 
			//m_d_next_change = NullableDateTime.Default;
			//m_d_last_change = DateTime.MinValue; 
			//m_d_last_change = NullableDateTime.Default;
			m_change_freq = 0; 
			m_change_freq_unit = String.Empty; 
			//m_d_next_chk = DateTime.MinValue; 
			//m_d_last_chk = DateTime.MinValue; 
			//m_d_next_chk = NullableDateTime.Default;
			//m_d_last_chk = NullableDateTime.Default;
			m_chk_freq = 0; 
			m_chk_freq_unit = String.Empty; 
			//m_pwd_lock_type_id = new PwdLockTypes(); 
			m_chk_pwd = false;
            m_concurrent = false;
			//m_d_in_use_until = NullableDateTime.Default;
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public UserPasswordEntity(
			int user_password_id, 
			bool static_pwd, 
			bool chk_pwd)
			: this()
		{
			m_user_password_id = user_password_id;
			m_password = String.Empty;
			m_static_pwd = static_pwd;
			m_d_next_change = DateTime.MinValue;
			m_d_last_change = DateTime.MinValue;
			m_change_freq = 0;
			m_change_freq_unit = String.Empty;
			m_d_next_chk = DateTime.MinValue;
			m_d_last_chk = DateTime.MinValue;
			m_chk_freq = 0;
			m_chk_freq_unit = String.Empty;
			m_pwd_lock_type_id = null;
			m_chk_pwd = chk_pwd;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties

        public bool ApplyRealUser 
        {
            get { return m_ApplyRealUser; }
            set { m_ApplyRealUser = value; }
        }

        public string RealPassword
        {
            get { return m_RealPassword; }
            set { m_RealPassword = value; }
        }

        /// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_user_password_id; }
			set
			{
				m_isChanged |= ( m_user_password_id != value ); 
				m_user_password_id = value;
			}

		}
		public IList UsersList
		{
			get
			{
				return m_UsersList;
			}
			set
			{
				m_UsersList = value;
			}
		}
		
		public IList PasswordsRequestsList
		{
			get
			{
				return m_PasswordsRequestsList;
			}
			set
			{
				m_PasswordsRequestsList = value;
			}
		}

		public IList RqstGrpsPwdsList
		{
			get
			{
				return m_RqstGrpsPwdsList;
			}
			set
			{
				m_RqstGrpsPwdsList = value;
			}
		}

        public IList FollowupRqstGrpsPwdsList
		{
			get
			{
                return m_FollowupRqstGrpsPwdsList;
			}
			set
			{
                m_FollowupRqstGrpsPwdsList = value;
			}
		}
		/// <summary>
		/// campo de contraseña pensado para encriptación de 448 bits (56 bytes o 112 chars hexa)
		/// </summary>
		public string Password
		{
			get { return m_password; }

			set	
			{	
				if(  value != null &&  value.Length > 550)
					throw new ArgumentOutOfRangeException("Invalid value for Password", value, value.ToString());
				
				m_isChanged |= (m_password != value); m_password = value;
			}
		}
			
		/// <summary>
		/// indica si la clave es estática (1: si - 0: no)
		/// </summary>
		public bool StaticPwd
		{
			get { return m_static_pwd; }
			set
			{
				m_isChanged |= ( m_static_pwd != value ); 
				m_static_pwd = value;
			}

		}
			
		/// <summary>
		/// indica la fecha en que se debe hacer le próximo cambio de la pwd
		/// </summary>
		public Nullable<DateTime> DNextChange
		{
			get { return m_d_next_change; }
			set
			{
				m_isChanged |= ( m_d_next_change != value ); 
				m_d_next_change = value;
			}

		}
			
		/// <summary>
		/// fecha en que se cambió el pwd por última vez
		/// </summary>
		public Nullable<DateTime> DLastChange
		{
			get { return m_d_last_change; }
			set
			{
				m_isChanged |= ( m_d_last_change != value ); 
				m_d_last_change = value;
			}

		}
			
		/// <summary>
		/// frecuencia de cambio. esta es la cantidad. luego se ve en el campo que indica la unidad de medida
		/// </summary>
		public decimal ChangeFreq
		{
			get { return m_change_freq; }
			set
			{
				m_isChanged |= ( m_change_freq != value ); 
				m_change_freq = value;
			}

		}
			
		/// <summary>
		/// unidad de medida de la frecuencia del cambio (H: hrs - D: días - W:semanas - M: meses - Y: años)
		/// </summary>
		public string ChangeFreqUnit
		{
			get { return m_change_freq_unit; }

			set	
			{	
				if(  value != null &&  value.Length > 1)
					throw new ArgumentOutOfRangeException("Invalid value for ChangeFreqUnit", value, value.ToString());
				
				m_isChanged |= (m_change_freq_unit != value); m_change_freq_unit = value;
			}
		}
			
		/// <summary>
		/// fecha en que se debe realizar el próximo chequee de no alteración de pwd
		/// </summary>
		public Nullable<DateTime> DNextChk
		{
			get { return m_d_next_chk; }
			set
			{
				m_isChanged |= ( m_d_next_chk != value ); 
				m_d_next_chk = value;
			}

		}
			
		/// <summary>
		/// fecha en que se chequeó por última vez la contraseña
		/// </summary>
		public Nullable<DateTime> DLastChk
		{
			get { return m_d_last_chk; }
			set
			{
				m_isChanged |= ( m_d_last_chk != value ); 
				m_d_last_chk = value;
			}

		}
			
		/// <summary>
		/// frecuencia de chequeo. esta es la cantidad. luego se ve en el campo que indica la unidad de medida
		/// </summary>
		public decimal ChkFreq
		{
			get { return m_chk_freq; }
			set
			{
				m_isChanged |= ( m_chk_freq != value ); 
				m_chk_freq = value;
			}

		}
			
		/// <summary>
		/// unidad de medida de la frecuencia de chequeo (H: hrs - D: días - W:semanas - M: meses - Y: años)
		/// </summary>
		public string ChkFreqUnit
		{
			get { return m_chk_freq_unit; }

			set	
			{	
				if(  value != null &&  value.Length > 1)
					throw new ArgumentOutOfRangeException("Invalid value for ChkFreqUnit", value, value.ToString());
				
				m_isChanged |= (m_chk_freq_unit != value); m_chk_freq_unit = value;
			}
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		/// <summary>
		/// id del tipo de lockeo que tiene la contraseña
		/// </summary>
        public PwdLockTypeEntity PwdLockType
		{
			get { return m_pwd_lock_type_id; }
			set
			{
				m_isChanged |= ( m_pwd_lock_type_id != value ); 
				m_pwd_lock_type_id = value;
			}

		}
		/// <summary>
		/// Indica si la contraseña debe ser chequeada
		/// </summary>
		public bool ChkPwd
		{
			get { return m_chk_pwd; }
			set
			{
				m_isChanged |= ( m_chk_pwd != value ); 
				m_chk_pwd = value;
			}

		}

		/// <summary>
		/// Fecha hasta que la contraseña está en uso por visualización. Lock type debe tener lockeo por contraseña en uso
		/// </summary>
		public Nullable<DateTime> DInUseUntil
		{
			get { return m_d_in_use_until; }
			set
			{
				m_isChanged |= ( m_d_in_use_until != value ); 
				m_d_in_use_until = value;
			}

		}
        public bool Concurrent
        {
            get { return m_concurrent; }
            set
            {
                m_isChanged |= (m_concurrent != value);
                m_concurrent = value;
            }
        }
        public bool Checkeable
        {
            get { return m_checkeable; }
            set
            {
                m_isChanged |= (m_checkeable != value);
                m_checkeable = value;
            }

        }
        #endregion 
	
        public override string Key
        {
            get
            {
                return m_user_password_id.ToString();
            }
            set
            {
                m_user_password_id = Convert.ToInt32(value);
            }
        }
    }
}
