/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public class UserEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_user_id; 
		//private IList m_WinDomainUsersList; 
		//private IList m_WinLocalUsersList; 
        private IList m_PwdChangesList;
		private string m_username; 
		private bool m_active_user; 
		private DateTime? m_modifying_date;
        private PhxUserEntity m_modifying_user;
		private UserTypeEntity m_user_type_id; 
		private UserPasswordEntity m_user_password_id;
        private string m_user_desc;
        private bool m_critical;
        /// Sacar cuando se encuentre el problema de los reportes
        /// </summary>
        private string m_User_RealPassword = string.Empty;
        public string User_RealPassword
        {
            get { return m_User_RealPassword; }
            set { m_User_RealPassword = value; }
        }
        #endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public UserEntity()
		{
			m_user_id = 0; 
			//m_WinDomainUsersList = new ArrayList(); 
			//m_WinLocalUsersList = new ArrayList(); 
            m_PwdChangesList = new ArrayList();
			m_username = String.Empty; 
			m_active_user = false; 
			m_user_type_id = new UserTypeEntity(); 
			m_user_password_id = new UserPasswordEntity();
            m_user_desc = String.Empty;
            m_critical = false;
        }
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public UserEntity(
			int user_id, 
			string username)
			: this()
		{
			m_user_id = user_id;
			m_username = username;
			m_active_user = false;
			m_user_type_id = null;
			m_user_password_id = null;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
        public int Id
		{
			get { return m_user_id; }
			set
			{
				m_isChanged |= ( m_user_id != value ); 
				m_user_id = value;
			}

		}

        public IList PwdChangesList
		{
			get
			{
                return m_PwdChangesList;
			}
			set
			{
                m_PwdChangesList = value;
			}
		}

		/*
		public IList WinDomainUsersList
		{
			get
			{
				return m_WinDomainUsersList;
			}
			set
			{
				m_WinDomainUsersList = value;
			}
		}

		public IList WinLocalUsersList
		{
			get
			{
				return m_WinLocalUsersList;
			}
			set
			{
				m_WinLocalUsersList = value;
			}
		}
		*/

		/// <summary>
		/// 
		/// </summary>
		public string Username
		{
			get { return m_username; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for Username", value, "null");
				
				if(  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for Username", value, value.ToString());
				
				m_isChanged |= (m_username != value); m_username = value;
			}
		}
			
		/// <summary>
		/// indica si esta cuenta está activa
		/// </summary>
		public bool ActiveUser
		{
			get { return m_active_user; }
			set
			{
				m_isChanged |= ( m_active_user != value ); 
				m_active_user = value;
			}

		}


        /// <summary>
        /// indica si este usuario está siendo modificado
        /// </summary>
        public DateTime? ModifyingDate
        {
            get { return m_modifying_date; }
            set
            {
                m_isChanged |= (m_modifying_date != value);
                m_modifying_date  = value;
            }

        }

        /// <summary>
        /// indica por qué usuario está siendo modificado
        /// </summary>
        public PhxUserEntity ModifyingUser
        {
            get { return m_modifying_user; }
            set
            {
                m_isChanged |= (m_modifying_user != value);
                m_modifying_user = value;
            }
        }


		public bool Critical
		{
            get { return m_critical; }
			set
			{
                m_isChanged |= (m_critical != value);
                m_critical = value;
			}

		}

		/// <summary>
        /// Indica el tipo de usuario (de dominio, de sql server, local de una workstation)
		/// </summary>
		public UserTypeEntity UserType
		{
			get { return m_user_type_id; }
			set
			{
				m_isChanged |= ( m_user_type_id != value ); 
				m_user_type_id = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public UserPasswordEntity UserPassword
		{
			get { return m_user_password_id; }
			set
			{
				m_isChanged |= ( m_user_password_id != value ); 
				m_user_password_id = value;
			}

		}
        /// <summary>
        /// Descripción del uso del usuario
        /// </summary>
        public string Desc
        {
            get { return m_user_desc; }

            set
            {
                if (value != null && value.Length > 100)
                    throw new ArgumentOutOfRangeException("Invalid value for UserDesc", value, value.ToString());

                m_isChanged |= (m_user_desc != value); m_user_desc = value;
            }
        }
	
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 

        /// <summary>
        /// propiedades utilizadas en los reportes
        /// </summary>
        public string State
        {
            get
            {
                if (m_active_user)
                {
                    return "Activo";
                }
                else
                {
                    return "Inactivo";
                }
            }
        }
        public string LastChangeDate
        {
            get
            {
                if (m_user_password_id.DLastChange == null)
                {
                    return "";
                }
                else
                {
                    return m_user_password_id.DLastChange.Value.ToString("dd/M/yyyy HH:m");
                }
            }
        }
        public override string Key
        {
            get
            {
                return m_user_id.ToString();
            }
            set
            {
                m_user_id = Convert.ToInt32(value);
            }
        }
    }
}
