/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class UserTypeEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_user_type_id; 
		private IList m_UsersList; 
		private string m_user_type_desc; 		
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public UserTypeEntity()
		{
			m_user_type_id = 0; 
			m_UsersList = new ArrayList(); 
			m_user_type_desc = String.Empty; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public UserTypeEntity(
			int user_type_id, 
			string user_type_desc)
			: this()
		{
			m_user_type_id = user_type_id;
			m_user_type_desc = user_type_desc;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_user_type_id; }
			set
			{
				m_isChanged |= ( m_user_type_id != value ); 
				m_user_type_id = value;
			}

		}
			
		public IList UsersList
		{
			get
			{
				return m_UsersList;
			}
			set
			{
				m_UsersList = value;
			}
		}

		/// <summary>
		/// tipo de usuario (usuario local windows, usuario de dominio windows, usuario de SQL Server, usuario Unix, etc)
		/// </summary>
		public string Desc
		{
			get { return m_user_type_desc; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for UserTypeDesc", value, "null");
				
				if(  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for UserTypeDesc", value, value.ToString());
				
				m_isChanged |= (m_user_type_desc != value); m_user_type_desc = value;
			}
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
	
        public override string Key
        {
            get
            {
                return m_user_type_id.ToString();
            }
            set
            {
                m_user_type_id = Convert.ToInt32(value);
            }
        }
        public override string ToString()
        {
            return this.Desc;
        }
    }
}
