/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class VencPwdAppLogDetEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

        private int m_batch_vencpwdappdet_log_id;
        private VencPwdAppLogEntity m_ejecucion;
        private int m_folio;
        private string m_aplicativo;
        private string m_usuario_app;
        private string m_email_usr_seg;
        private DateTime? m_fecha_ejecucion;
        private int m_dias_restantes;
        private string m_resultado;
        private string m_observaciones;
        #endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
        public VencPwdAppLogDetEntity()
		{
            m_batch_vencpwdappdet_log_id = 0;
            m_ejecucion = new VencPwdAppLogEntity();
        }
		#endregion // End of Default ( Empty ) Class Constuctor


		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
            get { return m_batch_vencpwdappdet_log_id; }
			set
			{
                m_isChanged |= (m_batch_vencpwdappdet_log_id != value);
                m_batch_vencpwdappdet_log_id = value;
			}

		}

        /// <summary>
        /// 
        /// </summary>
        public VencPwdAppLogEntity Ejecucion
        {
            get { return m_ejecucion; }
            set
            {
                m_isChanged |= (m_ejecucion != value);
                m_ejecucion = value;
            }

        }

        public int Folio
        {
            get { return m_folio; }
            set
            {
                m_isChanged |= (m_folio != value);
                m_folio = value;
            }
        }

        public string Aplicativo
        {
            get { return m_aplicativo; }
            set
            {
                m_isChanged |= (m_aplicativo != value);
                m_aplicativo = value;
            }
        }

        public string UsuarioApp
        {
            get { return m_usuario_app; }
            set
            {
                m_isChanged |= (m_usuario_app != value);
                m_usuario_app = value;
            }
        }

        public string EmailUsrSeg
        {
            get { return m_email_usr_seg; }
            set
            {
                m_isChanged |= (m_email_usr_seg != value);
                m_email_usr_seg = value;
            }
        }

        public DateTime? FechaEjecucion
        {
            get { return m_fecha_ejecucion; }
            set
            {
                m_isChanged |= (m_fecha_ejecucion != value);
                m_fecha_ejecucion = value;
            }
        }

        public int DiasRestantes
        {
            get { return m_dias_restantes; }
            set
            {
                m_isChanged |= (m_dias_restantes != value);
                m_dias_restantes = value;
            }
        }

        public string Resultado
        {
            get { return m_resultado; }
            set
            {
                m_isChanged |= (m_resultado != value);
                m_resultado = value;
            }
        }

        public string Observaciones
        {
            get { return m_observaciones; }
            set
            {
                m_isChanged |= (m_observaciones != value);
                m_observaciones = value;
            }
        }

        #endregion
        public override string Key
        {
            get
            {
                return m_batch_vencpwdappdet_log_id.ToString();
            }
            set
            {
                m_batch_vencpwdappdet_log_id = Convert.ToInt32(value);
            }
        }
	}
}
