/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class VencPwdAppLogEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

        private int m_batch_vencpwdapp_log_id;
        private DateTime? m_fecha_ejecucion;
        private int m_cantidad_vencimientos;
        private string m_usuario;
        private string m_resultado;
        private string m_observaciones;
        #endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
        public VencPwdAppLogEntity()
		{
            m_batch_vencpwdapp_log_id = 0;
		}
		#endregion // End of Default ( Empty ) Class Constuctor


		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
            get { return m_batch_vencpwdapp_log_id; }
			set
			{
                m_isChanged |= (m_batch_vencpwdapp_log_id != value);
                m_batch_vencpwdapp_log_id = value;
			}

		}


        public string Usuario
        {
            get { return m_usuario; }
            set
            {
                m_isChanged |= (m_usuario != value);
                m_usuario = value;
            }
        }
        public DateTime? FechaEjecucion
        {
            get { return m_fecha_ejecucion; }
            set
            {
                m_isChanged |= (m_fecha_ejecucion != value);
                m_fecha_ejecucion = value;
            }
        }

        public int CantidadVencimientos
        {
            get { return m_cantidad_vencimientos; }
            set
            {
                m_isChanged |= (m_cantidad_vencimientos != value);
                m_cantidad_vencimientos = value;
            }
        }

        public string Resultado
        {
            get { return m_resultado; }
            set
            {
                m_isChanged |= (m_resultado != value);
                m_resultado = value;
            }
        }

        public string Observaciones
        {
            get { return m_observaciones; }
            set
            {
                m_isChanged |= (m_observaciones != value);
                m_observaciones = value;
            }
        }
        
        #endregion
        public override string Key
        {
            get
            {
                return m_batch_vencpwdapp_log_id.ToString();
            }
            set
            {
                m_batch_vencpwdapp_log_id = Convert.ToInt32(value);
            }
        }
	}
}
