/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
    public sealed class vwCantRqstGrpPwdEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

        private int m_id;
        private int m_RqstGrpId;
        private int m_UserPasswordId;
        private int m_CantPwdAssoc;
        #endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public vwCantRqstGrpPwdEntity()
		{
			m_id = 0; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor


		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_id; }
			set
			{
				m_isChanged |= ( m_id != value ); 
				m_id = value;
			}

		}

        public int RqstGrpId
		{
            get { return m_RqstGrpId; }
			set
			{
                m_isChanged |= (m_RqstGrpId != value);
                m_RqstGrpId = value;
			}

		}

        public int UserPasswordId
		{
            get { return m_UserPasswordId; }
			set
			{
                m_isChanged |= (m_UserPasswordId != value);
                m_UserPasswordId = value;
			}

		}
        /// <summary>
        /// Indicates how many passwords are associated to the group
        /// </summary>
        public int CantPwdAssoc
		{
            get { return m_CantPwdAssoc; }
			set
			{
                m_isChanged |= (m_CantPwdAssoc != value);
                m_CantPwdAssoc = value;
			}

		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
	
        public override string Key
        {
            get
            {
                return this.m_id.ToString();
            }
            set
            {
                this.m_id = Convert.ToInt32(value);
            }
        }

    }
}
