/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class VwPerfilUsuarioEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_id; 
		private int m_user_id; 
		private string m_username; 
		private string m_fullname; 
		private string m_user_domain;
        private int m_role_id;
        private string m_role_name;
        #endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public VwPerfilUsuarioEntity()
		{
            m_id = 0; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor


		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_id; }
			set
			{
                m_isChanged |= (m_id != value);
                m_id = value;
			}

		}
		public int UserId
		{
			get { return m_user_id; }
			set
			{
				m_isChanged |= ( m_user_id != value ); 
				m_user_id = value;
			}

		}
        /// <summary>
		/// nombre de usuario. En un principio sería el usuario del dominio
		/// </summary>
		public string UserName
		{
			get { return m_username; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for Username", value, "null");
				
				if(  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for Username", value, value.ToString());
				
				m_isChanged |= (m_username != value); m_username = value;
			}
		}
			
		/// <summary>
		/// nombre completo del usuario
		/// </summary>
		public string FullName
		{
			get { return m_fullname; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for Fullname", value, "null");
				
				if(  value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for Fullname", value, value.ToString());
				
				m_isChanged |= (m_fullname != value); m_fullname = value;
			}
		}
			
		/// <summary>
		/// Dominio al cual pertenece el usuario. El nombre del dominio será en formato NT Domain
		/// </summary>
        public string UserDomain
		{
			get { return m_user_domain; }

			set	
			{	
				if(  value != null &&  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for UserDomain", value, value.ToString());
				
				m_isChanged |= (m_user_domain != value); m_user_domain = value;
			}
		}

        public int RoleId
        {
            get { return m_role_id; }
            set
            {
                m_isChanged |= (m_role_id != value);
                m_role_id = value;
            }

        }
        public string RoleName
        {
            get { return m_role_name; }

            set
            {
                if (value == null)
                    throw new ArgumentOutOfRangeException("Null value not allowed for RoleName", value, "null");

                if (value.Length > 200)
                    throw new ArgumentOutOfRangeException("Invalid value for RoleName", value, value.ToString());

                m_isChanged |= (m_role_name != value); m_role_name = value;
            }
        }
	
		public bool IsChanged
		{
			get { return m_isChanged; }
		}

        #endregion
        public override string Key
        {
            get
            {
                return m_id.ToString();
            }
            set
            {
                m_id = Convert.ToInt32(value);
            }
        }
        public string IndentifUsuario
        {
            get
            {
                return m_user_id.ToString() + " - " + m_username;
            }
        }
        public string IndentifRol
        {
            get
            {
                return m_role_id.ToString() + " - " + m_role_name;
            }
        }
	}
}
