/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class VwPermisoPerfilEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_id;
        private int m_role_id;
        private string m_role_name;
        private int m_privilege_id;
        private string m_privilege_name;
        #endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public VwPermisoPerfilEntity()
		{
			m_id = 0; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor


		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_id; }
			set
			{
                m_isChanged |= (m_id != value);
                m_id = value;
			}

		}

        public int RoleId
        {
            get { return m_role_id; }
            set
            {
                m_isChanged |= (m_role_id != value);
                m_role_id = value;
            }

        }
        public string RoleName
        {
            get { return m_role_name; }

            set
            {
                if (value == null)
                    throw new ArgumentOutOfRangeException("Null value not allowed for RoleName", value, "null");

                if (value.Length > 200)
                    throw new ArgumentOutOfRangeException("Invalid value for RoleName", value, value.ToString());

                m_isChanged |= (m_role_name != value); m_role_name = value;
            }
        }
	
		public bool IsChanged
		{
			get { return m_isChanged; }
		}

        public int PrivilegeId
        {
            get { return m_privilege_id; }
            set
            {
                m_isChanged |= (m_privilege_id != value);
                m_privilege_id = value;
            }

        }

        public string PrivilegeName
        {
            get { return m_privilege_name; }

            set
            {
                if (value == null)
                    throw new ArgumentOutOfRangeException("Null value not allowed for RoleName", value, "null");

                if (value.Length > 150)
                    throw new ArgumentOutOfRangeException("Invalid value for PrivilegeName", value, value.ToString());

                m_isChanged |= (m_privilege_name != value); m_privilege_name = value;
            }
        }
	
        #endregion
        public override string Key
        {
            get
            {
                return m_id.ToString();
            }
            set
            {
                m_id = Convert.ToInt32(value);
            }
        }
        public string IndentifPermiso
        {
            get
            {
                return m_privilege_id.ToString() + " - " + m_privilege_name;
            }
        }
        public string IndentifRol
        {
            get
            {
                return m_role_id.ToString() + " - " + m_role_name;
            }
        }
	}
}
