/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class VwPhxUserRqstPwdGroupEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_pwdrqst_grp_pwd_id; 
		private int m_rqst_grp_id; 
		private string m_rqst_grp_name; 
		private int m_user_password_id; 
		private int m_auth1_usr_id; 
		private Nullable<int> m_auth2_usr_id; 
		private int m_phx_user_id; 
		private string m_username; 
		private string m_fullname; 		
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public VwPhxUserRqstPwdGroupEntity()
		{
			m_pwdrqst_grp_pwd_id = 0; 
			m_rqst_grp_id = 0; 
			m_rqst_grp_name = String.Empty; 
			m_user_password_id = 0; 
			m_auth1_usr_id = 0; 
			//m_auth2_usr_id = 0; 
			m_phx_user_id = 0; 
			m_username = String.Empty; 
			m_fullname = String.Empty; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public VwPhxUserRqstPwdGroupEntity(
			int pwdrqst_grp_pwd_id, 
			int rqst_grp_id, 
			string rqst_grp_name, 
			int user_password_id, 
			int phx_user_id, 
			string username, 
			string fullname)
			: this()
		{
			m_pwdrqst_grp_pwd_id = pwdrqst_grp_pwd_id;
			m_rqst_grp_id = rqst_grp_id;
			m_rqst_grp_name = rqst_grp_name;
			m_user_password_id = user_password_id;
			m_auth1_usr_id = 0;
			//m_auth2_usr_id = 0;
			m_phx_user_id = phx_user_id;
			m_username = username;
			m_fullname = fullname;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int PwdrqstGrpPwdId
		{
			get { return m_pwdrqst_grp_pwd_id; }
			set
			{
				m_isChanged |= ( m_pwdrqst_grp_pwd_id != value ); 
				m_pwdrqst_grp_pwd_id = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public int RqstGrpId
		{
			get { return m_rqst_grp_id; }
			set
			{
				m_isChanged |= ( m_rqst_grp_id != value ); 
				m_rqst_grp_id = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public string RqstGrpName
		{
			get { return m_rqst_grp_name; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for RqstGrpName", value, "null");
				
				if(  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for RqstGrpName", value, value.ToString());
				
				m_isChanged |= (m_rqst_grp_name != value); m_rqst_grp_name = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>
		public int UserPasswordId
		{
			get { return m_user_password_id; }
			set
			{
				m_isChanged |= ( m_user_password_id != value ); 
				m_user_password_id = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public int Auth1UsrId
		{
			get { return m_auth1_usr_id; }
			set
			{
				m_isChanged |= ( m_auth1_usr_id != value ); 
				m_auth1_usr_id = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public Nullable<int> Auth2UsrId
		{
			get { return m_auth2_usr_id; }
			set
			{
				m_isChanged |= ( m_auth2_usr_id != value ); 
				m_auth2_usr_id = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public int PhxUserId
		{
			get { return m_phx_user_id; }
			set
			{
				m_isChanged |= ( m_phx_user_id != value ); 
				m_phx_user_id = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public string Username
		{
			get { return m_username; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for Username", value, "null");
				
				if(  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for Username", value, value.ToString());
				
				m_isChanged |= (m_username != value); m_username = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>
		public string Fullname
		{
			get { return m_fullname; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for Fullname", value, "null");
				
				if(  value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for Fullname", value, value.ToString());
				
				m_isChanged |= (m_fullname != value); m_fullname = value;
			}
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
	
        public override string Key
        {
            get
            {
                return m_pwdrqst_grp_pwd_id.ToString();
            }
            set
            {
                m_pwdrqst_grp_pwd_id = Convert.ToInt32(value);
            }
        }
    }
}
