/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class vwPwdRqstGrpEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

        private int m_id;

        private int m_folio; 
		private string m_usuario;
        private int m_IDAmbiente;
		private string m_ambiente;
        private bool m_critico;
        private bool m_activo;
        private int m_IDGrupo;
        private string m_Grupo;
        private bool m_GrupoActivo;

        #endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public vwPwdRqstGrpEntity()
		{
			m_folio = 0; 
			m_usuario = String.Empty; 
			m_ambiente = String.Empty;
            m_critico = false;
            m_activo = false;
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public vwPwdRqstGrpEntity(
			string usuario, 
			string ambiente,
            int folio)
			: this()
		{
            m_folio = folio;
            m_usuario = usuario;
            m_ambiente = ambiente;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties

        public int ID
        {
            get { return m_id; }
            set { m_id = value; }
        }
        /// <summary>
		/// 
		/// </summary>
		public int Folio
		{
			get { return m_folio; }
			set
			{
				m_isChanged |= ( m_folio != value ); 
				m_folio = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public string Usuario
		{
			get { return m_usuario; }

			set	
			{	
				if( value == null )
                    throw new ArgumentOutOfRangeException("Null value not allowed for Usuario", value, "null");
				
				if(  value.Length > 500)
                    throw new ArgumentOutOfRangeException("Invalid value for Usuario", value, value.ToString());
				
				m_isChanged |= (m_usuario != value); m_usuario = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>
		public string Ambiente
		{
			get { return m_ambiente; }

			set	
			{	
				if( value == null )
                    throw new ArgumentOutOfRangeException("Null value not allowed for Ambiente", value, "null");
				
				if(  value.Length > 50)
                    throw new ArgumentOutOfRangeException("Invalid value for Ambiente", value, value.ToString());
				
				m_isChanged |= (m_ambiente != value); m_ambiente = value;
			}
		}

        public bool Critico
        {
            get { return m_critico; }
            set
            {
                m_isChanged |= (m_critico != value);
                m_critico = value;
            }

        }

        public bool Activo
        {
            get { return m_activo; }
            set
            {
                m_isChanged |= (m_activo != value);
                m_activo = value;
            }

        }

        /// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
        public int IDAmbiente
        {
            get { return m_IDAmbiente; }
            set { m_IDAmbiente = value; }
        }
        public int IDGrupo
        {
            get { return m_IDGrupo; }
            set { m_IDGrupo = value; }
        }
        public string Grupo
        {
            get { return m_Grupo; }
            set { m_Grupo = value; }
        }
        public bool GrupoActivo
        {
            get { return m_GrupoActivo; }
            set { m_GrupoActivo = value; }
        }
        #endregion

        public override string Key
        {
            get
            {
                return m_id.ToString();
            }
            set
            {
                m_id = Convert.ToInt32(value);
            }
        }
    }
}
