/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class WinDomainEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_win_domain_id; 
		private IList m_GlobalWinGroupsList; 
		private IList m_WinDomainControllersList; 
		private IList m_WinDomainUsersList; 
		private string m_nt_name; 
		private string m_ad_name; 
		private IList m_WinPCsList;
        private string m_Comments;
		private string m_ldap_path; 
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public WinDomainEntity()
		{
			m_win_domain_id = 0; 
			m_GlobalWinGroupsList = new ArrayList(); 
			m_WinDomainControllersList = new ArrayList(); 
			m_WinDomainUsersList = new ArrayList(); 
			m_WinPCsList = new ArrayList(); 
			m_nt_name = String.Empty; 
			m_ad_name = String.Empty;
            m_Comments = string.Empty;
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public WinDomainEntity(
			int win_domain_id)
			: this()
		{
			m_win_domain_id = win_domain_id;
			m_nt_name = String.Empty;
			m_ad_name = String.Empty;
            m_Comments = string.Empty;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_win_domain_id; }
			set
			{
				m_isChanged |= ( m_win_domain_id != value ); 
				m_win_domain_id = value;
			}

		}
			
		public IList GlobalWinGroupsList
		{
			get
			{
				return m_GlobalWinGroupsList;
			}
			set
			{
				m_GlobalWinGroupsList = value;
			}
		}

		public IList WinDomainControllersList
		{
			get
			{
				return m_WinDomainControllersList;
			}
			set
			{
				m_WinDomainControllersList = value;
			}
		}

		public IList WinDomainUsersList
		{
			get
			{
				return m_WinDomainUsersList;
			}
			set
			{
				m_WinDomainUsersList = value;
			}
		}

		public IList WinPCsList
		{
			get
			{
				return m_WinPCsList;
			}
			set
			{
				m_WinPCsList = value;
			}
		}

		/// <summary>
		/// nombre del dominio según formato NT
		/// </summary>
		public string NtName
		{
			get { return m_nt_name; }

			set	
			{	
				if(  value != null &&  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for NtName", value, value.ToString());
				
				m_isChanged |= (m_nt_name != value); m_nt_name = value;
			}
		}

        /// <summary>
        /// Comentarios del dominio 
        /// </summary>
        public string Comments
        {
            get { return m_Comments; }

            set
            {
                string mvalue = value;

                if (value == null)
                    mvalue = string.Empty;

                if (mvalue.Length > 255)
                    mvalue = mvalue.Substring(1, 255);

                m_isChanged |= (m_Comments != mvalue); m_Comments = mvalue;
            }
        }

		/// <summary>
		/// nombre del dominio según formato active directory
		/// </summary>
		public string AdName
		{
			get { return m_ad_name; }

			set	
			{	
				if(  value != null &&  value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for AdName", value, value.ToString());
				
				m_isChanged |= (m_ad_name != value); m_ad_name = value;
			}
		}

		/// <summary>
		/// ldap path
		/// </summary>
		public string LDAPPath
		{
			get { return m_ldap_path; }

			set
			{
				if (value != null && value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for LDAPPath", value, value.ToString());

				m_isChanged |= (m_ldap_path != value);

				m_ldap_path = value;
			}
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
        public override string Key
        {
            get
            {
                return m_win_domain_id.ToString();
            }
            set
            {
                m_win_domain_id = Convert.ToInt32(value);
            }
        }
        public override string ToString()
        {
            return m_nt_name;
        }
    }
}
