/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class WinDomainControllerEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_win_dc_id; 
		private WinDomainEntity m_win_domain_id; 
		private string m_dc_type; 
		private WinPCEntity m_win_pc_id; 
		private WinDomainUserEntity m_impersonate_user_id; 		
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public WinDomainControllerEntity()
		{
			m_win_dc_id = 0; 
			m_win_domain_id = new WinDomainEntity(); 
			m_dc_type = String.Empty; 
			m_win_pc_id = new WinPCEntity(); 
			m_impersonate_user_id = null; //new WinDomainUsers(); 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public WinDomainControllerEntity(
			int win_dc_id, 
			WinDomainEntity win_domain_id, 
			string dc_type, 
			WinPCEntity win_pc_id)
			: this()
		{
			m_win_dc_id = win_dc_id;
			m_win_domain_id = win_domain_id;
			m_dc_type = dc_type;
			m_win_pc_id = win_pc_id;
			m_impersonate_user_id = null;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_win_dc_id; }
			set
			{
				m_isChanged |= ( m_win_dc_id != value ); 
				m_win_dc_id = value;
			}

		}
			
		/// <summary>
		/// dominio al que corresponde el domain controller
		/// </summary>
		public WinDomainEntity WinDomain
		{
			get { return m_win_domain_id; }
			set
			{
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for WinDomainId", value, "null");

				m_isChanged |= ( m_win_domain_id != value ); 
				m_win_domain_id = value;
			}

		}
			
		/// <summary>
		/// tipo de DC, P: primary - B: backup
		/// </summary>
		public string Type
		{
			get { return m_dc_type; }

			set	
			{	
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for DcType", value, "null");
				
				if(  value.Length > 1)
					throw new ArgumentOutOfRangeException("Invalid value for DcType", value, value.ToString());
				
				m_isChanged |= (m_dc_type != value); m_dc_type = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>
		public WinPCEntity WinPc
		{
			get { return m_win_pc_id; }
			set
			{
				if( value == null )
					throw new ArgumentOutOfRangeException("Null value not allowed for WinPcId", value, "null");

				m_isChanged |= ( m_win_pc_id != value ); 
				m_win_pc_id = value;
			}

		}
			
		/// <summary>
		/// usuario que se usa para hacer el impersonate
		/// </summary>
		public WinDomainUserEntity ImpersonateUser
		{
			get { return m_impersonate_user_id; }
			set
			{
				m_isChanged |= ( m_impersonate_user_id != value ); 
				m_impersonate_user_id = value;
			}

		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}

		public bool IsPDC
		{
			get
			{
				if (this.Type.ToUpper() == "P")
				{
					return true;
				}
				else
				{
					return false;
				}
			}
		}

		public bool IsBDC
		{
			get
			{
				if (this.Type.ToUpper() == "B")
				{
					return true;
				}
				else
				{
					return false;
				}
			}
		}
				
		#endregion 
        public override string Key
        {
            get
            {
                return m_win_dc_id.ToString();
            }
            set
            {
                m_win_dc_id = Convert.ToInt32(value);
            }
        }
    }
}
