/*
insert license info here
*/
using System;
using System.Collections;
using System.Collections.Generic;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class WinDomainUserEntity : UserEntity
	{

		#region Private Members
		private bool m_isChanged;

		//private int m_user_id; 
		private IList<WinDomainControllerEntity> m_WinDomainControllersList; 
		private WinDomainEntity m_win_domain_id; 
		private int m_user_domain_id; 		
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public WinDomainUserEntity()
		{
			//m_user_id = 0; 
			this.Id = 0;
			m_WinDomainControllersList = new List<WinDomainControllerEntity>(); 
			m_win_domain_id = new WinDomainEntity(); 
			m_user_domain_id = 0; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public WinDomainUserEntity(
			int user_id)
			: this()
		{
			//m_user_id = user_id;
			this.Id = user_id;
			m_win_domain_id = null;
			m_user_domain_id = 0;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
		
		/*
		/// <summary>
		/// 
		/// </summary>
		public int UserId
		{
			get { return m_user_id; }
			set
			{
				m_isChanged |= ( m_user_id != value ); 
				m_user_id = value;
			}

		}
		*/
			
		public IList<WinDomainControllerEntity> WinDomainControllersList
		{
			get
			{
				return m_WinDomainControllersList;
			}
			set
			{
				m_WinDomainControllersList = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public WinDomainEntity WinDomainId
		{
			get { return m_win_domain_id; }
			set
			{
				m_isChanged |= ( m_win_domain_id != value ); 
				m_win_domain_id = value;
			}

		}
			
		/// <summary>
		/// id asignado para el usuario en el dominio por el domain controller
		/// </summary>
		public int UserDomainId
		{
			get { return m_user_domain_id; }
			set
			{
				m_isChanged |= ( m_user_domain_id != value ); 
				m_user_domain_id = value;
			}

		}
		
		/*
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
		*/
				
		#endregion 
	}
}
