/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public class WinGroupEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_win_group_id; 
		private IList m_DelegationRequestsList; 
		private IList m_GlobalWinGroupsList; 
		private IList m_LocalWinGroupsList; 
		private string m_ad_group_name; 
		private string m_nt_group_name; 		
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public WinGroupEntity()
		{
			m_win_group_id = 0; 
			m_DelegationRequestsList = new ArrayList(); 
			m_GlobalWinGroupsList = new ArrayList(); 
			m_LocalWinGroupsList = new ArrayList(); 
			m_ad_group_name = String.Empty; 
			m_nt_group_name = String.Empty; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public WinGroupEntity(
			int win_group_id)
			: this()
		{
			m_win_group_id = win_group_id;
			m_ad_group_name = String.Empty;
			m_nt_group_name = String.Empty;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
        public int Id
		{
			get { return m_win_group_id; }
			set
			{
				m_isChanged |= ( m_win_group_id != value ); 
				m_win_group_id = value;
			}

		}
			
		public IList DelegationRequestsList
		{
			get
			{
				return m_DelegationRequestsList;
			}
			set
			{
				m_DelegationRequestsList = value;
			}
		}

		public IList GlobalWinGroupsList
		{
			get
			{
				return m_GlobalWinGroupsList;
			}
			set
			{
				m_GlobalWinGroupsList = value;
			}
		}

		public IList LocalWinGroupsList
		{
			get
			{
				return m_LocalWinGroupsList;
			}
			set
			{
				m_LocalWinGroupsList = value;
			}
		}

		/// <summary>
		/// nobre del grupo de 64 caracteres para active directory
		/// </summary>
		public string AdGroupName
		{
			get { return m_ad_group_name; }

			set	
			{	
				if(  value != null &&  value.Length > 64)
					throw new ArgumentOutOfRangeException("Invalid value for AdGroupName", value, value.ToString());
				
				m_isChanged |= (m_ad_group_name != value); m_ad_group_name = value;
			}
		}
			
		/// <summary>
		/// nombre del grupo compatible con dominios nt
		/// </summary>
		public string NtGroupName
		{
			get { return m_nt_group_name; }

			set	
			{	
				if(  value != null &&  value.Length > 40)
					throw new ArgumentOutOfRangeException("Invalid value for NtGroupName", value, value.ToString());
				
				m_isChanged |= (m_nt_group_name != value); m_nt_group_name = value;
			}
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
        public override string Key
        {
            get
            {
                return m_win_group_id.ToString();
            }
            set
            {
                m_win_group_id = Convert.ToInt32(value);
            }
        }
    }
}
