/*
insert license info here
*/
using System;
using System.Collections;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
    public sealed class WinLocalUserEntity : UserEntity
	{

		#region Private Members
		private bool m_isChanged;

		//private int m_user_id; 
		private IList m_WinLocalUsersList; 
		private WinPCEntity m_win_pc_id; 		
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public WinLocalUserEntity()
		{
			//m_user_id = 0; 
			this.Id = 0;
			m_WinLocalUsersList = new ArrayList(); 
			m_win_pc_id = new WinPCEntity(); 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public WinLocalUserEntity(
			int user_id)
			: this()
		{
			//m_user_id = user_id;
			Id = user_id;
			m_win_pc_id = null;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
		
		/*
		/// <summary>
		/// 
		/// </summary>
		public int UserId
		{
			get { return m_user_id; }
			set
			{
				m_isChanged |= ( m_user_id != value ); 
				m_user_id = value;
			}

		}*/
			
		/*
		public IList WinLocalUsersList
		{
			get
			{
				return m_WinLocalUsersList;
			}
			set
			{
				m_WinLocalUsersList = value;
			}
		}
		*/

		/// <summary>
		/// 
		/// </summary>
		public WinPCEntity WinPc
		{
			get { return m_win_pc_id; }
			set
			{
				m_isChanged |= ( m_win_pc_id != value ); 
				m_win_pc_id = value;
			}

		}
		
		/*
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
		*/
        public string Domain
        {
            get
            {
                return WinPc.WinDomain.NtName;
            }
        }
        public string PCName
        {
            get
            {
                return WinPc.Name;
            }
        }
        public string NetPath
        {
            get
            {
                string strUsr = @"\\" + Domain + @"\\" + PCName + @"\" + Username;
                return strUsr;
            }
        }

		#endregion 
	}
}
