/*
insert license info here
*/
using System;
using System.Collections;
//using NHibernate;

namespace PhalanxCommon.Entities
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class WinPCEntity : BaseEntity
	{

		#region Private Members
		private bool m_isChanged;

		private int m_win_pc_id; 
		private IList m_LocalWinGroupsList; 
		private IList m_WinDomainControllersList; 
		private IList m_WinLocalUsersList; 
		private string m_pc_name;
        private string m_pc_ip;
        private string m_desc;
		private WinDomainEntity m_win_domain_id;
        private bool m_active = true;
        private bool m_checkable = true;
        #endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public WinPCEntity()
		{
			m_win_pc_id = 0; 
			m_LocalWinGroupsList = new ArrayList(); 
			m_WinDomainControllersList = new ArrayList(); 
			m_WinLocalUsersList = new ArrayList(); 
			m_pc_name = string.Empty;
            m_pc_ip = string.Empty;
            m_desc = String.Empty;
            m_win_domain_id = new WinDomainEntity(); 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
		public WinPCEntity(
			int win_pc_id)
			: this()
		{
			m_win_pc_id = win_pc_id;
			m_pc_name = string.Empty;
            m_pc_ip = string.Empty;
			m_win_domain_id = null;
            m_desc = String.Empty;
        }
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public int Id
		{
			get { return m_win_pc_id; }
			set
			{
				m_isChanged |= ( m_win_pc_id != value ); 
				m_win_pc_id = value;
			}

		}
        public bool Active
        {
            get { return m_active; }
            set
            {
                m_isChanged |= (m_active != value);
                m_active = value;
            }

        }
        public bool Checkable
        {
            get { return m_checkable; }
            set
            {
                m_isChanged |= (m_checkable != value);
                m_checkable = value;
            }

        }

		public IList LocalWinGroupsList
		{
			get
			{
				return m_LocalWinGroupsList;
			}
			set
			{
				m_LocalWinGroupsList = value;
			}
		}

		public IList WinDomainControllersList
		{
			get
			{
				return m_WinDomainControllersList;
			}
			set
			{
				m_WinDomainControllersList = value;
			}
		}

		public IList WinLocalUsersList
		{
			get
			{
				return m_WinLocalUsersList;
			}
			set
			{
				m_WinLocalUsersList = value;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		public string Name
		{
			get { return m_pc_name; }

			set	
			{	
				if(  value != null &&  value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for PcName", value, value.ToString());
				
				m_isChanged |= (m_pc_name != value); m_pc_name = value;
			}
		}

        public string Desc
        {
            get { return m_desc; }

            set
            {
                if (value != null && value.Length > 200)
                    throw new ArgumentOutOfRangeException("Invalid value for Desc", value, value.ToString());

                m_isChanged |= (m_desc != value); m_desc = value;
            }
        }

        public string PcIP
        {
            get { return m_pc_ip; }

            set
            {
                if (value != null && value.Length > 15)
                    throw new ArgumentOutOfRangeException("Invalid value for PcIP", value, value.ToString());

                m_isChanged |= (m_pc_ip != value); m_pc_ip = value;
            }
        }
	
		/// <summary>
		/// dominio al que pertenece la PC
		/// </summary>
		public WinDomainEntity WinDomain
		{
			get { return m_win_domain_id; }
			set
			{
				m_isChanged |= ( m_win_domain_id != value ); 
				m_win_domain_id = value;
			}

		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_isChanged; }
		}
				
		#endregion 
        public override string Key
        {
            get
            {
                return m_win_pc_id.ToString();
            }
            set
            {
                m_win_pc_id = Convert.ToInt32(value);
            }
        }
        public override string ToString()
        {
            return m_pc_name;
        }
    }
}
