//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TestWSInterfaceClaves.WSTickets {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TicketsDeClavesSoap", Namespace="http://tempuri.org/")]
    public partial class TicketsDeClaves : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AgregarTicketOperationCompleted;
        
        private System.Threading.SendOrPostCallback TestLDAPConfigOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TicketsDeClaves() {
            this.Url = global::TestWSInterfaceClaves.Properties.Settings.Default.TestWSInterfaceClaves_WSTickets_TicketsDeClaves;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AgregarTicketCompletedEventHandler AgregarTicketCompleted;
        
        /// <remarks/>
        public event TestLDAPConfigCompletedEventHandler TestLDAPConfigCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AgregarTicket", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AgregarTicketResultado AgregarTicket(TicketNotificacionClave ticket) {
            object[] results = this.Invoke("AgregarTicket", new object[] {
                        ticket});
            return ((AgregarTicketResultado)(results[0]));
        }
        
        /// <remarks/>
        public void AgregarTicketAsync(TicketNotificacionClave ticket) {
            this.AgregarTicketAsync(ticket, null);
        }
        
        /// <remarks/>
        public void AgregarTicketAsync(TicketNotificacionClave ticket, object userState) {
            if ((this.AgregarTicketOperationCompleted == null)) {
                this.AgregarTicketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAgregarTicketOperationCompleted);
            }
            this.InvokeAsync("AgregarTicket", new object[] {
                        ticket}, this.AgregarTicketOperationCompleted, userState);
        }
        
        private void OnAgregarTicketOperationCompleted(object arg) {
            if ((this.AgregarTicketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AgregarTicketCompleted(this, new AgregarTicketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestLDAPConfig", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TestLDAPConfig(string username, string legajo) {
            object[] results = this.Invoke("TestLDAPConfig", new object[] {
                        username,
                        legajo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TestLDAPConfigAsync(string username, string legajo) {
            this.TestLDAPConfigAsync(username, legajo, null);
        }
        
        /// <remarks/>
        public void TestLDAPConfigAsync(string username, string legajo, object userState) {
            if ((this.TestLDAPConfigOperationCompleted == null)) {
                this.TestLDAPConfigOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTestLDAPConfigOperationCompleted);
            }
            this.InvokeAsync("TestLDAPConfig", new object[] {
                        username,
                        legajo}, this.TestLDAPConfigOperationCompleted, userState);
        }
        
        private void OnTestLDAPConfigOperationCompleted(object arg) {
            if ((this.TestLDAPConfigCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TestLDAPConfigCompleted(this, new TestLDAPConfigCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TicketNotificacionClave {
        
        private string stringAutenticacionField;
        
        private int idSolicitudField;
        
        private string codigoAplicacionField;
        
        private string nombreAplicacionField;
        
        private string usuarioAplicacionField;
        
        private string passwordUsuarioField;
        
        private string dominioUsuarioField;
        
        private string usuarioField;
        
        private string legajoField;
        
        private string tipoDocumentoField;
        
        private string documentoField;
        
        private bool usaPasswordDominioField;
        
        private System.Nullable<int> solicitudIDField;
        
        private string codigoGerenciaField;
        
        private string nombreGerenciaField;
        
        private string siglaAreaField;
        
        private string descripcionAreaField;
        
        private System.Nullable<System.DateTime> fechaVigDesdeField;
        
        private string nroLegajoSoliField;
        
        private string codSubsidiariaField;
        
        private string nomSubsidiariaField;
        
        private string nomSolicitanteField;
        
        private string apeSolicitanteField;
        
        /// <remarks/>
        public string StringAutenticacion {
            get {
                return this.stringAutenticacionField;
            }
            set {
                this.stringAutenticacionField = value;
            }
        }
        
        /// <remarks/>
        public int IdSolicitud {
            get {
                return this.idSolicitudField;
            }
            set {
                this.idSolicitudField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoAplicacion {
            get {
                return this.codigoAplicacionField;
            }
            set {
                this.codigoAplicacionField = value;
            }
        }
        
        /// <remarks/>
        public string NombreAplicacion {
            get {
                return this.nombreAplicacionField;
            }
            set {
                this.nombreAplicacionField = value;
            }
        }
        
        /// <remarks/>
        public string UsuarioAplicacion {
            get {
                return this.usuarioAplicacionField;
            }
            set {
                this.usuarioAplicacionField = value;
            }
        }
        
        /// <remarks/>
        public string PasswordUsuario {
            get {
                return this.passwordUsuarioField;
            }
            set {
                this.passwordUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string DominioUsuario {
            get {
                return this.dominioUsuarioField;
            }
            set {
                this.dominioUsuarioField = value;
            }
        }
        
        /// <remarks/>
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public string Legajo {
            get {
                return this.legajoField;
            }
            set {
                this.legajoField = value;
            }
        }
        
        /// <remarks/>
        public string TipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string Documento {
            get {
                return this.documentoField;
            }
            set {
                this.documentoField = value;
            }
        }
        
        /// <remarks/>
        public bool UsaPasswordDominio {
            get {
                return this.usaPasswordDominioField;
            }
            set {
                this.usaPasswordDominioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SolicitudID {
            get {
                return this.solicitudIDField;
            }
            set {
                this.solicitudIDField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoGerencia {
            get {
                return this.codigoGerenciaField;
            }
            set {
                this.codigoGerenciaField = value;
            }
        }
        
        /// <remarks/>
        public string NombreGerencia {
            get {
                return this.nombreGerenciaField;
            }
            set {
                this.nombreGerenciaField = value;
            }
        }
        
        /// <remarks/>
        public string SiglaArea {
            get {
                return this.siglaAreaField;
            }
            set {
                this.siglaAreaField = value;
            }
        }
        
        /// <remarks/>
        public string DescripcionArea {
            get {
                return this.descripcionAreaField;
            }
            set {
                this.descripcionAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FechaVigDesde {
            get {
                return this.fechaVigDesdeField;
            }
            set {
                this.fechaVigDesdeField = value;
            }
        }
        
        /// <remarks/>
        public string NroLegajoSoli {
            get {
                return this.nroLegajoSoliField;
            }
            set {
                this.nroLegajoSoliField = value;
            }
        }
        
        /// <remarks/>
        public string CodSubsidiaria {
            get {
                return this.codSubsidiariaField;
            }
            set {
                this.codSubsidiariaField = value;
            }
        }
        
        /// <remarks/>
        public string NomSubsidiaria {
            get {
                return this.nomSubsidiariaField;
            }
            set {
                this.nomSubsidiariaField = value;
            }
        }
        
        /// <remarks/>
        public string NomSolicitante {
            get {
                return this.nomSolicitanteField;
            }
            set {
                this.nomSolicitanteField = value;
            }
        }
        
        /// <remarks/>
        public string ApeSolicitante {
            get {
                return this.apeSolicitanteField;
            }
            set {
                this.apeSolicitanteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarTicketResultado {
        
        private bool exitoField;
        
        private string mensajeField;
        
        /// <remarks/>
        public bool Exito {
            get {
                return this.exitoField;
            }
            set {
                this.exitoField = value;
            }
        }
        
        /// <remarks/>
        public string Mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void AgregarTicketCompletedEventHandler(object sender, AgregarTicketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AgregarTicketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AgregarTicketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AgregarTicketResultado Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AgregarTicketResultado)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void TestLDAPConfigCompletedEventHandler(object sender, TestLDAPConfigCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TestLDAPConfigCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TestLDAPConfigCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591