//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotifClavesWeb.COBISDesbloqueo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.cts.ast", ConfigurationName="COBISDesbloqueo.BloqueoDesbloqueoUsuariosCobis")]
    public interface BloqueoDesbloqueoUsuariosCobis {
        
        // CODEGEN: El parámetro 'executeReturn' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="execute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="executeReturn")]
        NotifClavesWeb.COBISDesbloqueo.executeResponse execute(NotifClavesWeb.COBISDesbloqueo.executeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://domain.webservices.common.cts.ast")]
    public partial class RequestConnection : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userField;
        
        private string passwordField;
        
        private string applicationIDField;
        
        private string sessionIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string applicationID {
            get {
                return this.applicationIDField;
            }
            set {
                this.applicationIDField = value;
                this.RaisePropertyChanged("applicationID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string sessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
                this.RaisePropertyChanged("sessionID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.bloqueodesbloqueousuarioscobis.ecobis.cobiscorp")]
    public partial class FuncionarioRet : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int o_errorField;
        
        private string o_mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int o_error {
            get {
                return this.o_errorField;
            }
            set {
                this.o_errorField = value;
                this.RaisePropertyChanged("o_error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string o_mensaje {
            get {
                return this.o_mensajeField;
            }
            set {
                this.o_mensajeField = value;
                this.RaisePropertyChanged("o_mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://domain.webservices.common.cts.ast")]
    public partial class ServiceError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<long> codeField;
        
        private string messageField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public System.Nullable<long> code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://transport.webservices.cts.ast")]
    public partial class ExecuteRet : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ServiceError serviceErrorField;
        
        private FuncionarioRet funcionarioRetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public ServiceError serviceError {
            get {
                return this.serviceErrorField;
            }
            set {
                this.serviceErrorField = value;
                this.RaisePropertyChanged("serviceError");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public FuncionarioRet funcionarioRet {
            get {
                return this.funcionarioRetField;
            }
            set {
                this.funcionarioRetField = value;
                this.RaisePropertyChanged("funcionarioRet");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://transport.webservices.cts.ast")]
    public partial class BloqueoDesbloqueFil : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string i_c_loginField;
        
        private string i_c_estadoField;
        
        private string i_m_quien_llamaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string i_c_login {
            get {
                return this.i_c_loginField;
            }
            set {
                this.i_c_loginField = value;
                this.RaisePropertyChanged("i_c_login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string i_c_estado {
            get {
                return this.i_c_estadoField;
            }
            set {
                this.i_c_estadoField = value;
                this.RaisePropertyChanged("i_c_estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string i_m_quien_llama {
            get {
                return this.i_m_quien_llamaField;
            }
            set {
                this.i_m_quien_llamaField = value;
                this.RaisePropertyChanged("i_m_quien_llama");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="execute", WrapperNamespace="http://webservices.cts.ast", IsWrapped=true)]
    public partial class executeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.cts.ast", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public NotifClavesWeb.COBISDesbloqueo.RequestConnection requestConnection;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.cts.ast", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public NotifClavesWeb.COBISDesbloqueo.BloqueoDesbloqueFil loginFiltro;
        
        public executeRequest() {
        }
        
        public executeRequest(NotifClavesWeb.COBISDesbloqueo.RequestConnection requestConnection, NotifClavesWeb.COBISDesbloqueo.BloqueoDesbloqueFil loginFiltro) {
            this.requestConnection = requestConnection;
            this.loginFiltro = loginFiltro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="executeResponse", WrapperNamespace="http://webservices.cts.ast", IsWrapped=true)]
    public partial class executeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservices.cts.ast", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public NotifClavesWeb.COBISDesbloqueo.ExecuteRet executeReturn;
        
        public executeResponse() {
        }
        
        public executeResponse(NotifClavesWeb.COBISDesbloqueo.ExecuteRet executeReturn) {
            this.executeReturn = executeReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BloqueoDesbloqueoUsuariosCobisChannel : NotifClavesWeb.COBISDesbloqueo.BloqueoDesbloqueoUsuariosCobis, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BloqueoDesbloqueoUsuariosCobisClient : System.ServiceModel.ClientBase<NotifClavesWeb.COBISDesbloqueo.BloqueoDesbloqueoUsuariosCobis>, NotifClavesWeb.COBISDesbloqueo.BloqueoDesbloqueoUsuariosCobis {
        
        public BloqueoDesbloqueoUsuariosCobisClient() {
        }
        
        public BloqueoDesbloqueoUsuariosCobisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BloqueoDesbloqueoUsuariosCobisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BloqueoDesbloqueoUsuariosCobisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BloqueoDesbloqueoUsuariosCobisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NotifClavesWeb.COBISDesbloqueo.executeResponse NotifClavesWeb.COBISDesbloqueo.BloqueoDesbloqueoUsuariosCobis.execute(NotifClavesWeb.COBISDesbloqueo.executeRequest request) {
            return base.Channel.execute(request);
        }
        
        public NotifClavesWeb.COBISDesbloqueo.ExecuteRet execute(NotifClavesWeb.COBISDesbloqueo.RequestConnection requestConnection, NotifClavesWeb.COBISDesbloqueo.BloqueoDesbloqueFil loginFiltro) {
            NotifClavesWeb.COBISDesbloqueo.executeRequest inValue = new NotifClavesWeb.COBISDesbloqueo.executeRequest();
            inValue.requestConnection = requestConnection;
            inValue.loginFiltro = loginFiltro;
            NotifClavesWeb.COBISDesbloqueo.executeResponse retVal = ((NotifClavesWeb.COBISDesbloqueo.BloqueoDesbloqueoUsuariosCobis)(this)).execute(inValue);
            return retVal.executeReturn;
        }
    }
}
