CREATE TABLE [dbo].[M4_CLASSWORX_EMPLEADOS] (
    [ID_SOCIEDAD]    VARCHAR (2)  NOT NULL,
    [ID_EMPLEADO]    VARCHAR (10) NOT NULL,
    [NOMBRE]         VARCHAR (25) NOT NULL,
    [APELLIDO]       VARCHAR (30) NOT NULL,
    [ID_TIPO_DOC]    VARCHAR (50) NOT NULL,
    [TIPO_DOC]       VARCHAR (40) NOT NULL,
    [NUM_DOCUMENTO]  VARCHAR (10) NOT NULL,
    [CALLE]          VARCHAR (30) NOT NULL,
    [NUM_CALLE]      VARCHAR (5)  NULL,
    [PISO]           VARCHAR (10) NULL,
    [DEPARTAMENTO]   VARCHAR (10) NULL,
    [N_ESTADO_CIVIL] VARCHAR (50) NULL,
    [FEC_NACIMIENTO] DATETIME     NOT NULL,
    [TELEFONO]       VARCHAR (50) NOT NULL,
    [TORRE]          VARCHAR (50) NULL,
    [BLOQUE]         VARCHAR (50) NULL,
    [LOCALIDAD]      VARCHAR (50) NULL
);

