CREATE TABLE [dbo].[ticket_notificacion_clave] (
    [tnc_id]                INT           IDENTITY (1, 1) NOT NULL,
    [tnc_numero]            INT           NOT NULL,
    [tnc_app_id]            INT           NOT NULL,
    [tnc_app_user]          VARCHAR (50)  NOT NULL,
    [tnc_app_user_pass]     VARCHAR (50)  NULL,
    [tnc_user_domain]       VARCHAR (50)  NOT NULL,
    [tnc_user]              VARCHAR (50)  NOT NULL,
    [tnc_legajo]            VARCHAR (50)  NULL,
    [tnc_tipo_doc]          VARCHAR (50)  NOT NULL,
    [tnc_nro_doc]           VARCHAR (50)  NOT NULL,
    [tnc_is_dom_pass]       TINYINT       NOT NULL,
    [tnc_fecha]             DATETIME      NOT NULL,
    [tnc_fecha_ace_tyc]     DATETIME      NULL,
    [tnc_errado]            TINYINT       NOT NULL,
    [tnc_fecha_procesado]   DATETIME      NULL,
    [tnc_num_sol_alta]      INT           NULL,
    [tnc_num_leg_solicitud] VARCHAR (10)  NULL,
    [tnc_nomb_emp_sol]      VARCHAR (255) NULL,
    [tnc_ape_emp_sol]       VARCHAR (255) NULL,
    [tnc_fecha_vigencia]    DATETIME      NULL,
    [tnc_codigo_gerencia]   VARCHAR (3)   NULL,
    [tnc_nombre_gerencia]   VARCHAR (40)  NULL,
    [tnc_sigla_area]        VARCHAR (10)  NULL,
    [tnc_desc_area]         VARCHAR (40)  NULL,
    [tnc_cod_emp_sub]       VARCHAR (10)  NULL,
    [tnc_nomb_emp_sub]      VARCHAR (40)  NULL,
    [m_tnc_corregido]       TINYINT       DEFAULT ((0)) NOT NULL,
    [tnc_token]             VARCHAR (40)  NULL,
    [tnc_mail_id]           INT           NULL,
    [tnc_att_fecha]         DATETIME      NULL,
    [tnc_att_terminal]      VARCHAR (50)  NULL,
    [tnc_att_usuario]       VARCHAR (100) NULL
);

