ALTER TABLE [dbo].[Database_Types]
    ADD CONSTRAINT [IX_DataBase_Types_UniqueCode] UNIQUE NONCLUSTERED ([db_type_code] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

