ALTER TABLE [dbo].[Win_Domains]
    ADD CONSTRAINT [IX_Win_Domains_unique_nt_name] UNIQUE NONCLUSTERED ([nt_name] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

