ALTER TABLE [dbo].[aplicacion_notificacion_clave]
    ADD CONSTRAINT [PK_aplicacion_notificacion_clave] PRIMARY KEY CLUSTERED ([anc_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

