ALTER TABLE [dbo].[audit_permisos]
    ADD CONSTRAINT [PK_audit_permisos] PRIMARY KEY CLUSTERED ([audit_permisos_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

