ALTER TABLE [dbo].[audit_usuarios]
    ADD CONSTRAINT [PK_audit_usuarios] PRIMARY KEY CLUSTERED ([aud_usr_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

