ALTER TABLE [dbo].[audit_ticket_notificacion]
    ADD CONSTRAINT [PK_audit_notificacion_ticket] PRIMARY KEY CLUSTERED ([atn_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

