ALTER TABLE [dbo].[AS400_users]
    ADD CONSTRAINT [PK_AS400_users] PRIMARY KEY CLUSTERED ([user_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

