ALTER TABLE [dbo].[AS400]
    ADD CONSTRAINT [PK_AS400] PRIMARY KEY CLUSTERED ([as_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

