ALTER TABLE [dbo].[accion_item_chk_win_local_user]
    ADD CONSTRAINT [PK_accion_item_chk_win_local_user] PRIMARY KEY CLUSTERED ([id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

