ALTER TABLE [dbo].[audit_phx_user]
    ADD CONSTRAINT [PK_audit_phx_user] PRIMARY KEY CLUSTERED ([audit_phx_user_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

