ALTER TABLE [dbo].[Building]
    ADD CONSTRAINT [PK_Building] PRIMARY KEY CLUSTERED ([bld_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

