ALTER TABLE [dbo].[Communication_Device_User_Protocol]
    ADD CONSTRAINT [PK_Communication_Device_User_Protocol] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

