ALTER TABLE [dbo].[Communication_Devices]
    ADD CONSTRAINT [PK_Communication_Devices] PRIMARY KEY CLUSTERED ([cm_dv_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

