ALTER TABLE [dbo].[Devices]
    ADD CONSTRAINT [PK_Devices] PRIMARY KEY CLUSTERED ([dv_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

