ALTER TABLE [dbo].[Demo_Conf]
    ADD CONSTRAINT [PK_Demo_Conf] PRIMARY KEY CLUSTERED ([demo_conf_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

