ALTER TABLE [dbo].[Data_Bases]
    ADD CONSTRAINT [PK_Data_Bases] PRIMARY KEY CLUSTERED ([db_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

