ALTER TABLE [dbo].[evento_login]
    ADD CONSTRAINT [PK_evento_login] PRIMARY KEY CLUSTERED ([evento_login_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

