ALTER TABLE [dbo].[followup_request_group]
    ADD CONSTRAINT [PK_followup_request_group] PRIMARY KEY CLUSTERED ([frg_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

