ALTER TABLE [dbo].[mail_alert]
    ADD CONSTRAINT [PK_mail_alert] PRIMARY KEY CLUSTERED ([mail_alert_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

