ALTER TABLE [dbo].[phx_privilege]
    ADD CONSTRAINT [PK_phx_privilege] PRIMARY KEY CLUSTERED ([phx_privilege_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

