ALTER TABLE [dbo].[Phx_Roles_Users]
    ADD CONSTRAINT [PK_Phx_Roles_Users] PRIMARY KEY CLUSTERED ([phx_role_usr_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

