ALTER TABLE [dbo].[Protocol_Communication_Device]
    ADD CONSTRAINT [PK_Protocol_Communication_Device] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

