ALTER TABLE [dbo].[phx_config]
    ADD CONSTRAINT [PK_phx_config] PRIMARY KEY CLUSTERED ([code] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

