ALTER TABLE [dbo].[phx_privilege_group]
    ADD CONSTRAINT [PK_phx_privilege_group] PRIMARY KEY CLUSTERED ([phx_prv_grp_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

