ALTER TABLE [dbo].[Phx_Roles]
    ADD CONSTRAINT [PK_Phx_Roles] PRIMARY KEY CLUSTERED ([phx_role_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

