ALTER TABLE [dbo].[Requests]
    ADD CONSTRAINT [PK_Password_Queries] PRIMARY KEY CLUSTERED ([request_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

