ALTER TABLE [dbo].[Pwd_Lock_types]
    ADD CONSTRAINT [PK_Pwd_Lock_types] PRIMARY KEY CLUSTERED ([pwd_lock_type_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

