ALTER TABLE [dbo].[phx_privilege_role]
    ADD CONSTRAINT [PK_phx_privilege_role] PRIMARY KEY CLUSTERED ([phx_priv_role_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

