ALTER TABLE [dbo].[Phx_Log]
    ADD CONSTRAINT [PK_Phx_Log] PRIMARY KEY CLUSTERED ([phx_log_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

