ALTER TABLE [dbo].[Phx_Users_Groups]
    ADD CONSTRAINT [PK_Phx_Users_Groups] PRIMARY KEY CLUSTERED ([phx_usr_grp_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

