ALTER TABLE [dbo].[Phx_Users]
    ADD CONSTRAINT [PK_Phx_Users] PRIMARY KEY CLUSTERED ([phx_user_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

