ALTER TABLE [dbo].[phx_contingencia]
    ADD CONSTRAINT [PK_phx_contingencia] PRIMARY KEY CLUSTERED ([phx_cont_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

