ALTER TABLE [dbo].[Phx_User_Superior]
    ADD CONSTRAINT [PK_Phx_User_Superior] PRIMARY KEY CLUSTERED ([sup_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

