ALTER TABLE [dbo].[Requests_Groups]
    ADD CONSTRAINT [PK_Qry_Groups] PRIMARY KEY CLUSTERED ([rqst_grp_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

