ALTER TABLE [dbo].[Rqst_Grps_Pwds]
    ADD CONSTRAINT [PK_Qry_Grps_Pwds] PRIMARY KEY CLUSTERED ([pwdrqst_grp_pwd_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

