ALTER TABLE [dbo].[Request_States]
    ADD CONSTRAINT [PK_Request_States] PRIMARY KEY CLUSTERED ([rqst_state_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

