ALTER TABLE [dbo].[Rqst_Grps_Deleg]
    ADD CONSTRAINT [PK_Rqst_Grps_Deleg] PRIMARY KEY CLUSTERED ([delrqst_grp_delg_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

