ALTER TABLE [dbo].[Requests_Notes]
    ADD CONSTRAINT [PK_Requests_Notes] PRIMARY KEY CLUSTERED ([request_note_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

