ALTER TABLE [dbo].[ticket_notificacion_clave]
    ADD CONSTRAINT [PK_ticket_notificacion_clave] PRIMARY KEY CLUSTERED ([tnc_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

