ALTER TABLE [dbo].[Users_Passwords]
    ADD CONSTRAINT [PK_Users_Passwords] PRIMARY KEY CLUSTERED ([user_password_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

