ALTER TABLE [dbo].[Unix]
    ADD CONSTRAINT [PK_Unix] PRIMARY KEY CLUSTERED ([unx_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

