ALTER TABLE [dbo].[User_Types]
    ADD CONSTRAINT [PK_User_Types] PRIMARY KEY CLUSTERED ([user_type_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

