ALTER TABLE [dbo].[Win_PCs]
    ADD CONSTRAINT [PK_Win_PCs] PRIMARY KEY CLUSTERED ([win_pc_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

