ALTER TABLE [dbo].[Win_Domains]
    ADD CONSTRAINT [PK_Win_Domains] PRIMARY KEY CLUSTERED ([win_domain_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

