ALTER TABLE [dbo].[Win_Domain_Controllers]
    ADD CONSTRAINT [PK_Win_Domain_Controllers] PRIMARY KEY CLUSTERED ([win_dc_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

