ALTER TABLE [dbo].[Phx_Users]
    ADD CONSTRAINT [Unique_Phx_Users_Username_Domain] UNIQUE NONCLUSTERED ([username] ASC, [user_domain] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

