ALTER TABLE [dbo].[Phx_Roles_Users]
    ADD CONSTRAINT [Unique_Phx_Roles_Users] UNIQUE NONCLUSTERED ([phx_role_id] ASC, [phx_user_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

