ALTER TABLE [dbo].[Pwd_Lock_types]
    ADD CONSTRAINT [Unique_Pwd_Lock_type_codes] UNIQUE NONCLUSTERED ([pwd_lock_type_code] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

